elastic/apm-agent-nodejs

- package.json
- test/integration/api-schema/_utils.js
- test/integration/api-schema/basic.js
- test/integration/api-schema/download-json-schemas.sh
In https://github.com/elastic/apm-server/pull/4393 apm-server updated to
new and generate JSON schema. This commit updates the tests to get the
schema files from the new location and switches from the
"is-my-json-valid" JSON Schema validator to the more capable "ajv"
validator. This also changes the schema file cache dir so developers
need not manually delete the old cache.
Fixes #1867
> test(api-schema): update to new apm-server schemata

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- index.d.ts
- lib/config.js
- lib/instrumentation/http-shared.js
- lib/wildcard-matcher.js
- package.json
- test/central-config-enabled.js
- test/config.js
- test/instrumentation/modules/http/blacklisting.js
- test/wildcard-matcher.js
Will Fix: elastic/apm-agent-nodejs#1689
Implements `ELASTIC_TRANSACTION_IGNORE_URL`/`transactionIgnoreUrls` configuration for wildcard URL ignoring.  The intent of this new configuration is to gives users the ability to skip generating transactions for a request to a URL that matches an exact string, or a URL that matches simple wildcard pattern.  This wildcard pattern will behave consistently across language agents.
This PR leaves the existing `ignoreUrls` configuration in place to allow users access to more powerful regular expression matching _and_ to preserve existing functionality for users using this older configuration setting. 
This PR also introduces a new dependency, [`escape-string-regexp`](https://www.npmjs.com/package/escape-string-regexp).  In order to implement the …
> feat: transaction_ignore_urls wildcard matching

- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/mongodb.js
- test/instrumentation/modules/mongodb.js
> feat: set "destination" context for "mongodb" instrumentation

- CHANGELOG.asciidoc
- lib/instrumentation/modules/fastify.js
Hi,
This module seems to break fastify v3 when used with typescript as `default` and `fastify` are not exposed on the exported module anymore, so the imports are invalid. Also, starting from fastify 3.3 a few properties are exposed directly on the request but I don't think it's worth an entirely different wrapper.
> feat: support fastify 3

- CHANGELOG.asciidoc
- CONTRIBUTING.md
We're in the process of moving dev process to have PRs include an update to CHANGELOG.asciidoc so that we are authoring the changelog as part of making changes.  We started by adding unreleased changes to the *block comment* at the top of the changelog file. One pain point with that is that you cannot see those in the GitHub rendering.
I asked Brandon and he says that having an "Unreleased" section will not cause a problem for doc rendering for releases. In retrospect, I understand why because we have the release branches for those.
> chore: have a visible 'Unreleased' section in changelog

- .gitattributes
One (possibly minor) concern with having PRs include updates to CHANGELOG.asciidoc is more common merge conflicts. Time will tell if that proves to be a PITA and barrier.
Gil suggested using:
```
% cat .gitattributes
CHANGELOG.asciidoc merge=union
```
from the docs:
Run 3-way file level merge for text files, but take lines from both
versions, instead of leaving conflict markers. This tends to leave the
added lines in the resulting file in random order and the user should
verify the result. Do not use this if you do not understand the
implications.
> chore: use merge=union for changelog

- test/filters.js
This PR fixes the intent of the test in `test/filters.js`.
The intent of this test is to make sure that both the request response objects are filtered correctly. 
The problem with the old test was that `context.request.headers` and `context.response.headers` referenced _the same_ object.  
This means when `context.request.headers` was filtered that `context.response.headers` also appeared filtered regardless of whether code explicitly filtered it or not. 
This PR ensures that `context.request.headers` and `context.response.headers` are two separate object instances. 
This is a follow on PR to https://github.com/elastic/apm-agent-nodejs/pull/1886
> fix: fixes intent of filter test

- docs/configuration.asciidoc
This allows one to search for central config var names in these docs
when starting from central config. It also allows searching the
configuration doc page for "central" to find all centrally controllable
vars -- helpful given that the "Dynamic" badge isn't searchable.
> docs: document the central config var name for appropriate vars

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- index.d.ts
- lib/agent.js
- lib/parsers.js
- test/instrumentation/index.js
- test/parsers.js
This adds a `captureAttributes` boolean option to `apm.captureError()` to
allow *disabling* the automatic capture of Error object properties. This
is useful for cases where those properties should not be sent to the APM
Server, e.g. for performance (large string fields) or security (PII data).
> feat: add `captureAttributes` option to `apm.captureError()`

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- lib/config.js
- test/central-config-enabled.js
- test/config.js
Fix parsing of comma-separated strings for relevant config vars to allow
whitespace around the commas. E.g.:
export ELASTIC_APM_TRANSACTION_IGNORE_URLS='/ping, /metrics*'
This affects ARRAY_OPTS and KEY_VALUE_OPTS.
Also, correct the environment variable for setting `transactionIgnoreUrl` from
`ELASTIC_TRANSACTION_IGNORE_URLS` to `ELASTIC_APM_TRANSACTION_IGNORE_URLS`.
Fixes: #1913
> fix: trim whitespace around comma-separate string config vars

- CHANGELOG.asciidoc
- lib/filters/http-headers.js
- lib/redact-secrets/index.js
- lib/redact-secrets/is-secret.js
- package.json
- test/redact-secrets/is-secret.js
- test/redact-secrets/redact-secrets.js
- test/test.js
This PR comes out of work in #1898.  
The functionality of the new `sanitize_field_names` functionality and our existing filters (implemented via the external `redact-secret` module and it's dependency, `is-secret`) overlap slightly. It would greatly simplify things if these modules were forked and pulled into the agent proper.
> Pull redact-secret and is-secret into Agent

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- lib/parsers.js
- test/parsers.js
PR for #1925.  If a middleware processes `request.body` as Buffer, rather than report the potentially large binary object we'll report the string `<Buffer>` to indicate binary data was detected. 
Also updates public docs to reflect this.
> feat: improve/change processing of Buffer objects in post body

- docs/configuration.asciidoc
Dependent on landing https://github.com/elastic/apm-agent-nodejs/pull/1937 on landing, part of https://github.com/elastic/apm-agent-nodejs/issues/1815 -- this PR contains the documentation for the new `cloudProdiver` configuration variable.
> feat: docs for cloud provider configuration

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- index.d.ts
- lib/agent.js
- test/agent.js
This will be used by ecs-logging-js libs to set "service.name" in log
records.
> feat: add apm.getServiceName()

- .ci/Jenkinsfile
Enable GitHub check in addition to the GitHub commit status.
Add a `.Status` GitHub check with the digested build details, similar to the GitHub PR comments.
NOTE: This is a pretty new `feature`, we are working on adding more features, so feel free to suggest what things could be good to see. :)
- ~~[ ] Add tests
- ~~[ ] Update TypeScript typings~~
- ~~[ ] Update documentation~~
- ~~[ ] Add CHANGELOG.asciidoc entry~~
- ~~[ ] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)~~
> jenkins: enable github check .status

- CHANGELOG.asciidoc
- docs/release-notes.asciidoc
- lib/config.js
- test/central-config-enabled.js
> fix: local `cloudProvider` config is overwritten by a central config

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- lib/config.js
- test/central-config-enabled.js
- test/config.js
This implements the transaction_sample_rate precision spec (https://github.com/elastic/apm/blob/master/specs/agents/tracing-sampling.md#transaction_sample_rate-configuration), added in https://github.com/elastic/apm/pull/335.
Fixes: #1817
> feat: transaction_sample_rate precision

- CHANGELOG.asciidoc
- lib/metrics/runtime.js
- test/metrics/breakdown.js
The nodejs runtime metrics code define both
nodejs.eventloop.delay.ns
nodejs.eventloop.delay.avg.ms
but only the latter is every filled with a value. The former
is initialized to 0 and always reported as 0. This stems from the
original addition in #1021.
The apm-contrib Node.js dashboard only uses the latter.
https://github.com/elastic/apm-contrib/tree/master/apm-agent-nodejs/dashboards/
Refs: #1021
> chore: drop unused 'nodejs.eventloop.delay.ns' metric

- docs/configuration.asciidoc
- index.d.ts
- lib/config.js
- test/config.js
Partially implements: https://github.com/elastic/apm-agent-nodejs/issues/1956
This PR adds [the `ignore_message_queues`](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-messaging.md#ignore_message_queues-configuration) configuration to the agent.  This is a prerequisite for supporting AWS SQS instrumentation.  This PR does not include a CHANGELOG entry (that will come later, once the first messaging system (SQS) is added)
> feat: ignore_message_queues configuration

- .tav.yml
- test/config.js
- test/instrumentation/modules/@elastic/elasticsearch.js
The ES client has dropped support for node v8.
Fixes: #2016
> test: skip testing @elastic/elasticsearch >= 7.12.0 with node 8

- lib/agent.js
- lib/config.js
This is a companion to https://github.com/elastic/apm-nodejs-http-client/pull/143 to add a logger to the apm client and a private `agent._getStats()` API for dev/debugging.
* * *
This is pre-support for a coming work to fix https://github.com/elastic/apm-nodejs-http-client/issues/136
I'm trying to separate out some changes to make that change more focused.
> pass a logger to the apmclient and private _getStats for debugging

- .ci/scripts/docker-test.sh
We detected an issue with Node.js Docker images <=10 when we try to close the `apm-nodejs-http-client` repository during the `npm install`, we see a fatal error `unable to look up current user in the passwd file: no such user`. This errors is related to the Git version in those Docker images that is older than 2.7, the workaround is to set the user and email in the git configuration in case the user is not in the `/etc/passwd`.
> fix: workaround to a git <2.7 issue

- lib/tracecontext/tracestate.js
- test/tracecontext/tracestate.js
Part of #2023
This fixes a small bug in the `TraceState` class where
1. Creating an invalid tracestate
2. and then attempting to access a value in that tracestate via `getValue`
resulted in a crash.  This came up during the sample_rate work.
This PR provides a fix, and tests for that fix. The tests fail before the fix but succeed after.
> fix: fixes crash when accessing values from invalid tracestates

- DEVELOPMENT.md
I'm proposing a DEVELOPMENT.md (using a file name I've seen in a couple other elastic repos) document for informal dev tips. More formal content should end up in CONTRIBUTING.md, README.md, TESTING.md or the user "docs/...".
Rendered: https://github.com/elastic/apm-agent-nodejs/blob/trentm/devnotes/DEVELOPMENT.md
Thoughts?
> docs: start an informal doc for dev tips

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- docs/configuration.asciidoc
- docs/performance-tuning.asciidoc
- index.d.ts
- lib/config.js
- package.json
- test/_apm_server.js
- test/agent.js
- test/config.js
- test/integration/api-schema/basic.js
- test/integration/api-schema/capture-error-log-stack-traces.js
- test/integration/api-schema/capture-span-stack-traces.js
- test/integration/api-schema/source-lines-error-frames.js
- test/integration/api-schema/source-lines-span-frames.js
Update to http client which fixes/improves comms with apm-server.
> fix: blocking behaviour under load

- lib/filters/sanitize-field-names.js
This was added in commit 4cbe2f9e85f3d23808ddbec4e2833205c4550ae8,
likely in early revs of its PR, but never used.
> chore: drop unused createFilter function

- .ci/Jenkinsfile
- .ci/docker/docker-compose-node-edge-test.yml
- .ci/docker/docker-compose-node-test.yml
- .ci/scripts/test.sh
- test/script/docker/run_tests.sh
Invert logic of the selection of an appropriate docker-compose config
for *TAV* testing in docker, to default to *not setting up any extra
services* for a test run, unless specifically required for that TAV
module. Before this, TAV tests for `@hapi/hapi`, `@koa/router`, and
`@elastic/elasticsearch` would setup *all* services, which is overkill.
Also document .ci/scripts/test.sh because it subtlely does a few
slightly different things. Also rename the TAV_MODULE var name to be
more accurate.
Also bumps to using node 14 for the windows build which fixes #2061
* * *
Looking at the log for https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/864/pipeline/1037
which is step "TAV Test / Node.js-10-@hapi/hapi" of the TAV tests:
``` …
```
> ci: CI docker TAV tests are unnecessarily setting up all services for some modules

- .github/workflows/lint.yml
- .github/workflows/test.yml
The .ci/Jenkinsfile already has a similar skip:
```
// Skip all the stages except docs for PR's with asciidoc or md changes only
env.ONLY_DOCS = isGitRegionMatch(patterns: [ '.*\\.(asciidoc|md)' ], shouldMatchAll: true)
```
> chore: don't run GH Actions CI lint and tests for .md and doc file changes

- lib/parsers.js
There is a local 'http-headers' module (in lib/filters) that does
something different.
Possibly a neurotic refactor. When I was walking through code for https://github.com/elastic/apm-agent-nodejs/pull/2072 there were two "things" matching "http-headers" in the agent code that do different things.
> refactor: clarify func name

- CHANGELOG.asciidoc
- index.d.ts
- test/types/index.ts
They had been added to GenericSpan, but forgotten on class Agent.
Fixes: #2076
> fix: add 'stringify' arg to TypeScript typings for setLabel and addLabels

- CHANGELOG.asciidoc
- lib/instrumentation/http-shared.js
The w3c traceparent header is standardized and widely used enough now in Elastic tools that we should prefer it over the proprietary 'elastic-apm-traceparent' header.
See similar for [Java](https://github.com/elastic/apm-agent-java/pull/1821), [.NET](https://github.com/elastic/apm-agent-dotnet/pull/1302).
> feat: prefer 'traceparent' header over 'elastic-apm-traceparent' header

- .ci/Jenkinsfile
> test: correct the sense of ELASTIC_APM_ASYNC_HOOKS envvar from disableAsyncHooks jenkins step option

- .ci/.jenkins_nightly_nodejs.yml
- .ci/.jenkins_rc_nodejs.yml
- .ci/Jenkinsfile
- .ci/scripts/test.sh
"Edge" builds or "Edge Test" is this repo's name for running the Agent test suite against pre-release (RC or nightly) builds of Node.js.
1. node.js "nightly" builds: It is only useful testing those if there are no current releases for that major branch. For example, a nightly build of "v16.0.0-nightly20210420a0261d231c" (the current latest v16 nightly build) is pointless because there are v16.x node.js releases after that that we already test.  At time of writing only v17 has nightly builds and no releases. Once there is a v17.0.0 release my interpretation of https://nodejs.org/download/nightly/ is that there will be no more v17.x nightly builds -- or at least no v17 nightly builds of a commit past the latest v17 release commit sha. (I'd welcome an authoritative source for that. I …
> test: limit testing of 'edge' node builds (node.js nightly and RC builds) to useful versions

- DEVELOPMENT.md
- test/instrumentation/modules/mongodb-core.js
With mongodb-core@1.x there are some addition spans that can be
captured. This makes the test not blow up in those cases.
Fixes: #1337
> test: make this test robust for additional capture spans possible with mongodb-core@1.x

- .ci/.jenkins_tav.yml
- .tav.yml
- apollo-server-express: Only test the latest MAJOR.MINOR.x patch
releases, reducing from 84 down to 25 releases (currently).
- Aside: This also *adds* testing of apollo-server-express against
graphql@15 (released since this test matrix was updated.
Fixes #2084
> test: faster TAV runs by reducing the test matrix

- test/integration/api-schema/apm-server-schema/metricset.json
APM agent json schema automatic sync
*Changeset*
* https://github.com/elastic/apm-server/commit/07444287f Add support for histograms to metrics intake (https://github.com/elastic/apm-server/pull/5360)
> synchronize schema spec

- docs/configuration.asciidoc
- index.d.ts
After fixing up a missing type in another PR, I noticed there were a number of configuration values used by `lib/config.js` and documented by `docs/configuration.asciidoc` that were missing from our `index.d.ts` file.   This PR adds them in.
> fix: missing typescript defs

- CHANGELOG.asciidoc
- package.json
The root cause was https://github.com/facebook/react/pull/18708
temporarily doing `Error.prepareStackTrace = undefined` to get a stack
string. This wasn't handled correctly by error-callsites
(watson/error-callsites#3).
Fixes: #1980
> fix: 'TypeError: lastPrepareStackTrace' crash when used with React v17+

- package.json
https://github.com/elastic/ecs-logging-nodejs/issues/79 was a circular
require issue that could happen between 'elastic-apm-node' and
'@elastic/ecs-pino-format' (versions before 1.1.2) -- if user code
directly used both modules. This bumps the version of the latter to help
avoid that situation in user apps.
Refs: #2110
> fix: avoid possible circular require bug between this and ecs-pino-format

- CHANGELOG.asciidoc
- lib/instrumentation/modules/aws-sdk/sqs.js
- test/instrumentation/modules/aws-sdk/sqs.js
Fixes #2113
This PR modifies adds an additional guard clause to the SQS instrumentation that checks to see if a span was actually started or not.  It also removed the old `currentTransaction` guard clause from `shouldIgnoreRequest` and modifies the unit test accordingly.
> fix: SQS crashing error with no active transaction

- CHANGELOG.asciidoc
Minor tweaks to the changelog item for having added `sanitize_field_names`.
Related: I've also updated the relevant cells in https://docs.google.com/spreadsheets/d/1JJjZotapacA3FkHc2sv_0wiChILi3uKnkwLTjtBmxwU/edit#gid=0 for this.
> docs: improve changelog note on sanitize_field_names

- .ci/docker/docker-compose.yml
- .github/workflows/test.yml
- test/docker-compose.yml
Very recently MS removed the 'microsoft/mssql-server-linux' images from
Docker Hub in favour of https://hub.docker.com/_/microsoft-mssql-server
This was breaking tests.
> tests: fix mssql server Docker registry

- .ci/docker/docker-compose-localstack.yml
> tests: fix docker-compose setup that broke aws-sdk TAV tests in CI

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- index.d.ts
- lib/agent.js
- lib/config.js
- lib/errors.js
- lib/instrumentation/index.js
- lib/instrumentation/transaction.js
- lib/metrics/index.js
- lib/noop-transport.js
- package.json
- test/config.js
- test/disable-send.test.js
Env var is ELASTIC_APM_DISABLE_SEND. Default is false. This feature is
useful to use the APM agent for async context tracking, distributed
tracing context propagation, and/or log enrichment with trace.id. When
disableSend=true, attempts are made to limit unnecessary processing
(like calculating metrics, encoding stacktraces, etc.).
This is the same as the "disable_send" option in some of the other APM agents.
Fixes: #2101
> feat: disableSend boolean config option to work, but not communicate with APM server

- .ci/Jenkinsfile
Ensure a unique CI Worker is allocated.
There is a known issue with the provisioner that reuses workers for some reason (this is not related to Jenkins itself but the external provisioner). That could somehow be related to the issues when tearing down the tests (see https://github.com/elastic/apm-agent-nodejs/pull/2142)
https://github.com/elastic/apm-pipeline-library/blob/master/vars/withNode.txt
> ci: use withNode step to allocate unique workers

- .tav.yml
- docs/supported-technologies.asciidoc
The `.tav.yml` didn't have _all_ it's tests renamed.  Specifically
```
test/instrumentation/modules/express/set-framework.js
test/instrumentation/modules/fastify/async-await.js
test/instrumentation/modules/fastify/set-framework.js
test/instrumentation/modules/hapi/basic-legacy-path.js
test/instrumentation/modules/hapi/basic.js
test/instrumentation/modules/hapi/set-framework-hapi.js
test/instrumentation/modules/hapi/set-framework-hapihapi.js
test/instrumentation/modules/restify/set-framework.js
test/instrumentation/modules/koa-router/old-name,js
test/instrumentation/modules/koa-router/new-name.js
```
were still hanging around.  When the TAV runner tried to run these commands, it failed.
This PR renames these files to `.test.js`.
> fix: rename to .test.js for all tests in TAV

- .ci/Jenkinsfile
There was a typo in the named parameters for `WithNode` where the forcing of a workspace was never initialized
> chore: [ci] Fix parameter to correctly call forceWorkspace

- CHANGELOG.asciidoc
- lib/instrumentation/http-shared.js
- lib/instrumentation/modules/http2.js
- test/instrumentation/modules/@elastic/elasticsearch.test.js
- test/instrumentation/modules/elasticsearch.test.js
- test/instrumentation/modules/http/disabling.test.js
- test/instrumentation/modules/http/outgoing.test.js
- test/instrumentation/modules/http/request.test.js
- test/instrumentation/modules/http2.test.js
Part of https://github.com/elastic/apm-agent-nodejs/issues/2067
This PR changes the behavior of naming outgoing HTTP spans by dropping the path portion of the URL. This is done to comply with the spec and reduce the cardinality of outgoing HTTP span names: https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-http.md#http-client-spans
> fix: span name should comply with spec

- CHANGELOG.asciidoc
- lib/metrics/reporter.js
- test/metrics/breakdown.test.js
- test/metrics/index.test.js
- test/metrics/stale.test.js
> fix: remove zero count metrics from registry 

- .ci/jobs/apm-agent-nodejs-mbp.yml
This changes to be an allowlist rather than a denylist. It means that
feature branches that aren't yet PRs will not have CI run on them. This
also effectively drops the 2.x branch because that version is now EOL.
In https://github.com/elastic/observability-robots/discussions/689 and https://github.com/elastic/observability-robots/issues/683 it was raised that we should exclude unsupported branches from CI builds. For the node.js agent: [2.x is EOL as of 2021-03-19](https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrading.html#end-of-life-dates).
As well, before this change we include feature branches that need not be built:
most of those branch jobs are races against creating a PR job for that feature branch.
> ci: limit CI builds to explicit branches: master, PRs, and 3.x

- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/mongodb.js
- package.json
- test/config.test.js
- test/instrumentation/modules/mongodb.test.js
Fixes: https://github.com/elastic/apm-agent-nodejs/issues/2170
This PR adds back support for the recently release MongoDB 4.0+, and adds a `<5` constraint to the version check on the MongoDB instrumentation module. TAV test constraint remains at `>3.3` in order to catch problems with a theoretical 5.0 in the future.
> fix: adds supports for MongoDB 4.0+

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/apollo-server-core.js
- package.json
- test/config.test.js
- test/instrumentation/modules/apollo-server-express.test.js
This PR adds support for the 3.x branch of `apollo-server-express`, and adjusts our tests to ensure apollo server starts correctly. 
Prior to this change, tests were failing with the message
```
TAP version 13
/Users/astorm/Documents/github/elastic/apm-agent-nodejs/node_modules/apollo-server-core/dist/ApolloServer.js:273
throw new Error('You must `await server.start()` before calling `server.' +
^
Error: You must `await server.start()` before calling `server.applyMiddleware()`            
```
This PR adjusts the tests to start the server as expected in 3.x.
This PR also adjusts the `semver` constraint to allow version 3.x.
Finally, this PR adjusts the TAV tests to include an entry for apollo server 3.x using a peer dependency of `graphql@^15.0.0` and nodes >12.  These versions are based …
> fix: get apollo-server-express working @3.x

- lib/instrumentation/modules/mongodb.js
- package.json
- test/instrumentation/modules/mongodb.test.js
In mongodb@4.1.0 (https://jira.mongodb.org/browse/NODE-3513) the
monitorCommands option was reverted to defaulting to false. To
instrument we ensure it is true.
Fixes: #2177
> fix: ensure instrumentation of mongodb >=4.1.0 works

- lib/lambda.js
- test/lambda/promises.test.js
Part of https://github.com/elastic/apm-agent-nodejs/issues/2156
This PR ensures that if the Lambda function is responding to an API Gateway request (or other request that includes a `tracestate` header) that its transaction will start using that tracestate.  This is needed because our existing lambda instrumentation was written before `tracestate` was a thing.
> feat: add tracestate header when starting lambda transaction

- lib/agent.js
- lib/cloud-metadata/index.js
- lib/cloud-metadata/lambda.js
- lib/config.js
- lib/lambda.js
- test/cloud-metadata/index.test.js
- test/lambda/callbacks.test.js
- test/lambda/cloud-metadata.test.js
- test/lambda/context.test.js
- test/lambda/promises.test.js
Part of: https://github.com/elastic/apm-agent-nodejs/issues/2156
This PR implements a cloud metadata fetcher for AWS Lambda, and collects the three known cloud metadata fields for Lambda.  [Per the spec](https://github.com/elastic/apm/pull/470/files#diff-f2c63c07259b18f0e99842294455cf6f50fd4b1f415fafd1a2946a56f6086c25R35), when in an AWS Lambda environment the normal cloud metadata HTTP-service checks should be suspended, and we should attempt to collect as much of the cloud metadata from the environment without external service requests. 
This PR also does some small bits of module refactoring to facilitate current/future work
- `lib/lamba.js` now exports multiple functions, to facilitate testing of the new  `isLambdaExecutionEnviornment`
- A `getBaseClientConfig` has been introduced in …
> feat: cloud metadata for lambda

- CHANGELOG.asciidoc
- lib/instrumentation/http-shared.js
- package.json
- test/_mock_apm_server.js
- test/do-not-trace-self.test.js
- test/fixtures/do-not-trace-self.js
This fixes a couple of older issues and also ensures these internal
requests do not add noise to internal debug logging for instrumentation
async context tracking.
Fixes: #1168
Fixes: #1136
> fix: ensure the APM agent's own requests to APM server are not traced

- test/benchmarks/scripts/run-benchmarks.sh
- test/benchmarks/utils/apm-server.js
This is to avoid possible port conflict if there is a real APM server
already running on a shared machine.
Fixes: #2131
> ci: avoid port 8200 for mock apm-server for benchmark runs

- test/config.test.js
No functional change.
This is work that came out of earlier work on https://github.com/elastic/apm-agent-nodejs/pull/2193
The `longFieldMaxLength` config var for that PR was *originally* a "strict bytes" type. "Strict bytes" here is a config var type similar to the existing "bytes" type, but per https://github.com/elastic/apm/blob/master/specs/agents/configuration.md#durationsize-config-legacy-considerations all new "bytes" config vars must be *strictly* a string with the units. Our current "bytes" vars are loose (don't require a suffix like "b" or "kb", and allow an integer instead of a string) here, so a separate type on "config.js" will be necessary if/when we add one.
If/when we add a "strict" bytes/size type, then we'll need this refactoring of config.test.js -- or something better …
> tests: refactor handling of config var type in config.test.js

- CHANGELOG.asciidoc
- lib/instrumentation/named-array.js
- test/agent.test.js
There was a bug in the Instrumentation class's data structure for added
patches where removePatch(name, somethingBogus) would "find" that
handler at index -1 and remove the last handler.
> fix: apm.removePatch(name, somethingNotRegistered) would remove last handler

- lib/metrics/reporter.js
- test/_capturing_transport.js
- test/metrics/breakdown.test.js
This refactors breakdown.test.js to not need a `resetAgent(...)` that knows so much about Agent internals. Now that we have a usable `agent.destroy()`, use that and create a new Agent for each test case. 
This also moves away from the test/_mock_http_client.js testing style of waiting for an expected number of sent events to decide when to end a test case. This style is brittle when there is a test failure: either hanging waiting for an event that isn't coming, or crashing with `throw new Error('too many writes')`.
> tests: refactor breakdown metrics tests to not override Agent internals

- CHANGELOG.asciidoc
- docs/setup.asciidoc
- index.d.ts
- package.json
- types/aws-lambda.d.ts
- types/connect.d.ts
This ensures that TypeScript users do not need to install separate
'@types/...' packages to build -- with the lone exception of
'@types/node'.
We avoid imports by instead inlining the required types. This is a
trade-off. We don't want '@types/...' in "dependencies" because they
can be big and aren't really "official" types for those packages.
Fixes: #2331
> fix: avoid import of any '@types/...' packages in types file

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- lib/config.js
- lib/instrumentation/modules/aws-sdk/sqs.js
- lib/metrics/index.js
- test/config.test.js
Also guard against:
- `metricsInterval:null` resulting in metrics being enabled without any
log message, which is perhaps slightly surprising.
- `metricsInterval:-1s` (any negative value) resulting in metrics being
collected *as fast as possible* via
`setInterval(collectAllTheMetrics, -1000)`.
An invalid value for this config var, and the other "POSTIVE_TIME_OPTS",
will result in (a) a log.warning and (b) falling back to the default
value.
A slight semantic change on the internal Metrics object means that the
`getOrCreate...()` metric functions now return undefined when metrics
are disabled via `metricsInterval`. This doesn't affect any public API.
```js
// no-metrics-please.js
require('./').start({
serviceName: 'foo',
metricsInterval: '0s'
})
const http = require('http')
const hostname = …
```
> fix: ensure metrics collection is actually disabled with metricsInterval=0s

- index.d.ts
- test/types/index.ts
> fix: SpanOptions type should include 'startTime'

- CHANGELOG.asciidoc
- lib/instrumentation/async-hooks.js
- lib/instrumentation/generic-span.js
- lib/instrumentation/index.js
- lib/instrumentation/modules/aws-sdk/dynamodb.js
- lib/instrumentation/modules/aws-sdk/s3.js
- lib/instrumentation/modules/aws-sdk/sns.js
- lib/instrumentation/modules/aws-sdk/sqs.js
- lib/instrumentation/span.js
- lib/instrumentation/transaction.js
- test/instrumentation/async-hooks.test.js
- test/instrumentation/modules/@elastic/elasticsearch.test.js
- test/instrumentation/modules/aws-sdk/sns.test.js
- test/instrumentation/span.test.js
- test/instrumentation/transaction.test.js
Current `span.sync` is tracked via:
- the "before" async hook setting it false on the "active" span, and
- Instrumentation#bindFunction's wrapper setting it false, on the
fair assumption that all usages of bindFunction are for async
callbacks.
The former has issues when there are multiple active spans within a
single async task -- as is the case with Elasticsearch instrumentation
(issue #1996) and the aws-sdk instrumentations (which have manual
workarounds).
This changes to set sync=false if the executionAsyncId() at end-time
is different than at start-time. This works for whatever `asyncHooks`
config var value.
One change in behaviour is that the value of span.sync is only
guaranteed to be accurate after span.end() is called. Given that
span.sync isn't a public field, I believe this is …
> fix: more reliable span.sync determination, drop unused transaction.sync

- .ci/Jenkinsfile
- DEVELOPMENT.md
- TESTING.md
https://github.com/elastic/apm-agent-nodejs/pull/2342 simplified the GItHub commands, though there were some missing changes in the docs that should reflect the supported commands. `Jenkins run the ...` is deprecated in favour of the new `/test` and `^run....` commands.
Ensure the docs reflect those changes.
The new GitHub comment changes now provide those details, that were added in the apm-pipeline-library:
- https://github.com/elastic/apm-pipeline-library/blob/b057084212cbba2df8f3215d3bb00956ef1dcae4/src/co/elastic/NotificationManager.groovy#L479-L483
> ci: simplify GitHub commands

- CHANGELOG.asciidoc
- index.d.ts
- test/types/index.ts
Back in #1335 the "ids" property was added to Span and Transaction, but
it wasn't added to the TypeScript types.
/cc @mshustov
> types: add Span.ids and Transaction.ids to types

- .github/community-label.yml
- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
Add `triage` and `community` labels for new issues and PRs that originate from creators outside the apm team.
> Adapt GitHub actions automation for community issues and PRs

- CHANGELOG.asciidoc
- docs/metrics.asciidoc
- lib/instrumentation/transaction.js
- test/metrics/breakdown.test.js
None of `transaction.breakdown.count`, `transaction.duration.sum.us`,
`transaction.duration.count` are or were used by APM UI.
Closes: #2370
> chore: stop recording transaction breakdown metrics

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- index.d.ts
- lib/agent.js
- lib/config.js
- lib/instrumentation/index.js
- lib/instrumentation/transaction.js
- lib/metrics/index.js
- lib/noop-transport.js
- test/config.test.js
- test/context-propagation-only.test.js
- test/disable-send.test.js
Implement contextPropagationOnly per spec (it does what disableSend
did before this change). Change disableSend to just disable comms
with APM server, but otherwise *not* attempt to reduce work.
https://github.com/elastic/apm/blob/master/specs/agents/transport.md#context_propagation_only-configuration
Closes: #2393
> feat: impl contextPropagationOnly config var; change disableSend behaviour

- docs/configuration.asciidoc
The behavior of the APM agent's default 'uncaughtException' handler
can be confusing.
Refs: #2359
> docs: clarify side-effects of 'captureExceptions: true'

- lib/lambda.js
- test/lambda/_util.js
- test/lambda/callbacks.test.js
- test/lambda/context.test.js
- test/lambda/promises.test.js
Closes: #2417
Skipping changelog entry, because if this is in the same release as the recent Lambda transaction data work, then it falls under the same changelog entry.
> fix: remove unspec'd custom context for lambda transactions

- lib/agent.js
- lib/config.js
- test/agent.test.js
This restores the internal `apm._conf` as a crutch for
apm.startTransaction() -- and possibly other Agent API methods -- to
function without crashing before `apm.start()` is called. `apm._conf`
is set to a config object holding the agent's defaults.
Fixes: #2425
> fix: apm.startTransaction() crash if agent not yet started

- docs/lambda.asciidoc
- docs/set-up.asciidoc
- docs/supported-technologies.asciidoc
Updates Lambda docs to undeprecate Lambda and provide information on installing with [the Lambda extension](https://github.com/elastic/apm-aws-lambda/)
> docs: new lambda docs for Node.js agent

- CHANGELOG.asciidoc
- lib/instrumentation/http-shared.js
To be nice for servers that balk at empty header values.
Fixes: #2405
> fix: do not set 'tracestate' header to the empty string

- test/instrumentation/modules/redis.test.js
Regarding "correctness", the previous `findObjInArray` usage was finding only the first matching span name in:
```js
var groups = [
'FLUSHALL',
'SET',
'SET',
'HSET',
'HSET',
'HKEYS'
]
```
So for the *two* generated spans with name="SET", only the first of those was found and tested. It was tested twice.
> refactor: improve test case messages and correctness in redis test

- lib/config.js
- test/config.test.js
When creating the User-Agent, there is no need to escape chars in
serviceName, because it is already limited to legal User-Agent chars.
(From some private chat on escaping for User-Agent: https://elastic.slack.com/archives/C9A6ANR5Y/p1637163729166800)
> fix: no need to escape chars in serviceName for User-Agent

- test/config.test.js
- test/instrumentation/modules/fastify/set-framework.test.js
- test/instrumentation/modules/restify/basic.test.js
- test/instrumentation/modules/restify/set-framework.test.js
- test/sanitize-field-names/restify.test.js
Restify currently does not work with the latest v18.0.0 nightly.
See https://github.com/restify/node-restify/issues/1888
"Edge" nightly tests recently started failing on this. E.g.:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1178/pipeline/6508
```
[2021-11-15T07:16:33.458Z] node_tests_1     | # disableInstrumentations
[2021-11-15T07:16:33.458Z] node_tests_1     | # individual modules -> @elastic/elasticsearch
[2021-11-15T07:16:43.490Z] node_tests_1     | /app/node_modules/restify/lib/request.js:848
[2021-11-15T07:16:43.490Z] node_tests_1     |     Request.prototype.closed = function closed() {
[2021-11-15T07:16:43.490Z] node_tests_1     |                              ^
[2021-11-15T07:16:43.490Z] node_tests_1     | …
```
> tests: fix failing restify tests with latest node v18.0.0 nightly

- lib/instrumentation/modules/redis.js
- test/instrumentation/modules/redis.test.js
Before this the error.parent_id was set to the transaction.id, rather
than span.id.
> fix: the error captured for an erroring redis span should be the span

- CHANGELOG.asciidoc
- examples/trace-mysql.js
- lib/instrumentation/modules/mysql.js
- test/instrumentation/modules/mysql/mysql.test.js
This fixes the 'mysql' instrumentation to not have the mysql span
context be active in user code. This ensures that user code cannot
create a child span of the mysql span, which would (a) be misleading
and (b) cause problems for coming exit span and compressed span work.
Refs: #2430
> fix: ensure run-context for mysql span does not spill into user code

- .ci/Jenkinsfile
- README.md
Fixes the github command for module, see https://github.com/elastic/apm-agent-nodejs/pull/2444#issuecomment-970935406
Remove travis references
> ci: support modules github comments

- .ci/jobs/apm-agent-nodejs-mbp.yml
- .ci/jobs/defaults.yml
This will avoid building the PRs when the target branch has changed, normally when the MBP index scan happens.
> [jjbb] add minor improvements

- .tav.yml
- examples/trace-handlebars.js
- examples/trace-pug.js
Jade was renamed to pug and hasn't had a release since 2015. Testing
114 releases of jade for every commit is unnecessary.
This also adds examples for the other two templating libs.
> tests: reduce the number of versions of jade being tested

- CHANGELOG.asciidoc
- lib/parsers.js
- test/instrumentation/modules/http2.test.js
> fix: crash in Transaction serialization if req.socket is null

- CHANGELOG.asciidoc
- examples/trace-memcached.js
- lib/instrumentation/modules/memcached.js
- test/instrumentation/modules/memcached.test.js
This ensures that a created 'memcached' span is not the currentSpan
in user code after the call.
Refs: #2430
> fix: ensure correct run-context for 'memcached' instrumentation

- CHANGELOG.asciidoc
- examples/trace-ws.js
- lib/instrumentation/modules/ws.js
- test/instrumentation/modules/ws.test.js
> fix: ensure correct run context for 'ws' instrumentation

- docs/log-correlation.asciidoc
The docs PR to upgrade to 7.16 (https://github.com/elastic/docs/pull/2299) is failing due to a broken link in the apm-agent-nodejs repo. This link exists in `master`, `3.x`, and `2.x`:
```
14:29:51 INFO:build_docs:Bad cross-document links:
14:29:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/2.x/log-correlation.html contains broken links to:
14:29:51 INFO:build_docs:   - en/apm/guide/7.16/observability-integrations.html#_ingest_your_logs_into_elasticsearch
14:29:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/nodejs/3.x/log-correlation.html contains broken links to:
14:29:51 INFO:build_docs:   - en/apm/guide/7.16/observability-integrations.html#_ingest_your_logs_into_elasticsearch
14:29:51 INFO:build_docs: …
```
> docs: Fix broken link to 7.16 docs

- docs/index.asciidoc
Pins APM agent Node.js version 2.x to stack version 7.15 to avoid future broken links.
> docs: pin 2.x to 7.15

- docs/configuration.asciidoc
- docs/metrics.asciidoc
- lib/config.js
Also add some doc clarifications for the `breakdownMetrics` config var.
Fixes: #2502
> perf, docs: avoid calculating breakdown metrics if not sending

- .tav.yml
- CHANGELOG.asciidoc
- lib/instrumentation/modules/aws-sdk/dynamodb.js
- test/instrumentation/modules/aws-sdk/dynamodb.test.js
This also adds a couple aws-sdk-related tests to the TAV=aws-sdk tests.
Refs: #2430
> fix: run context handling for aws-sdk DynamoDB instrumentation

- .tav.yml
got@12 went pure ESM, so we cannot test it with the current test file.
However, since got@11, got doesn't use mimic-response, which was the
point of testing got. This change drops testing with got >=11.
Recent TAV test failure with node v10: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/31/pipeline/1363 
```
[2021-12-13T06:54:13.943Z] node_tests_1  | > tav --quiet
[2021-12-13T06:54:13.944Z] node_tests_1  | 
[2021-12-13T06:54:14.514Z] node_tests_1  | -- required packages ["got@12.0.0"]
[2021-12-13T06:54:14.514Z] node_tests_1  | -- installing ["got@12.0.0"]
[2021-12-13T06:54:24.528Z] node_tests_1  | -- running test "node test/instrumentation/modules/http/github-423.test.js" with got
[2021-12-13T06:54:24.528Z] node_tests_1  | …
```
> tests: fix TAV=got test failures with got@12

- test/instrumentation/modules/http/fixtures/make-http-request.js
- test/instrumentation/modules/http/http-run-context.test.js
This fixes a failing test due to a recent change in 'http://httpstat.us'
to no longer support http -- other than a redirect to https.
This change to `httpstat.us` https://github.com/Readify/httpstatus/commit/c23fb576fe17afbee2035a0b1cd4c735dc1e3cc9#diff-7aab2c6ec5099ca78c72cbed4417e12ea493ba35a898fbbf82faf930a49fd089R33
made it so that an *HTTP* request (rather than HTTPS) now just redirects to HTTPS rather than returning a response. This commit was made Dec 15th, and auto-deploys.
```
% curl -i http://httpstat.us/200
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=UTF-8
Location: https://httpstat.us/200
Date: Fri, 17 Dec 2021 18:14:22 GMT
Content-Length: 0
```
The test/instrumentation/modules/http/http-run-context.test.js test was using `http://httpstat.us/200` as a test …
> tests: use www.google.com rather than httpstat.us for an HTTP test

- .ci/packer_cache.sh
No more tagging `apm-agent-nodejs` specific docker images to the official docker `node:version` images.
Since `node:X` can be consumed by different pipelines, we cannot use the retagging as long as the CI workers are not specific per project but per CI controller.
OTOH, https://github.com/elastic/apm-agent-nodejs/pull/1383 simplified the docker images and [`.ci/docker/node-container/Dockerfile`](https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/docker/node-container/Dockerfile) is pretty much similar to the `node:X` version with the extra layer for the `node version` command.
Relates https://github.com/elastic/ecs-logging-nodejs/issues/112
> ci: avoid retagging official node images

- CHANGELOG.asciidoc
- examples/trace-graphql.js
- lib/instrumentation/modules/graphql.js
- test/instrumentation/modules/graphql.test.js
> fix: ensure correct run context for 'graphql' instrumentation

- test/metrics/index.test.js
Recent node v18 nightly builds changed the behaviour of os.freemem()
on Linux to report "MemAvailable" from /proc/meminfo rather than
"MemFree". This broke our tests.
The nightly "edge" tests started failing ~6-7 days ago with:
```
running test: cd . && node --unhandled-rejections=strict test/metrics/index.test.js > test_output/test-metrics-index.test.js.tap 2&>1
...
[2022-01-14T19:31:11.076Z] node_tests_1     | # system.memory.actual.free
[2022-01-14T19:31:11.076Z] node_tests_1     | ok 11 is present
[2022-01-14T19:31:11.076Z] node_tests_1     | ok 12 is a number
[2022-01-14T19:31:11.076Z] node_tests_1     | ok 13 is finite (was: 10925056000)
[2022-01-14T19:31:11.076Z] node_tests_1     | not ok 14 is larger than os.freemem() (value: 10925056000, free: 10925056000) …
```
> tests: fix test failure due to os.freemem() behaviour change in node v18

- docs/configuration.asciidoc
- docs/troubleshooting.asciidoc
- docs/upgrading.asciidoc
Refactor the troubleshooting doc (https://www.elastic.co/guide/en/apm/agent/nodejs/current/troubleshooting.html) somewhat inspired by the ordering/organization of the Java agent's troubleshooting doc (https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html).
> docs: refactor troubleshooting docs

- test/metrics/index.test.js
The update to libuv 1.43.0 changed the behaviour of os.freemem() on
Linux to report "MemAvailable" from /proc/meminfo rather than "MemFree".
Refs: #2530
(Most test runs for all PRs will fail when testing against node v17 until this is merged in.)
> tests: fix test failure due to os.freemem() behaviour change in node v17.4.0

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- lib/config.js
- test/config.test.js
This updates the default `serviceName` value per APM spec -- allowing
APM UI to recognize when a service name wasn't configured for a given
service.
Closes: #2491
> feat: align on 'unknown-{service.agent.name}-service' default service_name

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- docs/configuration.asciidoc
- docs/intro.asciidoc
- docs/log-correlation.asciidoc
- docs/opentracing.asciidoc
- docs/supported-technologies.asciidoc
- docs/troubleshooting.asciidoc
- docs/upgrading.asciidoc
Links updated as per https://github.com/elastic/observability-docs/issues/1385. The old links will break when 7.17 releases. This PR and all backports must be merged before the 7.17 release. Thanks!
> docs: update broken links for apm-guide-ref #1385

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- docs/configuration.asciidoc
- docs/intro.asciidoc
- docs/log-correlation.asciidoc
- docs/opentracing.asciidoc
- docs/supported-technologies.asciidoc
Backports the relevant changes in https://github.com/elastic/apm-agent-nodejs/pull/2541 to 3.x.
> [3.x] Doc link fixes

- CHANGELOG.asciidoc
- lib/config.js
- lib/instrumentation/index.js
- lib/noop-transport.js
- package.json
- test/_capturing_transport.js
- test/_mock_apm_server.js
- test/_mock_http_client.js
- test/_mock_http_client_states.js
- test/agent.test.js
- test/central-config-enabled.test.js
- test/config.test.js
- test/fixtures/do-not-trace-self.js
- test/instrumentation/index.test.js
- test/integration/allow-invalid-cert.test.js
- test/integration/api-schema/basic.test.js
- test/integration/api-schema/capture-error-log-stack-traces.test.js
- test/integration/api-schema/capture-span-stack-traces.test.js
- test/integration/api-schema/source-lines-error-frames.test.js
- test/integration/api-schema/source-lines-span-frames.test.js
- test/integration/no-sampling.test.js
- test/integration/server-url-path.test.js
- test/integration/skip-internal-http-spans.test.js
- test/integration/socket-close.test.js
- test/integration/verify-server-ca-cert.test.js
- test/outcome.test.js
- test/transaction-sampling.test.js
This updates to an elastic-apm-http-client that calls the APM Server
Information API on creation to get the APM Server version.
Closes: #2455
> feat: Drop unsampled transactions when connected to APM Server 8.0+

- CHANGELOG.asciidoc
- lib/instrumentation/modules/mongodb-core.js
- test/instrumentation/modules/mongodb-core.test.js
> fix: ensure correct run context for 'mongodb-core' instrumentation

- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- examples/trace-cassandra-driver.js
- lib/instrumentation/modules/cassandra-driver.js
- test/instrumentation/modules/cassandra-driver/index.test.js
> fix: ensure correct run context for 'cassandra-driver' instrumentation

- .ci/.jenkins_tav.yml
- .ci/scripts/test.sh
- .tav.yml
- CHANGELOG.asciidoc
- examples/trace-elasticsearch7.js
- examples/trace-elasticsearch8.js
- lib/instrumentation/elasticsearch-shared.js
- lib/instrumentation/modules/@elastic/elasticsearch.js
- lib/instrumentation/modules/elasticsearch.js
- package.json
- test/instrumentation/modules/@elastic/elasticsearch.test.js
- test/instrumentation/modules/elasticsearch.test.js
This is a re-write of the @elastic/elasticsearch instrumentation that
stops using the ES client observability events
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/observability.html
and switches to patching Transport#request() instead. This is necessary
to be able to bind that `request()` invocation to the RunContext for the
Span we've created; without using `apm.startSpan(...)`, which bleeds the
RunContext out to user code. (Patching Transport#request() is what the
legacy 'elasticsearch' instrumentation is also doing.)
Refs: #2430
> fix: ensure correct run context for '@elastic/elasticsearch' instrumentation

- CHANGELOG.asciidoc
- lib/instrumentation/modules/elasticsearch.js
- test/instrumentation/modules/elasticsearch.test.js
> fix: ensure correct run context for 'elasticsearch' (legacy) instrumentation

- .tav.yml
- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- docs/transaction-api.asciidoc
- index.d.ts
- lib/agent.js
- lib/instrumentation/http-shared.js
- lib/instrumentation/index.js
- lib/instrumentation/modules/aws-sdk/s3.js
- lib/instrumentation/span.js
- lib/instrumentation/transaction.js
- test/instrumentation/modules/aws-sdk/s3.test.js
- test/types/index.ts
Per https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans.md#exit-spans
the result is that HTTP child spans of S3 spans are no longer captured.
Closes: #2125
There is a boolean `exitSpan` option to the `startSpan()` APIs now, which we'll eventually use in our instrumentations. For now I've just added it to the `s3` instrumentation to get a feel. When creating a new span, if its parent is an exitSpan then the span won't be created.
I manually tested that context-propagation still works, but don't have a test case for that, because it is a pain in the S3 tests. I plan to add tests for context-propagation still working in https://github.com/elastic/apm-agent-nodejs/issues/2000 (because I already have a MockES in tests that I can easily use to test the `traceparent` et al …
> feat: introduce "exit spans" and mark S3 spans as exit spans

- test/fixtures/json-specs/span_types.json
APM agent specs automatic sync
*Changeset*
* https://github.com/elastic/apm/commit/b3f5827 Add ldap to external subtypes (https://github.com/elastic/apm/pull/588)
> test: synchronizing json spec

- CHANGELOG.asciidoc
- lib/instrumentation/modules/@elastic/elasticsearch.js
- lib/instrumentation/modules/elasticsearch.js
- lib/instrumentation/transaction.js
- package.json
- test/instrumentation/modules/@elastic/_mock_es.js
- test/instrumentation/modules/@elastic/elasticsearch.test.js
- test/instrumentation/modules/elasticsearch.test.js
Elasticsearch (ES) client spans are no marked as exit spans, so their HTTP
child spans are now no longer generated per spec:
https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans.md#exit-spans
Some HTTP context has been added to ES spans:
- span.context.http.status_code
- span.context.http.response.encoded_body_size
Closes: #2000
Closes: #2484
```
// - When using the non-default `asyncHooks=false` option with
//   @elastic/elasticsearch >=8 instrumentation, the diagnostic events do not
//   have the async run context of the current span. There are two impacts:
//   1. Elasticsearch tracing spans will not have additional "http" context
//      about the underlying HTTP request.
//   2. Users cannot access `apm.currentSpan` inside a diagnostic event handler.
```
I am currently …
> feat: mark Elasticsearch spans as exit spans; HTTP child spans are now elided

- lib/instrumentation/span.js
- test/agent.test.js
This fixes a bug recently introduced in commit 520a90113a5 where
`apm.createSpan()` with no args would result in a span with span.name
set to a SpanOptions value (and the options would not be applied).
commit 520a90113a56e6df0485b16ba067934dd243a33b (#2552) introduced a subtle
bug with `apm.createSpan()` -- specifically when called with no args. In this
case we expect a Span with the default name 'unnamed'. Instead what we get
is a Span with `name` set to a Span *options* object, which when serialized
(I'm shocked it got this far), results in badness:
```
{
"span": {
"name": {
"childOf": {
"_timer": null,
"_context": {
"traceparent": {
"recorded": true,
"version": "00",
"traceId": "5ea066a3c66fa7bfe12f727e49588dc1",
"id": "f8177cad6679a3d2",
"flags": "01"
},
"tracestate": {
"buffer": {}, …
```
> fix: `apm.createSpan()` with no args would create bogus span.name

- test/benchmarks/003-transaction-and-span-with-stack-trace.js
This benchmark is named 'transaction-and-span-with-stack-trace'
but since inception incorrectly has span stacktrace collection
*disabled*.
> perf: fix benchmark 003 to actually have span.stacktrace

- CHANGELOG.asciidoc
- lib/instrumentation/modules/@elastic/elasticsearch.js
tl;dr: Use a WeakMap as a WeakMap, not as an Object.
This leak was introduced in #2484.
Fixes: #2569
> fix: memory leak in @elastic/elasticsearch instrumentation

- CONTRIBUTING.md
I've found some references to update some travis files but travis is not anymore the existing CI.
> docs: remove travis reference

- .ci/docker/node-edge-container/Dockerfile
> test: use newer ubuntu for node.js edge tests for GLIBC_2.28 req

- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/hapi.js
- test/_is_hapi_incompat.js
- test/instrumentation/modules/hapi/shared.js
- test/sanitize-field-names/hapi.test.js
The body of incoming requests to an HTTP server using the Hapi
framework will be recorded in relevant APM transaction and error
objects depending on the `captureBody` config var setting.
Closes: #1905
> feat: add 'captureBody' support for Hapi

- docs/lambda.asciidoc
- docs/lambda/configure-lambda-widget.asciidoc
- docs/lambda/configure-lambda.asciidoc
- docs/lambda/nodejs-arn-replacement.asciidoc
- docs/scripts/build_docs.sh
This updates the Lambda getting started docs to use some shared widgets
from the apm-aws-lambda repo docs with the goal of making setup faster
and clearer.
Closes: #2615
This is related to and depends on https://github.com/elastic/apm-aws-lambda/pull/158
See also equivalent PRs for Python (https://github.com/elastic/apm-agent-python/pull/1511) and Java (https://github.com/elastic/apm-agent-java/pull/2556).
Getting this to build locally to sanity test it is a bit of a chore:
```
mkdir lambdocs
cd lambdocs
export LAMBDOCS=`pwd`
git clone git@github.com:elastic/apm-aws-lambda.git
(cd apm-aws-lambda; git checkout 8.1)
git clone git@github.com:elastic/docs.git
git clone git@github.com:elastic/apm-agent-nodejs.git
cd apm-agent-node
git checkout trentm/improve-lambda-docs …
```
> Improved getting started guide for AWS Lambda

- CHANGELOG.asciidoc
For https://github.com/elastic/apm-aws-lambda/pull/176. ~This fix needs to be in `3.x` before https://github.com/elastic/apm-aws-lambda/pull/176 can be merged.~
> docs: Update CHANGELOG link

- CHANGELOG.asciidoc
- lib/instrumentation/modules/aws-sdk/dynamodb.js
- lib/instrumentation/modules/aws-sdk/sns.js
- lib/instrumentation/modules/aws-sdk/sqs.js
- lib/instrumentation/modules/cassandra-driver.js
- lib/instrumentation/modules/http2.js
- lib/instrumentation/modules/ioredis.js
- lib/instrumentation/modules/memcached.js
- lib/instrumentation/modules/mongodb-core.js
- lib/instrumentation/modules/mongodb.js
- lib/instrumentation/modules/mysql.js
- lib/instrumentation/modules/mysql2.js
- lib/instrumentation/modules/pg.js
- lib/instrumentation/modules/redis.js
- lib/instrumentation/modules/tedious.js
- lib/instrumentation/modules/ws.js
- test/instrumentation/modules/aws-sdk/sqs.test.js
Implements: https://github.com/elastic/apm-agent-nodejs/issues/2601
Marks database/datastore style spans and outgoing service request spans as exit spans, adjusts SQS tests to reflect that lack of an HTTP span.
> feat: exit spans across all module instrumentations

- test/instrumentation/span-compression.test.js
A tweak to get some details if this test (sensitive to timing) fails again in CI. 
There was a recent failure of this test in GH Actions CI: https://github.com/elastic/apm-agent-nodejs/runs/6081847063?check_suite_focus=true#step:8:2934
It might be helpful to know if `span.composite.sum` was exactly 30 for that failure, or less, to know how to best make this test less flaky.
> test: add some context to test failure to help with debugging it

- test/instrumentation/modules/http/fixtures/make-http-request.js
- test/instrumentation/modules/http/fixtures/make-https-request.js
- test/instrumentation/modules/http/http-run-context.test.js
There were a number of spurious test failures in http-run-context.test.js
earlier today during a relatively short time window. All were when
making a request to httpstat.us. A theory is httpstat.us was down
(perhaps for maint) for that time window. Let's switch to using
www.google.com for test requests instead (as was done earlier in #2521
for a similar reason.
httpstat.us is a wonderful service, but no need to be hitting it frequently
in tests and relying on it having many 9s of uptime.
> test: attempt to avoid spurious failure over temporarily down httpstat.us

- CHANGELOG.asciidoc
- lib/instrumentation/transaction.js
- test/instrumentation/transaction.test.js
This was a restriction that dated back to the v1 APM Server intake
API that required all a transaction's spans to be sent along with the
transaction.
The Java APM agent, FWIW, allows this.  
This came up in discussion about some edge cases with the OTel Bridge. As we move closer to OTel semantics, the distinction between transactions and spans gets to be less. Currently can start a child span of a span that has already ended, so it is nice to be able to do the same for a transaction.
> feat: Allow starting a span on a transaction that has already ended

- test/instrumentation/span-compression.test.js
These two 'span.composite.sum > 30' tests have been flaky in CI. A recent
failure shows a value of `29.699`. The theory is that this is due to
the setTimeout calls firing slightly sooner than 10ms as discussed at:
https://github.com/nodejs/node/issues/26578#issuecomment-473708703
Refs: #2647
An alternative theory is that this might be related to `Timer` precision issues similar to https://github.com/elastic/apm-agent-nodejs/issues/2180 given that `span.composite.sum` is calculated from span `_duration` which uses our `Timer` class.
> test: deal with test flakiness due to early setTimeout callback

- .ci/.jenkins_nightly_nodejs.yml
- .ci/.jenkins_nodejs.yml
- .ci/.jenkins_rc_nodejs.yml
- .ci/.jenkins_tav_nodejs.yml
- .github/workflows/test.yml
- CHANGELOG.asciidoc
- package.json
> chore: update CI for node v18.0.0

- CHANGELOG.asciidoc
- lib/config.js
- lib/instrumentation/modules/http2.js
- lib/instrumentation/span.js
- test/instrumentation/modules/cassandra-driver/index.test.js
- test/instrumentation/modules/http2.test.js
- test/instrumentation/modules/tedious.test.js
- test/instrumentation/span-compression.test.js
Implements: https://github.com/elastic/apm-agent-nodejs/issues/2604
This PR finishes up the span compression work by implementing an `isCompressionEligible` method that uses propagated trace context headers, exit span, and outcome to determine whether a span is eligible for compression.  It also ties up a few other loose ends that came up while implementing it. 
- Span compression is enabled by default
- HTTP 2 requests will now propagate the the trace context headers
- Span compression disabled for tedious and cassandra tests (per other "db exit spans")
- Timing adjusted for "same kind compression" test as a possible fix for observed flakiness
- ~[ ] Update TypeScript typings~
> feat: implement isCompressionEligable method

- docs/configuration.asciidoc
Fixes docs to indicate that `spanCompressionEnabled` will be set to true by default.
> fix: change spanCompressionEnabled in docs

- CONTRIBUTING.md
This is because the current automated release process triggers off the
pushed release tag, but (somewhat indirectly) depends on the npm package
having been published (for the opbeans bump-version.sh release step).
> docs: update release steps to npm-publish before pushing release tag

- CHANGELOG.asciidoc
- lib/agent.js
- test/agent.test.js
This allows specifying an explicit Transaction or Span to be the parent
of the captured APM error. Before this change the *current* Transaction
or Span is always used as the parent. That's usually desired. However,
to support OTel interface Span.recordException(), the captured error
should be a child of the span on which that method is called, even if it
isn't the current span.
https://github.com/open-telemetry/opentelemetry-js-api/blob/v1.1.0/src/trace/span.ts#L122-L128
I have not documented this option in the user docs, nor added it to
the TypeScript types because I don't expect it to be that used.
I'm happy to doc it and add it to types if people disagree. Or we can
always add it later if there are external use cases.
> feat: 'parent' option to 'agent.captureError()'

- CHANGELOG.asciidoc
- lib/tracecontext/index.js
- lib/tracecontext/traceparent.js
- package.json
- test/instrumentation/modules/@elastic/elasticsearch.test.js
- test/instrumentation/modules/http/basic.test.js
- test/instrumentation/modules/http/outgoing.test.js
- test/tracecontext/tracecontext.test.js
- test/tracecontext/traceparent.test.js
This PR pulls the global NPM `traceparent` module into a local class module file.
The span statistics work (described [here](https://github.com/elastic/apm-agent-nodejs/issues/2302#issuecomment-1115450684)) will require us to modify the `TraceParent` class (by giving it the ability to change the recorded/sampled flag).  This seems like a good opportunity to pull the `TraceParent` class into the main repo and soft-deprecate the [stand alone `traceparent`](https://www.npmjs.com/package/traceparent) NPM module. 
- ~[ ] Update TypeScript typings~
- ~[ ] Update documentation~
> feat: make TraceParent a local class module

- CHANGELOG.asciidoc
- lib/instrumentation/modules/http2.js
- test/instrumentation/modules/http2.test.js
This also fixes a crash that was possible in instrumentation if an
HTTP/2 server called `stream.respond()` after the stream had been
destroyed (and the transaction ended):
../lib/instrumentation/modules/http2.js:149
trans.res.statusCode = status
^
TypeError: Cannot set properties of null (setting 'statusCode')
Fixes: #2670
> fix: possible crash in instrumentation of an incoming HTTP/2 request

- .ci/docker/docker-compose.yml
- .ci/scripts/test.sh
- test/docker-compose.yml
This also improves the test.sh runner to dump `docker inspect ...`
info for all containers if the `docker-compose up ...` fails. This
is verbose, but allows debugging which and why a container is unhealthy
if that happens.
Fixes: #2677
I've opted not to lock the cassandra image used for GH Actions right now
because it isn't currently failing. It is possible that this Cassandra issue is
resolved before they publish a new cassandra:{4,latest} image.
> test: lock to cassandra:3.11.11 to workaround CASSANDRA-17581 for now

- .tav.yml
Use "./dev-utils/aws-sdk-tav-versions.sh" to again reduce the number
of aws-sdk versions tested in TAV tests.
It has been a while and there have been another ~70 aws-sdk package releases. The aws-sdk TAV test steps have climbed again up to the top Jenkins test step times spots:
```
% ./dev-utils/jenkins-build-slow-steps.sh https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/main/154/
...
1320367 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "10"
1327520 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "mongodb-core" "12"
1337269 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "10"
1338317 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "aws-sdk" "18"
1373482 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t …
```
> test: reduce the number of aws-sdk versions tested

- .ci/Jenkinsfile
I think this change from #2627 may have broken running the benchmarks.
* * *
Benchmarks have broken recently, starting with https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/main/161/ which is ran with commit a289d4428c2c1ac3a57b0767794cb28e928c1da4  which is #2627.
```
[2022-05-12T17:14:55.956Z] + .ci/scripts/run-benchmarks.sh apm-agent-benchmark-results.json 14
[2022-05-12T17:14:55.956Z] + RESULT_FILE=apm-agent-benchmark-results.json
[2022-05-12T17:14:55.956Z] + NODE_VERSION=14
[2022-05-12T17:14:55.956Z] + [[ -z apm-agent-benchmark-results.json ]]
[2022-05-12T17:14:55.956Z] + [[ -z 14 ]]
[2022-05-12T17:14:55.956Z] ++ dirname .ci/scripts/run-benchmarks.sh
[2022-05-12T17:14:55.956Z] + SCRIPTPATH=.ci/scripts
[2022-05-12T17:14:55.956Z] + source …
```
> test: fix running benchmarks

- .tav.yml
mysql2@2.2.3 (and only that version) has a github dep:
"@types/mysql": "types/mysql",
Attempting to install that version with npm v6 (the npm in node v10, v12, and
v14) hits https://github.com/npm/cli/issues/4896 which results in an
install so slow that is hits the default 2 minute 'npm install' timeout
in the `tav` tool.
This is the same root cause of https://github.com/elastic/apm-integration-testing/issues/1483
> test: skip mysql2@2.2.3 in TAV tests to workaround npm v6 install issue with github deps

- .ci/Makefile
- CHANGELOG.asciidoc
AFAIK the "compatible runtimes" flag on Lambda layers is just advisory.
For example I can use our current latest Lambda layer with a
nodejs16.x-using Lambda function.
> feat: add "nodejs16.x" lambda runtime to our compatible runtimes

- lib/instrumentation/index.js
- test/agent.test.js
I get a
> TypeError: Cannot read properties of null (reading 'ended')\n  at Instrumentation.addEndedSpan (/app/node_modules/elastic-apm-node/lib/instrumentation/index.js:361:29
when continuing a trace from a context. 
Looking at the code `isCompressionEligible` checks whether `getParent` returns anything and if not returns false which makes me think that the order of the conditions is the wrong way around here.
> prevent npe when we have no Span as parent

- CHANGELOG.asciidoc
- examples/trace-sqs-receive-message.js
- examples/trace-sqs-send-message.js
- lib/constants.js
- lib/instrumentation/generic-span.js
- lib/instrumentation/modules/aws-sdk/sqs.js
- lib/opentelemetry-bridge/README.md
- test/instrumentation/modules/aws-sdk/fixtures/sqs.js
- test/instrumentation/modules/aws-sdk/sqs.test.js
Refs: #2593
This is *part* of https://github.com/elastic/apm-agent-nodejs/issues/2593. The change just for SQS instrumentation got large enough that I'll break it up into a few PRs: SQS, SNS, and Lambda instrumentation updates.
> feat: add span links to AWS SQS ReceiveMessage spans for messages with a traceparent

- CHANGELOG.asciidoc
- lib/instrumentation/span.js
- test/instrumentation/github-issue-2715.test.js
Closes: https://github.com/elastic/apm-agent-nodejs/issues/2715
When span compression is enabled and a span is compression eligible ensure the context is not nulled out in order to ensure its available for span serialization/encoding. 
~- [ ] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)~
> fix: get context back for composite spans

- .ci/Makefile
The `BRANCH_NAME=... make -C .ci dist` failed on
cp: ../build/aws/elastic-apm-node-lambda-layer-...zip: No such file or directory
because the "../build/aws" dir had not been created.
This was broken in #2627.
This fixes the failure in the release pipeline for the [v3.34.0 release](https://github.com/elastic/apm-agent-nodejs/pull/2723): https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/v3.34.0/1/pipeline
```
[2022-05-25T17:36:24.008Z] The lambda layer can be published as follows for dev work:
[2022-05-25T17:36:24.008Z]     aws lambda --output json publish-layer-version --layer-name '-dev-elastic-apm-node' --description ' dev Elastic APM Node.js agent lambda layer' --zip-file 'fileb://build/lambda-layer-zip/elastic-apm-node-lambda-layer.zip' …
```
> fix: build of Lambda layer broke in CI

- .github/workflows/labeler.yml
We just turned on dependabot version update PRs and they are getting 'community' and 'triage' labels, which they should now. This tweak copies the apm-agent-java https://github.com/elastic/apm-agent-java/blob/main/.github/workflows/labeler.yml#L29
> chore: do not add 'community' and 'triage' labels to dependabot PRs

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/ioredis.js
- test/instrumentation/modules/ioredis.test.js
Enable support for ioredis v5
It seems to work all right with this small change, I don't see anything in their [breaking changes](https://github.com/luin/ioredis/blob/main/CHANGELOG.md#500-2022-03-26) that would involve a larger change in APM.
I wasn't sure if this was a feat or a chore, let me know if I should change.
> feat: enable ioredis v5

- CHANGELOG.asciidoc
- lib/instrumentation/index.js
- lib/lambda.js
- test/lambda/github-issue-2709.test.js
Closes: #2709
This PR refactors the `getLambdaHandlerInfo` function to handle lambda function handlers with nested paths (`_HANDLER=path/to/file.methodName`)
When extracting a Lambda Handler's module the `getLambdaHandlerInfo` function will now shift off the final name in the path, matching the behavior of require-in-the-middle.  This, in turn, will allow wrapping to take place. 
> Fix Lambda _HANDLER=path/to/file.methodName Form

- .ci/Jenkinsfile
The requirement is by top-level code in "bash_standard_lib.sh"
(provided by infra) and used in "push-docker.sh" when run in CI.
* * *
This fixes a release failure in https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/v3.35.0/2/pipeline
```
...
[2022-06-02T15:14:37.175Z] ../dev-utils/push-docker.sh docker.elastic.co observability/apm-agent-nodejs 3.35.0
[2022-06-02T15:14:37.175Z] /usr/local/bin/bash_standard_lib.sh: line 4: HOME: unbound variable
[2022-06-02T15:14:37.276Z] Makefile:31: recipe for target 'push-docker' failed
...
```
> fix: the "Push Docker Image" jenkins step requires a HOME var

- .ci/Jenkinsfile
The HOME envvar is needed for the 'Push Docker Image' step in the
'Release' stage. While the Release stage currently uses the
main/top-level Jenkins agent, it might not always, so it is
safer/cleaner to define it closer to the needed stage.
> chore: move HOME envvar to 'Release' stage closer to where it is needed

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/knex.js
- test/instrumentation/modules/pg/knex.test.js
Refs: #2699
Feat: Add support for `knex` between v0.21 and v0.95.15 included
> Feat: Add support for knex between 0.21 and 0.95.15 included

- CHANGELOG.asciidoc
- lib/instrumentation/modules/express.js
- test/instrumentation/modules/express/basic.test.js
Express considers any value passed to a handler's next() handler
to be an error, except the special case 'route' and 'router' strings.
Before this change the agent's Express route handling (used for setting
transaction.name) would only consider the arg to be an error if
`instanceof Error`.
Refs: #2741
> fix: Express route calc when next(err-that-is-not-Error-instance) is used

- .eslintrc.json
- CHANGELOG.asciidoc
- NOTICE.md
- lib/instrumentation/modules/_lambda-handler.js
- lib/lambda.js
- lib/propwrap.js
- test/lambda/fixtures/esbuild-bundled-handler/Makefile
- test/lambda/fixtures/esbuild-bundled-handler/README.md
- test/lambda/fixtures/esbuild-bundled-handler/hello.js
- test/lambda/fixtures/esbuild-bundled-handler/hello.ts
- test/lambda/wrap-bundled-handler.test.js
- test/lambda/wrapper.test.js
- test/propwrap.test.js
> fix: handle wrapping Lambda handlers in modules that only provide getters to the handler properties

- .ci/Jenkinsfile
Responsibility for updating the elastic-apm-node dep in
opbeans-node.git will move to *opbeans-node*'s CI.
Refs: https://github.com/elastic/opbeans-node/issues/164
Fixes: #2728
> chore: drop Opbeans update stage of the CI Release pipeline

- docs/setup.asciidoc
The "(higher overwrites lower)" for config precendence can be
confusing because "4" is higher than "1" in the numbered bullets,
but that's not what is intended.
> docs: drop potentially confusing language in config precendence

- .github/dependabot.yml
- .tav.yml
- package-lock.json
- package.json
- test/instrumentation/modules/http/github-423.test.js
We use 'got' in our tests only to test its usage by mimic-response.
got@11 dropped usage of mimic-response, so there is no point having
anything later than got@10.
* * *
This PR will stop dependabot suggesting updates to got beyond got@10, e.g. no more PRs like https://github.com/elastic/apm-agent-nodejs/pull/2784
> chore: update to got@10 and stop there

- test/instrumentation/modules/http2.test.js
- test/parsers.test.js
As of https://github.com/nodejs/node/issues/37184 node v19 and later
defaults the http,https.globalAgent to use keep-alive:
- globalAgent: new Agent()
+ globalAgent: new Agent({ keepAlive: true, scheduling: 'lifo', timeout: 5000 })
This change in default broke a couple tests. The agent itself is
unaffected because our http client already uses a custom http agent
using keep-alive.
* * *
This should fix recent Jenkins CI failures in the "Nightly Test" stage.
E.g. https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/main/267/pipeline/7010
This started failing with the `v19.0.0-nightly20220630350a6a8d59` nightly node build which included these node commits:
```
* 350a6a8d59 - perf_hooks: add initiatorType getter
* a0440c9174 - doc: add …
```
> tests: fix test failures with node v19 change to default http clients to use keep-alive

- test/benchmarks/scripts/run-benchmarks-ci.sh
"12th Gen Intel(R) Core(TM) i5-12500" is a new CPU model appearing in CI
benchmark runs in the last week.
* * *
This should fix recent "Benchmarks" CI failures, e.g. https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/main/265/pipeline
```
...
[2022-06-30T18:44:11.560Z] + setUp
[2022-06-30T18:44:11.560Z] + echo 'Setting CPU frequency to base frequency'
[2022-06-30T18:44:11.560Z] Setting CPU frequency to base frequency
[2022-06-30T18:44:11.560Z] ++ lscpu
[2022-06-30T18:44:11.560Z] ++ grep 'Model name'
[2022-06-30T18:44:11.560Z] ++ awk '{for(i=3;i<=NF;i++){printf "%s ", $i}; printf "\n"}'
[2022-06-30T18:44:11.560Z] + CPU_MODEL='12th Gen Intel(R) Core(TM) i5-12500 '
[2022-06-30T18:44:11.560Z] + '[' '12th Gen Intel(R) Core(TM) i5-12500 ' == …
```
> test: fix setup of benchmarks in CI on new CPU models

- .github/dependabot.yml
- .tav.yml
- lib/instrumentation/modules/mimic-response.js
- package-lock.json
- package.json
- test/instrumentation/modules/http/github-423.test.js
got@11.8.5 includes a fix for CVE-2022-33987. Ours is a dev-dep so the
vuln shouldn't affect us. This update is effectively the same thing
as the recent #2784 from dependabot.
This also removes the change from #2785 to lock us to got@10, and
clarifies that we want to continue testing with recent versions of 'got'
as a sanity check that the agent works with it. At least for now.
* * *
Alan, initially I closed the [dependabot PR to update us to got@11](https://github.com/elastic/apm-agent-nodejs/pull/2784) and did #2785 instead to lock us on got@10, based on the arguments that (a) testing with got is *only* for testing the mimic-response@1.0.0 issue and (b) got@11 no longer uses mimic-response.
I had missed that there is a vuln in got@10 that is fixed in latest got@11 and got@12. We …
> chore: bump to got@11.8.5 for vuln fix

- package.json
There are node v19 nightlies now and tests (currently) pass.
Adding v19 to "engines" avoids "EBADENGINE" warnings from 'npm install
elastic-apm-node'
* * *
Currently this is what a user of node v19 sees when trying to install:
```
% node --version
v19.0.0-nightly202206287cbcc4fc43
% npm install elastic-apm-node
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'elastic-apm-node@3.36.0',
npm WARN EBADENGINE   required: { node: '^8.6.0 || 10 || 12 || 14 || 16 || 17 || 18' },
npm WARN EBADENGINE   current: { node: 'v19.0.0-nightly202206287cbcc4fc43', npm: '8.13.1' }
npm WARN EBADENGINE }
up to date, audited 132 packages in 493ms
38 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
> chore: allow use with node v19

- .ci/Jenkinsfile
- dev-utils/gen-notice.sh
The "Dist" step in the release process in Jenkinsfile was failing with
npm ERR! code ELSPROBLEMS
npm ERR! missing: @babel/cli@^7.8.4, required by elastic-apm-node@3.37.0
... ditto for every *dev* dependency ...
The part that was actually failing was 'npm ls --omit=dev --all --parseable'
in "gen-notice.sh" when run in a dist try that only has the non-dev deps
installed.
The issue was a too-old npm: node 16.15.0 includes npm 8.5.5, but we
require npm v8.7.0 to get support for 'npm ls --omit=dev ...'
(https://github.com/npm/cli/pull/4744).
* * *
Initial discussion for this was on the PR for the 3.37.0 release here: https://github.com/elastic/apm-agent-nodejs/pull/2830#issuecomment-1188303303
I wasn't able to reproduce this on my dev machine initially because (a) initially I'd been using node …
> fix: "Dist" step failed in Jenkins with ELSPROBLEMS

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- index.d.ts
- lib/config.js
- lib/instrumentation/generic-span.js
- lib/instrumentation/index.js
- lib/instrumentation/span.js
- test/central-config-enabled.test.js
- test/instrumentation/drop-fast-exit-spans.test.js
Closes: https://github.com/elastic/apm-agent-nodejs/issues/2301
Refs: https://github.com/elastic/apm/issues/496
Introduces the `exitSpanMinDuration` configuration value.
> fast exit spans

- lib/instrumentation/http-shared.js
I don't think this currently impacts anything. Because http spans always
propagate trace-context they cannot be compressed or dropped. If we
later add child HTTP spans (to breakdown dns, connect, etc. phases) then
it will matter.
> fix: 'http' spans should be marked as exitSpans

- test/instrumentation/drop-fast-exit-spans.test.js
In one of my PRs I saw this spurious test failure in drop-fast-exit-spans.test.js:
https://github.com/elastic/apm-agent-nodejs/runs/7681916973?check_suite_focus=true
```
running test: cd . && node --require /home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/_promise_rejection.js test/instrumentation/drop-fast-exit-spans.test.js
TAP version 13
ok 1 spans are not discardable by default
ok 2 exit spans are discardable
ok 3 exit spans are discardable
ok 4 failed spans are not discardable
ok 5 exit spans are discardable
ok 6 spans with propagated context are not discardable
ok 7 should be strictly equal
ok 8 should be strictly equal
not ok 9 should be strictly equal
---
operator: equal
expected: 0
actual:   1
at: <anonymous> (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/instru …
```
> test: bump test exitSpanMinDuration to avoid spurious test failures due to event-loop delay

- CHANGELOG.asciidoc
- lib/lambda.js
- test/lambda/mock/transaction.js
- test/lambda/trans-setDefaultName.test.js
Before this the Lambda instrumentation was setting `trans.name = ...`,
which (via the Transaction.name setter) would set `trans._customName`,
which has higher prio than the `trans._defaultName`. Setting
`_customName` is intended for the *user* to override. If a Lambda
function is using GraphQL, the graphql instrumentation should be able to
override the transaction name.
Fixes: #2832
> fix: lambda instrumentation must set transaction *default* name to allow subsequent override by graphql instrumentation

- CHANGELOG.asciidoc
- lib/instrumentation/modules/aws-sdk/s3.js
- test/_validate_schema.js
- test/instrumentation/modules/aws-sdk/s3.test.js
The APM agent spec for S3 spans says
`span.context.destination.service.resource` should be the bucket name
or access point, if available. That isn't available for ListBuckets,
which doesn't operate on a bucket. In this case the APM agent was emiting:
span.context.destination.service = { name: ..., type: ... }
which fails APM server schema validation with
missingProperty: 'resource'
and results in APM server intake logs with:
Error: validation error: span: context: destination: service: 'resource' required
The fix, for now, is to skip `span.context.destination.service` entirely
for ListBuckets.
----
Dropping `span.context.destination.service` for `ListBuckets` spans will mean the span will be accepted by APM server (good), but won't result in "S3" being recognized as a backend for the …
> fix: an S3 ListBuckets span was invalid for APM server intake

- CHANGELOG.asciidoc
- lib/errors.js
- test/errors.test.js
Fixes: #2030
----
Example of the tests failing without the fix:
```
...
ok 39 got expected attrs
ok 40 got expected attrs
/Users/trentm/el/apm-agent-nodejs6/lib/errors.js:99
val = val.toISOString()
^
RangeError: Invalid time value
at Date.toISOString (<anonymous>)
at attributesFromErr (/Users/trentm/el/apm-agent-nodejs6/lib/errors.js:99:21)
at Test.<anonymous> (/Users/trentm/el/apm-agent-nodejs6/test/errors.test.js:366:21)
at Test.bound [as _cb] (/Users/trentm/el/apm-agent-nodejs6/node_modules/tape/lib/test.js:99:32)
at Test.run (/Users/trentm/el/apm-agent-nodejs6/node_modules/tape/lib/test.js:117:31)
at Test.bound [as run] (/Users/trentm/el/apm-agent-nodejs6/node_modules/tape/lib/test.js:99:32)
at Test._end (/Users/trentm/el/apm-agent-nodejs6/node_modules/tape/lib/test.js:220:11)
at …
```
> fix: captureError would fail on an Error attribute that is an invalid date

- .github/ISSUE_TEMPLATE/Bug_report.md
Before this change, if you pasted in multiline content for the
"replace this line with ..." lines and didn't manually indent all those
pasted lines, then the GitHub rendered markdown `<details>` segments
would not be rendered as intended. By left justifying all the markup,
the bug reporter doesn't need to manually indent pasted lines.
> chore: improve usability of "Bug report" issue template

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/tedious.js
- package-lock.json
- package.json
- test/config.test.js
- test/instrumentation/modules/tedious.test.js
This adds support for tedious 15.x, which was first published in July:
```
$ npm info tedious time
...
'15.0.0-beta.1': '2022-07-11T08:22:36.753Z',
'15.0.0': '2022-07-11T17:56:34.399Z',
'15.0.1': '2022-07-26T08:11:31.852Z',
'15.1.0': '2022-08-17T20:33:59.478Z'
}
```
tedious@15 drops support for Node 12.
https://github.com/tediousjs/tedious/releases/tag/v15.0.0
Supersedes: https://github.com/elastic/apm-agent-nodejs/pull/2893 (dependabot PR for this)
> feat: tedious@15 support

- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/knex.js
- test/instrumentation/modules/pg/knex-no-span-stack-traces.test.js
Knex instrumentation exists only for better span stack traces. It should
be disabled when not collecting span stack traces. This should be a
perf win for default usage of Knex because we avoid an expensive
`Error.captureStackTrace(obj)` for each wrapped knex query.
Obsoletes: #506
* * *
Here I'm finishing up work started by @watson in #506. I updated for the newer config var (`spanStackTraceMinDuration`), added a test, and tweaked the knex-related docs.
> perf: disable Knex instrumentation if spanStackTraceMinDuration=-1

- .github/dependabot.yml
These deps are updated frequently (aws-sdk almost daily) and distract from more important dependabot updates.
Also bump the default to 10 for the weekly updates so we can actually get through the backlog.
---
I picked the set of monthly deps partially from the frequency of dependabot merges that we've done so far:
```
% git log --oneline | rg deps-dev | cut -d' ' -f4 | sort | uniq -c | sort -n | tail
2 @elastic/elasticsearch
2 apollo-server-express
2 undici
2 ws
3 @babel/preset-env
3 fastify
3 ioredis
3 mongodb
4 @babel/core
5 @types/node
```
Also, for interest sake, https://github.com/elastic/apm-agent-nodejs/network/updates/456488058 shows a log of the latest dependabot run against the repo. Grepping that log for deps that need updates yet:
```
% rg 'Updating ' dependabot-run.log …
```
> chore: reduce freq of dependabot updates for some deps to monthly

- .ci/docker/docker-compose.yml
- .github/workflows/test.yml
- test/docker-compose.yml
With MongoDB 6 containers (released in the last week), the `mongo`
binary is gone, replaced by `mongosh`.
See https://github.com/docker-library/mongo/issues/558
Our tests were using `mongo:latest`. For now let's lock to mongo:5 and
then have a separate issue for updating container versions for testing.
> test: lock to mongo:5 container, recently released mongo:6 breaks our healthcheck

- .tav.yml
- DEVELOPMENT.md
- dev-utils/bitrot.js
- docs/supported-technologies.asciidoc
'dev-utils/bitrot.js' is a small CLI that will compare the entries in ".tav.yml" and "supported-technologies.asciidoc" for inconsistencies and for whether our supported instrumentation version ranges are behind current releases.
Helpfully, this parsing also noticed a couple errors in our .tav.yml (missing "name: ..." params) that were resulting in use not testing some older module versions.
---
A current run of bitrot shows:
```
% ./dev-utils/bitrot.js
knex bitrot: latest knex@2.3.0 (released 2022-08-31): is not in .tav.yml ranges (^0.16.5 || <0.16.4 >=0.16.0 || ^0.15.0 || ^0.14.0 || ^0.13.0 || ^0.12.5 || <0.12.4 >0.11.6 || <0.11.6 >0.9.0, >=0.17 <0.21, >=0.21 <1), is not in supported-technologies.asciidoc ranges (>=0.9.0 <1.0.0)
mongoose bitrot: latest mongoose@6.6.0 (released …
```
> chore: add a dev utility to list issues with instrumention module version ranges

- .ci/Jenkinsfile
- DEVELOPMENT.md
Refs: https://github.com/elastic/apm-integration-testing/issues/1523
---
The Go agent recently did the same: https://github.com/elastic/apm-agent-go/pull/1318
> ci: remove Integration Tests stage

- .tav.yml
This reduces from 97 versions tests down to 7.
----
The time for TAV runs on main (in Jenkins CI) has crept up from ~1h to 1h20m of late.
```
% ./dev-utils/jenkins-build-slow-steps.sh https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/main/410/ | tail
1619313 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "8"
1642453 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "14"
1651751 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "aws-sdk" "18"
1802458 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "12"
2038386 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "14"
2123879 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "12"
2179244 FINISHED SUCCESS …
```
> test: reduce TAV tested versions of aws-sdk

- .tav.yml
- docs/supported-technologies.asciidoc
This removes TAV testing of apollo-server-express@2 versions with
graphql@^0.12.0 and graphql@^0.13.0. We still test
apollo-server-express@2 with more recent versions of graphql. The
latest graphql 0.13 release was 2018-03-16.
This removes TAV testing of express-graphql versions before 0.10.0 --
the latest such release was 2019-07-15.
---
Motivation: apollo-server-express TAV testing is one of our slow ones -- up to ~40 minutes for each node version.
Also, FWIW, the config for testing apollo-server-express and express-graphql in ".tav.yml" is
179 of the total 586 lines. Much of that is to be continuously testing versions of packages that are more than 3 years old.
```
% ./dev-utils/jenkins-build-slow-steps.sh https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/main/ …
```
> test: reduce apollo-server-express and express-graphql TAV matrix

- .github/dependabot.yml
https://github.com/elastic/apm-agent-nodejs/network/updates was showing:
> The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
What we'd been *intending* in our dependabot config was to say "update
my package.json deps weekly, except for this subset of
frequently-updated modules that I just want updated monthly".  I guess
we cannot use two config blocks in dependabot.yml to get the desired
behaviour.
* * *
Alternative options:
1. Drop the second config block, give up, and just take frequent dependabot version update PRs for `@babel/preset-env` and others.
2. Drop the second config block, and use the `@dependabot ignore this major|minor version` command on the next version update PR for those …
> chore: drop unsupported second dependabot.yml config block for package.json

- docs/koa.asciidoc
- docs/supported-technologies.asciidoc
This fixes the formatting of the "Frameworks" table in the supported-technologies doc page. It was broken by me recently in #2924. It never made it to a release.
This also updates the repo link for koa-router. The previous link *was* the original, but now it redirects to a fork (https://github.com/ZijianHe/koa-router) that hasn't been updated since 2019. At some point the official `koa-router` npm package releases moved to https://github.com/koajs/router
You can currently see the broken state at https://www.elastic.co/guide/en/apm/agent/nodejs/master/supported-technologies.html#compatibility-frameworks  
The rows are all messed up. AsciiDoc table markup is definitely not Markdown table markup.
* * *
I've also re-ordered the table to be mostly alphabetical.
* * *
> docs: fix formatting of the Frameworks table; also update koa-router repo link

- CHANGELOG.asciidoc
- lib/instrumentation/span.js
- lib/instrumentation/timer.js
- lib/instrumentation/transaction.js
This avoids a possible 'RangeError: Maximum call stack size exceeded' as
described in #2929.
The case the user hit is in `maybeTime(...)` used in Span timer handling.
Fixed by dropping the recursion.  A `Timer` instance's `_timer` is always the
same object as its parent's `_timer` if it has a parent, so there is no
need to walk the chain.
Refs: #2929 
---
See the discussion at https://github.com/elastic/apm-agent-nodejs/pull/2929 for why this doesn't include tests. We don't have a perfect understanding of how this is happening so don't have a good test to add.  If this passes the current breakdown metrics tests ("test/metrics/breakdown.test.js"), then I think this should be good as a workaround for the user's issue.
> fix avoids a possible 'RangeError: Maximum call stack size exceeded' in maybeTime(...)

- docs/lambda.asciidoc
- docs/lambda/configure-lambda.asciidoc
- AWS Lambda extension docs moved from the APM Guide to their own docs. Fixing links.
- added `background` as recommended send strategy in the docs
> Correct links to Lambda extension docs

- test/instrumentation/modules/redis.test.js
client.set('foo') fails on 4.1, but not on 4.0.
---
The redis TAV tests failed today: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/main/464/pipeline
```
[2022-10-25T07:01:48.084Z] node_tests_1  | -- installing ["redis@4.0.6"]
[2022-10-25T07:01:57.820Z] node_tests_1  | -- running test "node test/instrumentation/modules/redis.test.js" with redis
...
not ok 61 no response expected
---
operator: fail
at: <anonymous> (/Users/trentm/el/apm-agent-nodejs4/test/instrumentation/modules/redis.test.js:167:7)
stack: |-
Error: no response expected
at Test.assert [as _assert] (/Users/trentm/el/apm-agent-nodejs4/node_modules/tape/lib/test.js:312:48)
at Test.bound [as _assert] (/Users/trentm/el/apm-agent-nodejs4/node_modules/tape/lib/test.js:95:17)
at …
```
> test: fix redis TAV tests with redis 4.0.x

- .ci/.jenkins_nightly_nodejs.yml
Now that v19.0.0 is out, nightlies at https://nodejs.org/download/nightly/ are for v20.
E.g.:
```
v20.0.0-nightly2022101987cdf7d412/                 19-Oct-2022 07:00                   -
v20.0.0-nightly20221020b4efac4820/                 20-Oct-2022 07:30                   -
v20.0.0-nightly20221021eb32a8443a/                 21-Oct-2022 07:30                   -
v20.0.0-nightly20221022e43d191bcb/                 22-Oct-2022 07:00                   -
v20.0.0-nightly2022102389c4e1f967/                 25-Oct-2022 12:00                   -
v20.0.0-nightly20221024aab9f3246e/                 25-Oct-2022 12:00                   -
v20.0.0-nightly20221025c6c18a9a24/                 25-Oct-2022 07:00                   -
v20.0.0-nightly202210265e2aeae032/                 26-Oct-2022 09:00 …
```
> chore: test node v20 nightlies now that v19.0.0 has been released

- dev-utils/bitrot.js
- We have 'js-yaml' as a dep now, so it isn't a cheat.
- The current js-yaml version removed `.safeLoad` in favour of `.load`.
- Update regex for some formatting changes made to supported-technologies.asciidoc a little while back.
> chore: fix bitrot.js util for recent changes

- test/instrumentation/modules/next/a-nextjs-app/.tav.yml
- test/instrumentation/modules/next/next.test.js
1. next.test.js was failing in Docker/CI with node v14 and v16
because https://nextjs.org/telemetry automatically turned on
which resulted in APM spans for `POST telemetry.nextjs.org`
during tests, which broke assertions.
2. `next build` with Next.js v11 and Node.js >=17 crashes due to
https://github.com/vercel/next.js/issues/30188
We just skip testing that older Next.js with newer Node.js.
> test: fix two TAV=next test failures with Next.js v11

- .tav.yml
- docs/supported-technologies.asciidoc
- package-lock.json
- package.json
- test/_is_hapi_incompat.js
Our instrumentation already worked with hapi v21, but the tests
would attempt to use node v12 (which hapi v21 dropped support for).
> test, docs: @hapi/hapi@21

- test/_is_restify_incompat.js
This is a follow-on to #3031 to handle testing of Node.js nightly
builds. These have a prerelease version, e.g.
"v20.0.0-nightly202211186f9175deaa", and therefore need the
includePrelease semver option for gte comparison.
Refs: #3031
> test: fix nightly tests to properly skip prerelease node versions >=18

- CHANGELOG.asciidoc
- lib/lambda.js
- test/lambda/fixtures/aws_api_http_test_data.json
- test/lambda/fixtures/aws_api_rest_test_data.json
- test/lambda/trans-setDefaultName.test.js
- test/lambda/transaction.test.js
- test/lambda/transaction2.test.js
https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws-lambda.md#api-gateway--lambda-urls
> The agent should use the information in the request and response
> objects to fill the HTTP context (context.request and context.response)
> fields in the same way it is done for HTTP transactions.
Closes: #2419
> feat: capture HTTP context for API Gateway-triggered Lambda functions

- .ci/Makefile
- CHANGELOG.asciidoc
This is just about adding "nodejs18.x" to the advisory "compatible runtimes" for the published layers. The previous images supported the nodejs18.x runtime just fine already.
> chore: mark Lambda layer as supporting the new nodejs18.x lambda runtime

- docs/configuration.asciidoc
- docs/custom-stack.asciidoc
- docs/express.asciidoc
- docs/fastify.asciidoc
- docs/hapi.asciidoc
- docs/koa.asciidoc
- docs/opentracing.asciidoc
- docs/restify.asciidoc
- docs/setup.asciidoc
- examples/trace-http-request.js
- lib/agent.js
- lib/config.js
- package-lock.json
- package.json
- test/config.test.js
Starting in node v17 the defaults for DNS resolution order was
changed (https://github.com/nodejs/node/pull/39987) such that
`dns.lookup()` no longer sorted IPv4 addresses first. This impacts
usage of the *default* APM Server URL (the `serverUrl` config var),
'http://localhost:8200', when using node >=17 because the APM server
only binds to the IPv4 address by default
(https://github.com/elastic/apm-server/issues/1405).
Fixes: #3045
Refs: https://github.com/elastic/apm/pull/727
* * *
This is a start of the change. I've docs and the http-client, etc. to update. Also I'll follow up with an APM agents shared spac PR change.
> fix: avoid IPv4 vs IPv6 ambiguity in default 'serverUrl' by using '127.0.0.1' rather than 'localhost'

- .ci/Jenkinsfile
- .ci/snapshoty.yml
- package.json
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Add support for daily snapshots.
Validation: https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-3050/11/
> Support publishing a snapshot build for each commit to main

- .eslintrc.json
- CHANGELOG.asciidoc
- lib/instrumentation/index.js
- test/instrumentation/span-compression.test.js
https://github.com/elastic/apm/blob/main/specs/agents/handling-huge-traces/tracing-spans-compress.md#span-buffering says:
> A buffered span gets reported when
>  1. its parent ends
>  2. a non-compressible sibling ends
Before this change, case 2 was not being handled. Further, a possibly
buffered span on the ending sibling would incorrectly get sent *twice*.
The scenario is as follows:
```
trans t0
span s1: _bufferdSpan=s2
span s2: ended, compressible -> buffered on s1
span s3: incompressible, _bufferdSpan=s4
span s4: ended, compressible -> buffered on s3
```
What happens when s3 ends? We expect:
- s4 is encoded and sent
- s2 is encoded and sent
- s3 is encoded and sent
Before this change the agent would send: s4, s4, s3
Refs: https://discuss.elastic.co/t/apm-agent-send-duplicate-record-in …
> fix: span compression bug where a buffered span would not be sent when an incompressible sibling ended

- dev-utils/bitrot.js
- The script was mistakenly assuming that the anchor in the "Frameworks"
doc table, "nextjs", matched the npm package name, "next".
- Also, it wasn't looking at the separate .tav.yml in the Next.js test
dir.
> fix bitrot.js dev-util to work for Next.js versions

- lib/errors.js
- package-lock.json
- package.json
- test/errors.test.js
The test for `error.exception.module` for a reported APM error using
`@elastic/elasticsearch` broke with the recent `8.6.0` version...  as
installed by the npm in node v14.
The issue was that the install tree changed such that the error stack
top frame was in:
node_modules/@elastic/elasticsearch/node_modules/@elastic/transport/lib/Transport.js
rather than:
node_modules/@elastic/transport/lib/Transport.js
for reasons independent of the `@elastic/elasticsearch@8.6.0` release.
The `_moduleNameFromFrames` utility didn't handle a nested
`node_modules/...` dir.  This change fixes that.
---
This was failing in TAV tests for the last few days. E.g.:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/main/565/pipeline
```
-- installing …
```
> fix TAV test failure with @elastic/elasticsearch@8.6.0 and node v14

- lib/instrumentation/azure-functions.js
From "timer". Neither value is in the APM agents shared spec, but
"scheduled" is prior art from some Java instrumentations (e.g. for
Quartz).
Refs: #3071
---
Bias to a common value for similar usage from the Java agent. Possible spec'ing of this in the shared APM agents specs can come later.
> chore: switch to transaction.type="scheduled" for timer-triggered Azure Functions

- CHANGELOG.asciidoc
- lib/instrumentation/dropped-span-stats.js
- test/instrumentation/dropped-span-stats.test.js
Before this change it could be a float, which is rejected by the APM
server intake API.
Fixes: #3104
> fix: ensure `transaction.dropped_spans_stats[*].duration.sum.us` is an int

- .tav.yml
- test/_is_hapi_incompat.js
- test/instrumentation/modules/hapi/set-framework-hapihapi.test.js
- test/instrumentation/modules/hapi/shared.js
The 'http.request' instrumentation fix in #3090 uncovered a bug in our
tests for @hapi/hapi when with node v8 (a version before
`http.request(url, opts, cb)` was supported in node). This fixes that.
This also updates the .tav.yml section for '@hapi/hapi' to align with
logic in "_is_hapi_incompat.js" so the TAV tests don't waste time
installing a version of Hapi for which tests will be skipped anyway.
Refs: #3090
---
A TAV test failure example is here: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/main/578/pipeline/2844
The test hanged:
```
.ci/scripts/test.sh -b "release" -t "@hapi/hapi" "8" 
...
[2023-01-18T07:05:32.394Z] node_tests_1  | -- required packages ["@hapi/hapi@18.4.1"]
[2023-01-18T07:05:32.394Z] node_tests_1  | -- …
```
> test: fix TAV=@hapi/hapi test failure with node v8

- test/instrumentation/modules/next/next.test.js
Recently there was a spurious CI test failure with Node.js v14 where
a first test run ran this 'npm ci' and it failed with:
Error: Command failed: npm ci
npm ERR! cb() never called!
This is an old old npm issue that will never get fixed, because we are
running tests with an old node and old npm.
The CI setup currently will retry the full test run on failure. The
*second* run failed because the `npm ci` was skipped -- because the
first failed attempt created "./node_modules" but not the full install
under it -- and then went on to fail to spawn
"./node_modules/.bin/next".
> test: run 'npm ci' on a second test run if the first 'npm ci' possibly failed

- lib/instrumentation/modules/@elastic/elasticsearch.js
In #2550 this module was rewritten to not be primarily based on
the ES client "diagnostic" events for instrumentation. That change
should have also removed this part of the top-comment.
Refs: #2550
---
No functional change.
> chore: correct comment on ES client instrumentation

- CHANGELOG.asciidoc
- lib/activation-method.js
- test/activation-method/activation-method.test.js
This also fixes a bug where the value "k8s-attacher" was erroneously
used.
Closes: #3119
Refs: #3041, https://github.com/elastic/apm-mutating-webhook/pull/69
> fix: activation_method='k8s-attach' now uses explicit ELASTIC_APM_ACTIVATION_METHOD

- package.json
- test/instrumentation/azure-functions/azure-functions.test.js
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package.json
This is because the 'azure-function-core-tools' package install on
Windows is too flaky in CI.
Closes: #3107
---
This implements option 1 described in #3107.
> test: skip Azure Functions tests on Windows

- .ci/snapshoty.yml
Use github-actions metadata and git branch references
Otherwise, it fails
```
⇒ Loading configuration...
✓ Succeeded to load configuration
Traceback (most recent call last):
File "snapshoty/artifacts.py", line 78, in walk
File "string.py", line ***63, in format
File "string.py", line ***67, in vformat
File "string.py", line ***07, in _vformat
File "string.py", line ***7***, in get_field
File "string.py", line ***9, in get_value
KeyError: 'jenkins_***_name'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "snapshoty/commands.py", line 87, in ***
File "snapshoty/artifacts.py", line 8***, in walk
ValueError: Failed to find `jenkins_***_name` metadata
```
when running on debug mode, see …
> snapshoty: migrate to github actions

- index.d.ts
TypeScript declaration for `AgentConfigOptions` was missing the `opentelemetryBridgeEnabled` option.
> fix: add opentelemetryBridgeEnabled option to TS declaration for AgentConfigOptions

- CHANGELOG.asciidoc
- index.d.ts
Prompted by https://github.com/elastic/apm-agent-nodejs/pull/3121 for another missing config option from this type.
> fix: add missing 'contextManager' config var to TypeScript types

- .tav.yml
The aws-sdk TAV tests are again getting to be the longest-running
ones, taking over 30m in Jenkins CI.
---
```
$ ./dev-utils/jenkins-build-slow-steps.sh https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/main/592/
...
1469845 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "pg" "12"
1470370 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "tedious" "12"
1473120 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "tedious" "14"
1474314 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "fastify" "14"
1474713 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "graphql" "14"
1475815 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "graphql" "12"
1478359 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "aws-sdk" "16"
1481406 FINISHED SUCCESS …
```
> test: reduce the number of aws-sdk versions tested in TAV tests

- CHANGELOG.asciidoc
- lib/lambda.js
- lib/parsers.js
- test/lambda/fixtures/aws_elb_test_data.json
- test/lambda/mock/transaction.js
- test/lambda/trace-context.test.js
- test/lambda/transaction2.test.js
The transaction captured for a Lambda triggered by a Lambda function URL
or by ELB (an Application Load Balancer targetting the Lambda function)
will now include data according to spec
(https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws-lambda.md#elastic-load-balancer-elb).
Closes: #2901
> feat: support for Lambda function URL and ELB-triggered Lambdas

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- index.d.ts
- lib/agent.js
- test/agent.test.js
Fixes #2857.
This PR modifies `Agent.flush()` to return a `Promise` if no `callback` parameter is supplied to the function. This allows the method to be usable with the `await` keyword.
> feat: Make Agent.flush() return a Promise if no callback is passed as param

- CHANGELOG.asciidoc
- lib/instrumentation/modules/next/README.md
- lib/instrumentation/modules/next/dist/server/dev/next-dev-server.js
- lib/instrumentation/modules/next/dist/server/next-server.js
- test/instrumentation/modules/next/a-nextjs-app/package-lock.json
- test/instrumentation/modules/next/a-nextjs-app/package.json
- test/instrumentation/modules/next/next.test.js
Before this change internal changes in next@13.2.0 resulted in
transactions for Next.js API routes being `{method} unknown route`.
> fix: transaction name for Next.js API routes in next@13.2 was broken

- .github/workflows/lint.yml
- .github/workflows/test.yml
> ci: limit parallel GH Action test runs to try to avoid 429 errors on checkout

- .github/workflows/edge.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- examples/trace-redis.js
- test/types/index.ts
- Avoid test, lint, & edge CI workflows for .md and .asciidoc changes in
any subdir.
- Tweak the "types" test (npm run test:types) to catch the case of
`apm.flush()` with no callback returning a promise.
> test, ci: some small changes

- .github/workflows/test.yml
Earlier in #3180 we added max-parallel:15 as an attempted workaround
errors in the "actions/checkout@v2" (#3179). We also changed to
"actions/checkout@v3" in that change.
https://github.com/actions/checkout/issues/417 suggests that the update
to v3 is sufficient to fix, so let's get the parallelism back.
Refs: #3179
> ci: drop max-parallel for GH actions

- .github/workflows/test.yml
Abort old running builds when a new commit has been pushed to the existing Pull Request.
Save cost 
See https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
> action: abort builds when new commit

- .ci/updatecli.d/update-json-specs.yml
- .ci/updatecli.d/update-specs.yml
Updatecli pipelines were misconfigured hence the automation failed with
```
ACTIONS
========
WARNING: **Fallback** Please add a title to you configuration using the field 'title: <your pipeline>'
Pipeline "update-jsons-specs" failed
Skipping due to:
action stage:	"Title is too long (maximum is 256 characters)"
```
I also changed the PR title to be within the kind definition rather than within the specs.
> updatecli: fix title since it caused errors

- test/context-propagation-only.test.js
This failed in GH Actions CI:
not ok 16 captureError is fast (<5ms): 6.238244ms
> test: bump threshold to avoid spurious failure for possibly slow CI

- .ci/Jenkinsfile
Remove GitHub build message in Jenkins. CI has been migrated to GH actions, but the micro-benchmarking 
that will happen eventually.
Move filter `when` to happen earlier in the pipeline
GH build message might be re-done to support GitHub actions, but for now the GH command is not accurate. Hence it's removed.
> ci: remove notification and leftovers Jenkins

- .github/dependabot.yml
- .github/workflows/tav.yml
- .tav.yml
- CHANGELOG.asciidoc
- dev-utils/bitrot.js
- docs/api-opentelemetry.asciidoc
- docs/supported-technologies.asciidoc
- examples/opentelemetry-bridge/README.md
- examples/opentelemetry-bridge/package.json
- package-lock.json
- package.json
- test/opentelemetry-bridge/active-span-and-context-interop.test.js
- Bump the dep.
- Update examples/opentelemetry-bridge/ and get dependabot to handle this in
the future.
- Add an OTel section to the supported-technologies page.
- Add TAV testing of supported @opentelemetry/api versions.
- Add a test for the added `otel.trace.getActiveSpan()` in v1.2.0 of the API.
This is implemented in the API, so no need for *implementation* changes.
Supersedes: #3211
> feat: update @opentelemetry/api dep to 1.4.x for OpenTelemetry Bridge

- CHANGELOG.asciidoc
- lib/config.js
- test/central-config-enabled.test.js
The crash was with init of config.sanitizeFieldNamesRegExp in the central-config
code path. I've fixed that. Other updates:
- Updated config normalization of this var -- and similar config vars
that set a `${name}RegExp` array var -- initialize the RegExp array to empty
before populating it.
- Updated the tests to ensure we always add to "central-config-enabled.test.js"
whenever a new supported central config var is added.
- Updated central-config handling to try/catch and log.error instead of
*crashing* if there is an unexpected exception. Partially applied central
config isn't great, but it is better than having a DoS avenue where central
config can crash agents. For example:
{"log.level":"error",...,"remoteConf":{"sanitize_field_names":"password, …
> fix: receiving central config with `sanitize_field_names` would crash

- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/next/dist/server/next.js
- test/instrumentation/modules/next/a-nextjs-app/.tav.yml
> chore: limit Next.js instrumentation to <13.3.0 for now

- test/instrumentation/modules/aws-sdk/s3.test.js
It was found that running this test in Docker on mac -- e.g. by running `.ci/scripts/test.sh -b release 18` -- would fail. It would hit the set timeout for the `execFile` call. THis bumps the timeout and improves some logging output around that so it is easier to diagnose if it happens again.
> test: fix s3.test.js failure in Docker on macos due to timeout

- CONTRIBUTING.md
- docs/set-up.asciidoc
- typescript note for new v5 thing that is related
- update for release process being in GH Actions CI now
- renumber; note the relevant CI job for updating the 'current' published docs
> chore: potpourri (various small changes)

- .github/dependabot.yml
- test/instrumentation/azure-functions/azure-functions.test.js
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package.json
Just skip them until https://github.com/Azure/azure-functions-core-tools/issues/3335
is resolved.
This also bumps the azure-functions-core-tools dep and sets up
dependabot for that package.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3279
> test: workaround Azure Functions test failures on node >=18.x

- CHANGELOG.asciidoc
- lib/instrumentation/generic-span.js
- lib/instrumentation/modules/aws-sdk/s3.js
- test/instrumentation/modules/aws-sdk/s3.test.js
- test/integration/api-schema/apm-server-schema/span.json
Extract the parameters `Bucket` and `Key` from the instrumented requests to S3. Parameters are added into OTel attributes of the span following [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/90007a192ae8b06d40ee8c15f56256d69a330321/semantic_conventions/trace/instrumentation/aws-sdk.yml#L435)
Closes: #3150
> feat: add S3 Bucket and Key params in instrumentation

- .github/workflows/test.yml
To be able to trigger a workflow manually requires `on: workflow_dispatch`.
Let's do that for the main "test" workflow. Then we can:
```
gh workflow run test.yml
```
Eventually it might be nice to have input params to limit the node versions run, etc. but that can be done separately.
> ci: allow the 'test.yml' CI to be run manually

- .ci/tav.json
- .github/workflows/edge.yml
- .github/workflows/test.yml
- package.json
Node v20.0.0 is out (https://nodejs.org/en/blog/release/v20.0.0).   This updates to support that.
1. Change "engines" to just be `>=8.6.0` instead of explicitly listing all the even and current releases. This means that we'll avoid users getting this "npm WARN EBADENGINE" when a new release comes out:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'elastic-apm-node@3.44.1',
npm WARN EBADENGINE   required: { node: '^8.6.0 || 10 || 12 || 14 || 16 || 17 || 18 || 19' },
npm WARN EBADENGINE   current: { node: 'v20.0.0', npm: '9.6.4' }
npm WARN EBADENGINE }
```
at the cost of users of older elastic-apm-node versions perhaps assuming it supports all future Node.js releases.
In practice, I don't see any other npm packages using "engines" the way we have been doing. In …
> chore: update versions tested now that Node.js v20 is out

- lib/lambda.js
- lib/parsers.js
- test/lambda/transaction2.test.js
If the lambda handler object for an ELB- or API Gateway-triggered Lambda
invocation did not have a 'headers' field, then the Lambda
instrumentation would crash. I'm not sure how to get an event with no
'headers' field, but we should still be defensive here.
Fixes: https://github.com/elastic/apm-agent-nodejs/issues/3286
> fix: crash in Lambda handler with ELB or API Gateway event with no 'headers'

- .tav.yml
- package-lock.json
- package.json
Also update our dev dep to the current latest fastify release.
---
TAV tests for fastify v4.x started failing in the last day. E.g.: https://github.com/elastic/apm-agent-nodejs/actions/runs/4821512259/jobs/8587501136
<details>
<summary>test failure excerpt</summary>
```
node_tests_1  | > tav --quiet && (cd test/instrumentation/modules/next/a-nextjs-app && tav --quiet)
node_tests_1  | 
node_tests_1  | -- required packages ["fastify@4.17.0"]
node_tests_1  | -- installing ["fastify@4.17.0"]
node_tests_1  | -- running test "node test/instrumentation/modules/fastify/fastify.test.js" with fastify
node_tests_1  | -- running test "node test/instrumentation/modules/fastify/async-await.test.js" with fastify
node_tests_1  | -- running test "node …
```
> test: skip testing fastify 4.16.0 - 4.16.2 inclusive, they are broken releases

- CHANGELOG.asciidoc
- docs/lambda.asciidoc
- lib/lambda.js
- lib/noop-transport.js
- package-lock.json
- package.json
- test/_capturing_transport.js
- test/_mock_apm_server.js
- test/lambda/callbacks.test.js
- test/lambda/context.test.js
- test/lambda/github-issue-2709.test.js
- test/lambda/metadata.test.js
- test/lambda/metadata2.test.js
- test/lambda/mock/agent.js
- test/lambda/mock/transaction.js
- test/lambda/promises.test.js
- test/lambda/trace-context.test.js
- test/lambda/trans-setDefaultName.test.js
- test/lambda/transaction.test.js
- test/lambda/transaction2.test.js
- test/lambda/wrap-bundled-handler.test.js
- test/lambda/wrapper.test.js
When used with the Lambda extension >=v1.4.0, this results in
transactions being reported for Lambda timeout, uncaughtException,
and unhandledRejection.
Closes: #3136
Closes: #2379
- Drop AgentMock in tests and re-add support for `contextManager: patch` usage (see https://github.com/elastic/apm-agent-nodejs/pull/3285#issuecomment-1523908892)
- Consider a separate issue to look at replacing lambda-local usage for local testing with https://github.com/aws/aws-lambda-runtime-interface-emulator that Jonas has been looking at for the Java agent. It runs the AWS-provided emulator in a Docker container, allows using the real Lambda extension. It doesn't support the Logs API and not sure about the newer Telemetry API, so it isn't a perfect representation, but is a lot closer. Java agent PR: …
> feat: pre-register partial transactions in AWS Lambda

- .ci/scripts/test.sh
- .tav.yml
- dev-utils/aws-sdk-s3-client-tav-versions.sh
- docs/supported-technologies.asciidoc
- test/instrumentation/modules/@aws-sdk/client-s3.test.js
- test/instrumentation/modules/aws-sdk/s3.test.js
- Fix for bad selection of docker compose file to run tests on module `@aws-sdk/client-s3`. Test script was selecting the default one instead of using one with localstack.
- Bump the min supported client-s3 version to v3.15.0.
- Also a small fix in intake event sorting for tests 
Fixes: #3311
> test: fix @aws-sdk/client-s3 TAV test failures

- .tav.yml
The TAV tests were failing on fastify@3 with this error:
FastifyError [FST_ERR_PLUGIN_VERSION_MISMATCH]: fastify-plugin: @fastify/formbody - expected '4.x' fastify version, '3.29.5' is installed
The '@fastify/formbody' dep used in the sanitize-field-names/fastify.test.js
test file needs to match the fastify major version.
I am somewhat hesitant to add this change, because I think it might
make the fastify TAV tests much longer to run. Each version tested will
be doing an additional npm install step, which is slow.
---
<details>
<summary>Test failure log output</summary>
From https://github.com/elastic/apm-agent-nodejs/actions/runs/4871077219/jobs/8687616639
```
...
node_tests_1  | -- installing ["fastify@4.0.0"]
node_tests_1  | -- running test "node …
```
> test: fix fastify TAV test failures

- test/instrumentation/azure-functions/azure-functions.test.js
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package.json
This changes the workaround added in #3281.
The core issue with testing with node >=18.x was fixed in azure-functions-core-tools@4.0.5148
However, an issue testing with node v14.0.0 was introduced. We work around this by
just not testing with node v14.0.0. Testing with the latest node v14.x passes.
Refs: #3281
Fixes: #3279
> test: restore testing of Azure Functions on node >=18.x

- dev-utils/bitrot.js
- There are a couple more .tav.yml files for bitrot.js to include in its processing now.
- Also fix a regex to avoid this error:
```
% ./dev-utils/bitrot.js
bitrot: error: could not parse this table cell text from docs/supported-technologies.asciidoc: " https://www.npmjs.com/package/@opentelemetry/sdk-metrics[@opentelemetry/sdk-metrics]"
```
> chore: fix bitrot.js dev util for recent changes

- .ci/docker/node-edge-container/Dockerfile
- .ci/scripts/prepare-benchmarks-env.sh
We use nvm to install specific versions of node for "Edge tests"
and benchmarks. v0.34.0 was from 2019.
> chore: update nvm

- test/instrumentation/modules/fastify/fastify.test.js
`http.request(url, options, cb)` didn't exist until node v10.
---
This is to resolve this `test-tav (8, fastify)` test failure:
https://github.com/elastic/apm-agent-nodejs/actions/runs/4876452824/jobs/8700775255#step:3:158
```
node_tests_1  | -- required packages ["fastify@2.15.3"]
node_tests_1  | -- installing ["fastify@2.15.3"]
node_tests_1  | -- running test "node test/instrumentation/modules/fastify/fastify.test.js" with fastify
node_tests_1  | events.js:340
node_tests_1  |     throw new TypeError('"listener" argument must be a function');
node_tests_1  |     ^
node_tests_1  | 
node_tests_1  | TypeError: "listener" argument must be a function
node_tests_1  |     at ClientRequest.once (events.js:340:11)
node_tests_1  |     at new ClientRequest (_http_client.js:174:10)
node_tests_1  | …
```
> test: fix running fastify.test.js with node v8

- .github/workflows/edge.yml
Also add v21 because at some point there may be an RC
for a v21.0.0 release.
> test: drop node 14 from RC tests now that it is EOL

- package-lock.json
The package.json change in #3203 did not sync the package-lock file. The result is that `npm ci` fails:
```
% npm ci
npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Missing: @types/node-fetch@2.6.3 from lock file
npm ERR! Missing: form-data@3.0.1 from lock file
```
We only currently use `npm ci` for *releases*, not for other CI tests, so this isn't critical yet.
This is the first time I've made this error. If it happens at all frequently, we could add a CI check for this.
> chore: sync package-lock so 'npm ci' can work

- .ci/tav.json
- .tav.yml
- dev-utils/tav-versions-fastify.sh
- package-lock.json
- package.json
- test/instrumentation/modules/bluebird/bluebird.test.js
This tweaks the .tav.yml config for most TAV test matrix jobs that were
observed to be taking >20 minutes in CI recently. One job was taking
longer than 40 minutes and being aborted:
test-tav (14, bluebird,got,mimic-response)
- mimic-response: The agent instruments and will only ever instrument a
single version: v1.0.0. Therefore there is no need for to "test all
versions" as long as the regular non-TAV tests test that version. Lock
package.json to that version.
- bluebird, got, pg, mongodb-core, knex, tedious: Massively reduce the
number of versions tested when the latest release for a given major
version was more than 2-3 years ago.
- fastify, aws-sdk: Update the tested ranges to test the first, last,
and approximately 5 versions in between. (Added
./dev-utils/tav-versions-fastify.sh …
> test: reduce TAV test matrix for slowest jobs

- .tav.yml
- docs/supported-technologies.asciidoc
Our knex instrumentation only ever supported '>0.9.0', but the docs for
it accidentally stated '>=0.9.0'. Then in a recent change to .tav.yml we
actually started testing with '0.9.0', the result being that the tests
hang.  This change corrects and restates the range to be '>=0.10.0
<1.0.0'.
Dropping a documented supported version might in general be worthy of
changelog, docs, and even a breaking change. However, instrumenting
0.9.0 never worked and it was released 2015.
---
This fixes recent hangs in knex TAV tests, e.g.:
https://github.com/elastic/apm-agent-nodejs/actions/runs/4895356707
> fix: correct supported versions of knex to exclude 0.9.0

- .tav.yml
This is a temporary workaround for #3324.
Ref: https://github.com/elastic/apm-agent-nodejs/issues/3324
----
See https://github.com/elastic/apm-agent-nodejs/issues/3324#issuecomment-1539208381. This PR is that "option 3".
> test: workaround SQS test failures with aws-sdk >=2.1372.0 but not testing latest aws-sdk versions for now

- .ci/docker/docker-compose.yml
- .ci/tav.json
- .github/workflows/test.yml
- .tav.yml
- package-lock.json
- package.json
- test/docker-compose.yml
- bump the elasticsearch-canary dep to the latest version
- Drop TAV testing of elasticsearch-canary, because it doesn't work with
TAV: `tav` doesn't support ranges of *pre*releases (its internal usage
of node-semver does not use or support using `{includePrerelease: true}`, 
so our current .tav.yml block does not test the *latest*
canary release, only the exact version specified. Testing an older
canary release is pointless.
- Bump the Elasticsearch service version we use to the latest (8.7.1).
> chore, test: bump @elastic/elasticsearch-canary dep, drop its TAV testing, bump ES server version

- CHANGELOG.asciidoc
- lib/agent.js
- lib/config/config.js
- lib/config/normalizers.js
- lib/config/schema.js
- lib/instrumentation/generic-span.js
- lib/instrumentation/index.js
- lib/instrumentation/transaction.js
- test/agent.test.js
- test/central-config-enabled.test.js
- test/config.test.js
- test/config/normalizers.test.js
- test/instrumentation/modules/@elastic/elasticsearch.test.js
- test/instrumentation/modules/http/ignore-url-does-not-leak-trans.test.js
- test/traceContinuationStrategy.test.js
This is a continuation from a previous one (#3343) which aim for better organisation of the config logic without changing the behavior. What's don in this PR:
- move constant and defaults to `schema.js`. This file will contain in the future a schema object for easier config definitions (object shape to be discussed with \@trentm)
- moved last normalizers left in config file and added tests for them
- move `config.js` file in its own module alongside with `schema.js` and `normalizers.js` files
-  update `require` calls of the dependant modules
Relates to #3060
> chore: move config.js to its own module

- .github/dependabot.yml
Update `dependabot.yml` to ignore updates of `mimic-response` package. Reason behind this is the agent does not instrument any version higher than `1.0.0`
Sample dependabot PR trying to update the package https://github.com/elastic/apm-agent-nodejs/pull/3349
> chore: ignore mimic-response updates since they are not instrumented

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/tedious.js
- package-lock.json
- package.json
- test/config.test.js
- test/instrumentation/modules/tedious.test.js
Enable instrumentation of `tedious@16.x` and update `tav` tests according node versions supported by this new release.
Closes #3365
> chore: add tedious v16 in tav tests and agent checks

- docs/agent-api.asciidoc
- docs/log-correlation.asciidoc
- docs/opentracing.asciidoc
Some PRs cannot pass the docs generation check. The logs reveal som broken links
https://elasticsearch-ci.elastic.co/job/elastic+apm-agent-nodejs+pull-request+build-docs/2604/console
This PRs fix the broken links. Once passed there should be another similar PR for `3.x` branch
> docs: fix broken links to APM docs

- CHANGELOG.asciidoc
- docs/set-up.asciidoc
- lib/config/config.js
- package.json
- start-next.js
- start.js
This avoids the, arguably, surprise case of an additional APM agent
being started whenever a new Worker is created (see Node.js
`worker_thread` docs) if `node -r elastic-apm-node/start.js ...`
or `import 'elastic-apm-node/start.js'` is being used.
The former is especially surprising when using a loader with node v20:
node --experimental-loader=elastic-apm-node/loader.mjs -r elastic-apm-node/start.js ...
because Node v20 has moved loader processing to a Worker... so the
"start.js" is executed again in that worker. The visible side-effect
is that the logging preamble is printed twice.
This change isn't ideal because an explicit use of
import 'elastic-apm-node/start.js'
in TypeScript or ESM code for a worker does *not* start the APM agent.
That's a subtlety that we rely on documentation to …
> fix: do not start the Agent in "start.js" when in a Worker thread

- test/http-request.test.js
The test was using www.google.com:81 behaviour of firewalling requests
to that port such that establishing a *connection* would hang long
enough for the code under test to emit a "connectionTimeout" event.
Recently a number of tests on unrelated PRs were getting an ECONNREFUSED
instead.
See https://github.com/elastic/apm-agent-nodejs/issues/3313#issuecomment-1591932919 for an example.
This changes the test to not rely on an external server, but uses a
custom http.Agent that drops socket "connect" events, there by
simulating a connection hang and timeout.
> test: fix a flaky test that was relying on www.google.com:81 behaviour

- CHANGELOG.asciidoc
- lib/filters/sanitize-field-names.js
- lib/parsers.js
- test/parsers.test.js
- test/sanitize-field-names/main.test.js
This PR intends to finish the work started in https://github.com/elastic/apm-agent-nodejs/pull/3382 which has a fix to nor redact response headers. This one includes the fix on `redactObjectKeys` from the aforementioned PR and also changes the usage of it in `parser.js` file.
> fix: avoid redaction of response headers

- CHANGELOG.asciidoc
- lib/instrumentation/modules/http2.js
With distributed tracing incoming http2 requests have no parent ids. This behavior can be observed using grpc/js module which is using http2 transport.
The change extracts parent ids and state from the request headers the similar way as it is done for http/1.
This fixes https://github.com/elastic/apm-agent-nodejs/issues/1830
> fix: set the transaction parent for an incoming HTTP/2 request

- CHANGELOG.asciidoc
- lib/instrumentation/modules/http2.js
- test/instrumentation/modules/http2.test.js
This is a follow-up to the just-added HTTP/2 trace-context fix.
Refs: https://github.com/elastic/apm-agent-nodejs/pull/3451
> test: add a test of trace-context propagation for HTTP/2

- CHANGELOG.asciidoc
- lib/instrumentation/index.js
- lib/instrumentation/modules/@aws-sdk/smithy-client.js
- package-lock.json
- package.json
- test/config.test.js
In https://github.com/aws/aws-sdk-js-v3/pull/4873 aws-sdk v3 moved
@aws-sdk/smithy-client to @smithy/smithy-client. This will now
instrument either package name.
Fixes: https://github.com/elastic/apm-agent-nodejs/issues/3454
> fix: @aws-sdk/client-s3 instrumentation was broken with 3.363.0 release

- CHANGELOG.asciidoc
- lib/instrumentation/modules/@aws-sdk/client-s3.js
- package-lock.json
- package.json
- test/instrumentation/modules/@aws-sdk/client-s3.test.js
- test/instrumentation/modules/@aws-sdk/fixtures/use-client-s3.js
Closes: https://github.com/elastic/apm-agent-nodejs/issues/3464
> fix: `@aws-sdk/client-s3` instrumentation could cause `getSignedUrl` to crash

- lib/parsers.js
Since response.finished property is deprecated as of the newer node versions and another property i.e. response.writableEnded is currently used in place of it. So started supporting the response.writableEnded in transaction's context. Also, the change is backward compatible as the response.finished is not removed yet. 
Fixes: #3428
> fix: Started Supporting response.writableEnded in transaction's context.

- CHANGELOG.asciidoc
- lib/instrumentation/modules/tedious.js
tedious@16.2.0 changed the "name" it uses internally for RpcRequestPayload objects, from a string to the SQL Server-defined numeric identifiers. For example, to identify a "prepare":
```diff
- new RpcRequestPayload('sp_prepare', ...);
+ new RpcRequestPayload(Procedures.Sp_Prepare, ...);
```
where that `Procedures.Sp_Prepare` is a hardcoded 11, corresponding to https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-prepare-transact-sql
> fix: identifying the "sp_prepare" stored procedure changed for tedious@16.2.0

- .github/dependabot.yml
- dev-utils/gen-notice.sh
- examples/opentelemetry-metrics/package.json
- package-lock.json
- test/instrumentation/drop-fast-exit-spans.test.js
- test/opentelemetry-metrics/fixtures/package-lock.json
- test/opentelemetry-metrics/fixtures/package.json
This also adds the 0BSD license, used by the new tslib dep of
some OTel packages, to the list of known licenses for redist.
Obsoletes: #3478, #3483
> chore(deps): bump OpenTelemetry deps

- CHANGELOG.asciidoc
- lib/instrumentation/http-shared.js
Before this change, a call with a non-Function callback:
http.request(urlString, {}, 'this-is-not-a-cb-function')
would accidentally *not* fail because of the agent's instrumentation.
This is because the Node.js internal `isURL()` check changed such that
the result of `urlToHttpOptions(url)` passes `isURL()`.
> fix: shimming of `http.request()` with node v18.17.0 caused a subtle edge case breakage

- CHANGELOG.asciidoc
- package.json
This was noted here: https://github.com/elastic/apm-agent-nodejs/issues/1952#issuecomment-1652228018
> fix: the loader.mjs needed for ESM support was not included in the published package

- CHANGELOG4.asciidoc
- docs/upgrade-to-v4.asciidoc
- docs/upgrading.asciidoc
- lib/config/schema.js
- package.json
This starts an "Upgrade to 4.x" guide.
Bumping the min Node.js to 14.5.0 means we will be able to rely on
AsyncLocalStorage support.
Closes: https://github.com/elastic/apm-agent-nodejs/issues/2661
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3529
---
I know I'm mixing multiple things here. When starting the "Upgrade to" guide I wanted to not forget about where we have the min supported Node.js mentioned. If we decide we want the base 14 version to be 14.0.0 later, then we can change these two references back. We should discuss this in https://github.com/elastic/apm-agent-nodejs/issues/3529
> chore!: drop ELASTIC_APM_KUBERNETES_* envvars, bump min to node v14.5.0

- CHANGELOG4.asciidoc
- lib/instrumentation/span.js
- lib/instrumentation/transaction.js
Closes: https://github.com/elastic/apm-agent-nodejs/issues/2990
> chore!: drop "timer" option to startTransaction/startSpan

- CHANGELOG4.asciidoc
- lib/config/normalizers.js
- test/config.test.js
- test/config/normalizers.test.js
Add a warning when a duration config option does not have the units in its value.
Closes #2121
> chore: add warning on missing units for duration config options

- lib/config/normalizers.js
- lib/logging.js
Narrow a bit more the `Logger` typedef and move it to `logging.js` file
> chore: move logging types

- CHANGELOG.asciidoc
- lib/apm-client/http-apm-client/index.js
Refs: https://github.com/elastic/apm-nodejs-http-client/pull/182
---
In https://github.com/elastic/apm-agent-nodejs/pull/3507 the APM http-client was moved in this repo. At the time there were some remaining PRs and issues. One of them was https://github.com/elastic/apm-nodejs-http-client/pull/182 by @linjunpop to add some logging for 304, 403, and 404 responses from APM server when polling for central config.  This was adapted to this PR.  Changes from the original PR:
- I've reduced the log levels from debug to trace -- because 'trace' is the more typical "show the inner workings" log level being used in the http-client -- and warn to debug -- because [this part of the spec](https://github.com/elastic/apm/blob/main/specs/agents/configuration.md#dealing-with-errors) says:
> If the server …
> chore: add some logging for 3xx and 4xx responses polling for central config

- CHANGELOG4.asciidoc
- docs/agent-api.asciidoc
- docs/upgrade-to-v4.asciidoc
- index.d.ts
- lib/instrumentation/index.js
- lib/instrumentation/noop-transaction.js
- test/agent.test.js
This PR adds a check in the `agent.startTransaction()` API which looks if the agent has been started. If so it lets the method run otherwise returns a noop transaction (same a approach as OTel does).
Closes #2429
> chore: return noop transaction if agent not started

- CHANGELOG4.asciidoc
- docs/configuration.asciidoc
- docs/upgrade-to-v4.asciidoc
- lib/config/schema.js
- test/instrumentation/modules/http/outgoing.test.js
- test/instrumentation/modules/http2.test.js
- test/opentelemetry-bridge/fixtures.test.js
- test/tracecontext/tracecontext.test.js
As part of the config changes we're doing for next major version `4.x` we're disabling the elastic traceparent header by default. This PR does that change and also updates its tests & docs accordingly.
Closes #3510
> chore: set `useElasticTraceparentHeader`'s default value to `false`

- CHANGELOG4.asciidoc
- docs/upgrade-to-v4.asciidoc
- lib/config/normalizers.js
- test/config/normalizers.test.js
Spit out a warning whenever a size/bytes config option is given without its units. The log shows the value provided and the name of the option.
This PR also adds a warning log if the deprecated `errorMessagesMaxLength` is used.
Closes #2121 
Closes #2314
> chore: warn for missing units in config and for `errorMessagesMaxLength` usage

- CONTRIBUTING.md
- README.md
- dev-utils/push-docker.sh
- chore: simplify and doc push-docker.sh dev script
- some cleanup of CONTRIBUTING content
- docs: better document the release process, prepping for a coming 4.x new major
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2668
> docs: document active branches, prep the release process for having a maintenance branch

- package-lock.json
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
This PR keeps dependencies aligned with `main` branch so it would be easier to merge `dev/4.x` for the next major release.
> chore: bump deps from main

- CHANGELOG.asciidoc
- lib/instrumentation/span.js
- test/fixtures/json-specs/service_resource_inference.json
- test/service-resource-inference.test.js
This PR is conform  with the agreements of the discussion in https://github.com/elastic/apm/pull/700 which in summary says that default ports should be explicit in `serviceTarget.name` property of the span.
Updatecli workflows are failing because of that and JSON specs cannot be updated #3589
> chore: add default ports to `context.service.target.name` for exit HTTP spans 

- .ci/Makefile
- .github/workflows/release.yml
- CONTRIBUTING.md
- dev-utils/github-release.sh
This updates the 'npm publish' and 'github release' steps of the
release process to do the right thing for pre-releases. If a release
for a pre-release tag (one with hyphen) is started, this will now
properly avoid tagging the npm package and github release as
latest.
---
This should be backported to 3.x. It will make the github-release step smarter, so that we don't need to explicitly added `--latest=false` to the `gh release create ...` call; it will do the right thing automatically.
> chore: improve release tagging to support pre-releases

- test/instrumentation/modules/@aws-sdk/client-sns.test.js
In @aws-sdk/client-sns@3.181.0 the exception name/type changed.
https://github.com/aws/aws-sdk-js-v3/commit/384cbd7cbdbc0635d2dbff53b54d769ca80dabbb
---
The TAV tests were failing on older client-sns versions with:
```
node_tests_1  | not ok 19 error.exception.type
node_tests_1  |   ---
node_tests_1  |     operator: equal
node_tests_1  |     expected: 'NotFoundException'
node_tests_1  |     actual:   'NotFound'
node_tests_1  |     at: Object.checkApmServer (/app/test/instrumentation/modules/@aws-sdk/client-sns.test.js:226:9)
node_tests_1  |     stack: |-
node_tests_1  |       Error: error.exception.type
node_tests_1  |           at Test.assert [as _assert] (/app/node_modules/tape/lib/test.js:309:48)
node_tests_1  |           at Test.strictEqual (/app/node_modules/tape/lib/test.js:473:7) …
```
> fix: @aws-sdk/client-sns tav failure: NotFound error type

- test/instrumentation/modules/@aws-sdk/fixtures/use-client-sns.js
- test/instrumentation/modules/@aws-sdk/fixtures/use-client-sns.mjs
- test/instrumentation/modules/aws-sdk/sns.test.js
Reuse phone number defined on `aws-sdk` tests in `@aws-sdk/clilent-sns`.
> tests: use a known test phone for SNS v3 tests

- dev-utils/docker-compose.yml
- test/apm-client/http-apm-client/config.test.js
This test has been flaky in CI with node v20 and v21. I don't know
why the node version could matter here.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3313#issuecomment-1734291517
> test: add a lame delay in payloadLogFile test to avoid flaky failures

- docs/esm.asciidoc
In previous PRs to add support for:
- @aws-sdk/client-dynamodb
- @aws-sdk/client-sns
- @aws-sdk/client-sqs
I forgot to update the table. This PR amends it
> docs: add missing @aws-sdk clients on ESM support table

- test/instrumentation/drop-fast-exit-spans.test.js
- test/instrumentation/timer.test.js
- test/metrics/index.test.js
- test/testconsts.js
We should try to avoid timing-sensitive tests where possible, but
where that isn't possible and if experience shows that Windows CI
builds flake out frequently, then let's just skip them. Windows
isn't important enough.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3313
---
Review note: One of the changes here is mostly whitespace. Look at the diff with `?w=1`.
> test: skip some timing-sensitive tests on Windows CI to avoid flaky tests

- .github/workflows/addToProject.yml
Copied from the [java agent repo](https://github.com/elastic/apm-agent-java/blob/main/.github/workflows/addToProject.yml), with the team name replaced.
I replaced what was in this file already, assuming that it's no longer relevant. Please let me know if you still need what was in the file-- it adds an issue to the Old Agents project board.
> Add GitHub action to add issue to agents project board when milestoned

- .tav.yml
The TAV run had gotten way up to 79 versions tested, which
broke a 40min run time limit for some jobs.
> chore: reduce the number of aws-sdk versions in TAV tests

- CHANGELOG.asciidoc
- docs/nextjs.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/next.js
- lib/instrumentation/modules/next/dist/server/api-utils/node.js
- lib/instrumentation/modules/next/dist/server/dev/next-dev-server.js
- lib/instrumentation/modules/next/dist/server/next-server.js
- test/instrumentation/modules/next/a-nextjs-app/.tav.yml
next@11 does not get new releases, and only works on node 14 and 16,
which are EOL.  It is failing in our CI TAV tests and it is not worth
the time digging into older versions.
---
Currently `test-tav (next 14)` and `test-tav (next 16)`, i.e. the TAV tests of Next.js with Node v14 and v16, are failing with `next@11`. For example, from https://github.com/elastic/apm-agent-nodejs/actions/runs/6488426576/job/17620863144
```
...
node_tests_1  | -- installing ["react@^18.2.0","react-dom@^18.2.0","next@12.0.10"]
node_tests_1  | -- running test "node ../next.test.js" with next
node_tests_1  | -- required packages ["react@^17.0.2","react-dom@^17.0.2","next@11.1.4"]
node_tests_1  | -- installing ["react@^17.0.2","react-dom@^17.0.2","next@11.1.4"]
node_tests_1  | -- running test "node …
```
> chore!: drop next@11 support

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- index.d.ts
- lib/agent.js
- test/agent.test.js
For use by ecs-logging-nodejs packages for log correlation.
Refs: https://github.com/elastic/ecs-logging-nodejs/issues/121
Refs: #3195
> feat: apm.getServiceVersion(), apm.getServiceEnvironment(), apm.getServiceNodeName()

- .ci/tav.json
- .github/workflows/edge.yml
- .github/workflows/test.yml
Node.js v21 was first released on 2023-10-17. v22 nightlies should
start coming as well.
> chore: test with Node v21

- NOTICE.md
- lib/async-hooks-polyfill.js
- lib/instrumentation/modules/mongodb/lib/cmap/connection_pool.js
> fix: usage of AsyncResource.bind in mongodb instrumentation for Node.js v14 and earlier

- CHANGELOG.asciidoc
- lib/instrumentation/modules/mongodb.js
- test/instrumentation/modules/mongodb/fixtures/use-mongodb.js
- test/instrumentation/modules/mongodb/mongodb.test.js
This PR sets span outcome for `mongodb` commands. The tests realised (see related issue) reveals that a failed command triggers:
- a **CommandFailed** event with a property named `failure`
- a **CommandSucceeded** event with the a property named `reply`. The presence of a sub-property named `writeErrors` indicates the command failed.
Closes: #3182
> fix: set outcome for mongodb spans

- .ci/tav.json
- CHANGELOG.asciidoc
- test/instrumentation/modules/cassandra-driver/cassandra-driver.test.js
This PR simplifies the version ranges for testing `cassandra-driver`. Tests are going to be skipped if node version is <16.9
Refs:  #3629 
Closes: #3629
> chore: skip `cassandra-driver` tests if node <16.9

- .ci/scripts/test.sh
- .ci/scripts/windows/prepare-test.sh
- .ci/scripts/windows/stop-test.sh
- package.json
Move to docker v2 before v1 hits EOL. Basically it uses the new CLI options since the images we're using in CI (ubuntu-latest) already has [Docker V2](https://github.com/actions/runner-images/blob/cdbbd8a4455b608075cbf785bf0e969c13681890/images/linux/Ubuntu2204-Readme.md?plain=1#L71)
- `--log-level` option is now moved to docker command
- `--no-ansi` has been changed for `--ansi never` as suggested in the warning from Docker
Closes: #3306
> chore: change use docker v2 command

- .github/workflows/edge.yml
Change the trigger events for "edge" tests to make them run twice a week instead of in each commit to main.
Closes: #3338
> chore: run edge tests periodically

- .ci/updatecli.d/update-json-specs.yml
- .ci/updatecli.d/update-specs.yml
Add the original Pull Request that contains the changes in the specs to be in the description of the Pull Request created with the `updatecli` automation. This will help with track what APM Agents use it.
Given the updatecli and gh cli
When running
```bash
$ GIT_USER=foo \
GIT_EMAIL=1 \
GITHUB_TOKEN=*** \
updatecli apply --config .ci/updatecli.d/update-specs.yml --push=false --debug
```
Then
```
...
✔ content: found from file "https://github.com/elastic/apm-data/commit/main.patch":
From 5d596b8bb0cbf31aac8ea65e611a8d5d7d5b482d 
...
----
https://github.com/elastic/apm-data/pull/178
----
...
```
> updatecli: link to the original Pull Request

- .tav.yml
Limit the list of versions tested of `@aws-sdk/client-sqs` until `localstack` supports JSON responses in SQS seevice.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3716
> tests: skip tests @aws-sdk/client-sqs v3.446.0 & v3.447.0

- docs/configuration.asciidoc
- lib/agent.js
- lib/apm-client/apm-client.js
- lib/config/config.js
- lib/config/normalizers.js
- lib/config/schema.js
- lib/constants.js
- lib/instrumentation/generic-span.js
- lib/instrumentation/index.js
- lib/instrumentation/transaction.js
- test/agent.test.js
- test/config.test.js
- test/config/normalizers.test.js
PR to unify the way configuration options are defined and processed.
NOTE: this is a draft and so its description, do not review yet
> chore: unify configuration options definition

- .tav.yml
`aws-sdk@2.1491.0` module switched the protocol to "json" whch is not suported yet by `localstack`. Disabled the tests and re-enable when we have suport
Ref: #3719 
Closes: #3718
> tests: disable aws-sdk TAV tests for aws-sdk@2.1491.0 and up

- lib/config/config.js
- lib/config/schema.js
Follow up PR to refactor the configuration of the agent. this time we use the new schema to extract the data that is shown in the log preamble.
> chore: move preamble data function to config schema

- examples/trace-graphql.js
Credit to https://stackoverflow.com/a/71929390/14444044 for the fix. This was broken back when we upgraded from graphql@15 to graphql@16.
> fix: fix graphql example to work with graphql@16

- .github/dependabot.yml
Some of our devDeps can be logically grouped for updates. For example, there recently were two separate PRs to update apollo-server-* deps. Both PRs updated the other.
https://github.com/elastic/apm-agent-nodejs/pull/3738
https://github.com/elastic/apm-agent-nodejs/pull/3737
> chore: try to group some dependabot PRs for dev-deps

- .ci/tav.json
- test/opentelemetry-bridge/.tav.yml
- test/opentelemetry-metrics/fixtures/.tav.yml
- test/opentelemetry-metrics/fixtures/package.json
The TAV=@opentelemetry/sdk-metrics tests were failing because
test/opentelemetry-metrics/fixtures/package.json would need
to update that dep and exporter-prometheus in lockstep to avoid
a crash with two different versions of sdk-metrics installed.
I don't know how to coordinate that in TAV without labouriously
writing out all the version combos. Let's not do that now.
> test: drop TAV=@opentelemetry/sdk-metrics tests; TAV test with latest otel/api release

- .ci/docker/docker-compose-node-edge-test.yml
- .ci/docker/docker-compose-node-test.yml
- .ci/docker/docker-compose.yml
- .github/workflows/test.yml
- .tav.yml
- CHANGELOG.asciidoc
- lib/instrumentation/modules/@aws-sdk/client-sqs.js
- test/docker-compose.ci.yml
- test/docker-compose.yml
- test/instrumentation/modules/@aws-sdk/client-dynamodb.test.js
- test/instrumentation/modules/@aws-sdk/client-s3.test.js
- test/instrumentation/modules/@aws-sdk/client-sns.test.js
- test/instrumentation/modules/@aws-sdk/client-sqs.test.js
- test/instrumentation/modules/@aws-sdk/fixtures/use-client-sqs.js
- test/instrumentation/modules/aws-sdk/aws4-retries.test.js
- test/instrumentation/modules/aws-sdk/dynamodb.test.js
- test/instrumentation/modules/aws-sdk/fixtures/use-sqs.js
- test/instrumentation/modules/aws-sdk/s3.test.js
- test/instrumentation/modules/aws-sdk/sns.test.js
- test/instrumentation/modules/aws-sdk/sqs.test.js
Kudos to @peterabbott to find the issue and give context to start with the fix.
This PR adds a check when instrumenting `SendMessageBatch` command. The `entries` may not have the property `MessageAttributes` or it could be undefined breaking the propagation of traceContext headers.
We also leverage this fix to bump the version of local stack to `v3.0.0`. This new version supports the JSON protocol so we can re-enable tests for `@aws-sdk/client-sqs@3.446.0` and up.
Fixes: #3746
Closes: https://github.com/elastic/apm-agent-nodejs/issues/3719
~NOTE: we will re-enable test for other modules (`aws-sdk`, ..) in a follow up PR.~
> fix: error in @aws-sdk/client-sqs when SendMessageBatch entries have undefined attributes

- CHANGELOG.asciidoc
- package.json
The `node --experimental-default-type=module ...` option in Node
v20.10.0 means a default to "commonjs" isn't guaranteed.
> chore: explicitly mark this package as being of type="commonjs"

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- examples/trace-http-request.js
- lib/apm-client/apm-client.js
- lib/config/schema.js
Closes: #3759
---
I haven't added any tests here. FWIW there are existing tests in the *http-apm-client tests* for the `headers` config option that we are using here:
https://github.com/elastic/apm-agent-nodejs/blob/f590ef67c5b016520b844ce3a87164a4b7bbbfbd/test/apm-client/http-apm-client/config.test.js#L171-L194
I don't think there is much value in a test case that a `apmClientHeaders` value given to `apm.start()` makes it to the HttpApmClient() instance. For example, there isn't an equivalent test for these related config vars being passed through:
```js
rejectUnauthorized: conf.verifyServerCert,
serverTimeout: conf.serverTimeout * 1000,
```
> feat: add 'apmClientHeaders' config option for custom headers in APM server comms

- test/opentelemetry-metrics/fixtures.test.js
Letftover from a previous PR https://github.com/elastic/apm-agent-nodejs/pull/3755
Opentelemetry tests are also using undici so we need also to apply the same checks and skip if necessary.
> chore(undici): fix opentelemetry tests using undici

- lib/config/normalizers.js
- test/config.test.js
- test/config/config.test.js
- test/config/fixtures/use-agent.js
This PR refactors tests for:
- truthy/falsy values
- byte values
- -1 === Infinity values
- key/value pairs values
> chore: another batch of config tests being refactored

- .tav.yml
Learned about this bad version from OTel work.
> test: exclude bad '@aws-sdk/client-s3' version from tav tests

- test/config.test.js
- test/config/_json-utils.js
- test/config/config.test.js
- test/config/fixtures/use-agent.js
Another PR of the refactor config series. In this one:
- adds a missing test for key/value pair formats
- refactors the test for configurations which may hold regular expresions or wildcards
NOTE: a new file has been created to share replace & revive logic from JSON serialization and deserialization so test and fixture can transfer the right values of config and not loose them while stringifying them
> tests: refactor ignore config options tests (strings, regexp)

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- package-lock.json
- package.json
* Fix the dependency version range for `@elastic/ecs-pino-format`. (#3774)
* Change the log level of `Sending error to Elastic APM: ...` from `info` to
`debug`. There is no need to clutter the log output with this message. (#3748)
* Add the `apmClientHeaders` config option, to allow adding custom headers
to HTTP requests made to APM server by the APM agent. (#3759)
> release 4.3.0

- lib/activation-method.js
* Rename `apm-mutating-webhook` to `apm-k8s-attacher`
* The repository `apm-mutating-webhook` has been renamed to `apm-k8s-attacher`.
> chore: rename apm-mutating-webhook to apm-k8s-attacher

- .tav.yml
Not a particularly strong reason to do this, but I had this change sitting around and why not reduce the number of versions tested for faster TAV runs.
> chore: reduce number of redis@4 versions tested

- docs/set-up.asciidoc
This PR adds a link to the [APM attacher docs](https://www.elastic.co/guide/en/apm/attacher/current/apm-attacher.html). Copied from the [Java agent docs](https://github.com/elastic/apm-agent-java/blob/9da66286823e374bb7f9a4b877a48d0bad288790/docs/setup-attach-cli.asciidoc?plain=1#L12).
> Add link to APM attacher docs

- test/fixtures/json-specs/container_metadata_discovery.json
APM agent specs automatic sync
*Changeset*
* https://github.com/elastic/apm/commit/7ef63617e84081139e6b79b5006c035057dc42fb
* https://github.com/elastic/apm/pull/838
---
<Actions>
<action id="e7bafc0028f2ea75735351de467c80b970adf57e3b81e7c192ce52b5185822ef">
<h3>update-jsons-specs</h3>
<details id="51b51c35f35d91535097fd9395976b0be51211da0a6db79e48824e45a55d3156">
<summary>container_metadata_discovery.json</summary>
<p>1 file(s) updated with &#34;{\n  \&#34;cgroup_v1_underscores\&#34;: {\n    \&#34;files\&#34;: {\n      \&#34;/proc/self/cgroup\&#34;: [\n        \&#34;1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod90d81341_92de_11e7_8cf2_507b9d4141fa.slice/crio-2227daf62df6694645fee5df53c1f91271546a9560e8600a525690ae252b7f63.scope\&#34;\n      ]\n    },\n …
> [Automation] Update JSON specs

- CHANGELOG.asciidoc
- lib/activation-method.js
This is a the new favoured value for the envvar to indicate the apm-k8s-attacher
is being used. This still supports the old 'K8S' value, so the current release of
apm-k8s-attacher still works to properly set `activation_method`.
This should be backported.
Refs: https://github.com/elastic/apm-k8s-attacher/issues/91
> chore: support 'K8S_ATTACH' value for 'ELASTIC_APM_ACTIVATION_METHOD'

- lib/instrumentation/modules/koa-router.js
- lib/instrumentation/modules/mongodb.js
No functional change. However, I was confused for a little while that
'12.0.1' satisfies '>=5.2.0 <=12'. To me it isn't self-explanatory
that '<=12' is not the same as '<=12.0.0'.
> chore: clarify koa-router instrumentation range

- .ci/tav.json
- .github/workflows/test.yml
- CHANGELOG.asciidoc
- docs/esm.asciidoc
- test/testconsts.js
The iitm@1.7.3 update has resolved ESM instrumentation issues
with Node.js `^18.19.0 || >=20.2.0`.
Closes: #3784
Obsoletes: #3785
Refs: #3844
* * *
Note that the `@@toStringTag` issue impacting OTel doesn't impact us.
> fix: restore ESM testing with Node.js >=v18.19.0 and v20 and v21; clarify ESM Node.js version support

- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
- .github/workflows/test.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
> security: add permissions block to workflows

- .github/workflows/labeler.yml
Closes: https://github.com/elastic/apm-agent-nodejs/issues/3884
---
@david-luna I added perms to the wrong job in this workflow in https://github.com/elastic/apm-agent-nodejs/issues/3885.
> chore(ci): allow appropriate job in labeler workflow the write perms it needs

- lib/apm-client/http-apm-client/detect-hostname.js
In some cases, the PowerShell command that is used to detect the hostname will contain extra output before the hostname, e.g. the Microsoft copyright banner or any output that is printed in the PowerShell profiles. This causes invalid hostnames to be sent to the APM server.
This change ensures that the PowerShell output is limited only to the hostname.
> Fix incorrect hostname detection on Windows

- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- package-lock.json
- test/opentelemetry-bridge/.tav.yml
- test/opentelemetry-bridge/active-span-and-context-interop.test.js
- test/opentelemetry-bridge/package-lock.json
- test/opentelemetry-metrics/fixtures/.tav.yml
- test/opentelemetry-metrics/fixtures/package-lock.json
This uses "./dev-scripts/update-otel-deps.js", plus a manual edit of CHANGELOG.md.
Per https://github.com/elastic/apm-agent-nodejs/blob/trentm/otel-devs-update-202403/lib/opentelemetry-bridge/README.md#maintenance it is important for us to get a release out soonish after a new `@opentelemetry/api` version is released.
This obsoletes various dependabot updates of OTel deps.
> feat(otel-bridge): Update OpenTelemetry bridge to support @opentelemetry/api@1.8.0

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/apm-client/http-apm-client/detect-hostname.js
- lib/instrumentation/modules/tedious.js
- package-lock.json
- package.json
- test/instrumentation/modules/tedious.test.js
v17 release does not have major changes but just drops node versions support.
> feat: add support for tedious v17

- .github/workflows/labeler.yml
Earlier failed attempts were #3885 and #3886.
Fixes: #3884
* * *
I cribbed from the .NET agent (https://github.com/elastic/apm-agent-dotnet/pull/2300), which seems to be the only other one with "permissions:" in its labeler.yml so far... and theirs is working.
> chore: fix labeler.yml workflow permissions, again

- .github/community-label.yml
- .github/labeler-config.yml
- .github/workflows/labeler.yml
This is based on the more-recently updated labeler.yml in the apm-agent-dotnet repo.
- Switch away from Alex's old unmaintained issue-labeler action.
- Remove old debugging "Show team membership" step.
- Stop assigning the issue to project 454 (and old GH proj we no longer use)
- The hope is that these changes will also close #3884.
> chore: modernize issue/pull labeler action

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/tedious.js
- package-lock.json
- package.json
Tedious v18 was released recently (soon after v17 was released):
```
...
'16.6.0': '2023-10-21T13:29:58.966Z',
'16.6.1': '2023-11-19T21:21:36.654Z',
'16.7.0': '2024-01-31T21:53:12.246Z',
'16.7.1': '2024-02-09T15:03:06.383Z',
'17.0.0': '2024-02-11T17:27:44.577Z',
'18.0.0': '2024-02-28T21:21:55.511Z',
'18.1.0': '2024-03-02T10:47:28.209Z'
```
> feat: add support for tedious v18

- CHANGELOG.asciidoc
- lib/instrumentation/index.js
- test/instrumentation/modules/next/next.test.js
For some instrumentations we path module sub-paths (e.g. mongodb/lib/foo.js).
On Windows RITM returns modPath=mongodb\lib\foo.js. This change adds path
separator normalization so those values equate. Before this the module
patcher for that subpath was not applied.
* * *
This impacts instrumentation for Next.js, redis v4+, and part of the instrumentation for mongodb.
The reason this wasn't caught in testing is because:
- for other reasons testing Next.js on Windows is a limitation (process control things, see comments in the test file)
- redis and mongodb (among other) instrumentations are not tested on Windows because GH actions does not support "services" on Windows runners
> fix(next, redis, mongodb): ensure module sub-path RITM hooks are applied on Windows

- .github/workflows/labeler.yml
- use more reliable 'elastic' org membership test for triage, etc. labels
- bypass 'action-add-labels' action to avoid another dep
- drop agent-nodejs label that we no longer require for use in GH projects
Fixes: https://github.com/elastic/apm-agent-nodejs/issues/3884
* * *
The `actions/github-script@v7` usage is from apm-agent-java.
The dropping `agent-nodejs` label adding is pending on team discussion (https://elastic.slack.com/archives/C9A6ANR5Y/p1710809441508399).
> ci: fix/refactor labeler workflow

- .ci/docker/docker-compose-all.yml
- .ci/docker/docker-compose-edge.yml
- .ci/docker/docker-compose-kafka.yml
- .ci/docker/docker-compose.yml
- test/docker-compose.yml
This adds the require zookeeper volume refs.
Closes: https://github.com/elastic/apm-agent-nodejs/issues/3922
> ci: fix 'test-nightly' job in 'edge' CI workflow

- CHANGELOG.asciidoc
- lib/instrumentation/express-utils.js
- test/instrumentation/express-utils.test.js
Host header may contain invalid characters making the agent throw an exception and stoping the app. Agent should not throw and let the app deal with the wrong requerst.
Closes: #3874
> fix: handle invalid chars in host header

- .tav.yml
- test/instrumentation/modules/tedious.test.js
This was necessitated by a transitive dep of tedious breaking support
for Node.js versions earlier than 16.
Closes: #3926
> test(tedious): stop testing some older tedious versions with Node.js 14

- .ci/docker/docker-compose.yml
- test/docker-compose.yml
Running 'npm test' outside of CI will start all test services in docker
*then wait for them to all be healthy*. Without a healthcheck for zk
the 'wait_for_healthy' in test/script/run_tests.sh would never pass.
> test: add healthcheck for zookeeper test service so 'npm test' works outside of CI

- .ci/docker/docker-compose.yml
- test/docker-compose.yml
Specifying the mssql image platform is necessary on *arm* Macs
because the mssql Docker image only provides binaries for the
amd64 architecture. My understanding is that Rosetta emulation
on recent macOS supports running the amd binary just fine.
> test: fix 'npm test' on Apple silicon Macs

- package.json
there was a internal conversation about changing the `author` field. This is my proposal to add info about the observability team within the `package.json` file
> chore: add contributors to package.json

- CONTRIBUTING.md
Necessitated by loss of the ability to (force) push directly to the "4.x" branch.
> doc: update release process to use a PR for updating the docs-build branch

- CHANGELOG.asciidoc
- lib/instrumentation/modules/undici.js
undici TAV tests started failing recently: https://github.com/elastic/apm-agent-nodejs/actions/runs/8606452765
The issue is a bug in undici@6.11.0 that removed an API used by our instrumentation.
That bug was discussed here: https://github.com/nodejs/undici/issues/3043
And it was fixed in undici@6.11.1 shortly after.
> fix(undici): cope with undici@6.11.0 bug that removed req.addHeader

- CHANGELOG.asciidoc
- lib/instrumentation/modules/undici.js
- test/instrumentation/modules/undici/undici.test.js
... because Elasticsearch borks on these requests. This case should only be
possible in a weird case like having two APM agents active.
Fixes: #3964
* * * 
We might want to add a similar guard to OTel's undici instr as well.
> fix(undici): avoid possible duplicate 'traceparent' header on instrumented HTTP requests

- dev-utils/make-distribution.sh
Fixes: #3968
* * *
- Once this is in, then move the v4.5.1 tag to that commit and ensure the release works.
> fix(release): ensure our npm options are used during make-distribution

- CHANGELOG.asciidoc
- package-lock.json
- package.json
v4.5.1 (https://github.com/elastic/apm-agent-nodejs/pull/3966) was abortive because the release process failed and tags are protected (https://github.com/elastic/apm-agent-nodejs/pull/3969#issuecomment-2050685857).
> release 4.5.2

- CHANGELOG.asciidoc
- dev-utils/make-distribution.sh
- package-lock.json
- package.json
- fix(release): ensure our npm options are used during make-distribution (#3969)
- release 4.5.2 (#3970)
> docs: update 4.x branch for v4.5.2 release

- CONTRIBUTING.md
- dev-utils/update-4x-branch.sh
Now that we need to use a PR to update the 4.x branch for a release, I've added a script to help with this.
This script was used for https://github.com/elastic/apm-agent-nodejs/pull/3971 for the v4.5.2 release.
> chore: add a script for, and update the release process for updating the 4.x docs branch

- CHANGELOG.asciidoc
- lib/instrumentation/modules/kafkajs.js
- test/instrumentation/modules/kafkajs/fixtures/use-kafkajs-each-message.js
- test/instrumentation/modules/kafkajs/kafkajs.test.js
The `kafkajs` instrumentation was calling `toString` method for all of the messages received. This approach wasn't taking in consideration `tombstone messages` which is defines as
> A message with a key and a null payload will be treated as a delete from the log. Such a record is sometimes referred to as a _tombstone_.
Ref: https://kafka.apache.org/documentation/#design_compactionbasics
Fixes: #3980
> fix(kafkajs): handle kafka tombstone messages

- .ci/tav.json
- .github/workflows/edge.yml
- .github/workflows/test.yml
Now that v22 is out add it and drop v21 testing.
https://github.com/nodejs/release#release-schedule
> test: test with Node.js v22

- .github/workflows/release.yml
Use https://github.com/docker/metadata-action/tree/8e5442c4ef9f78752691e2d8f8d19755c6f78e81/?tab=readme-ov-file#semver to get the tag version and [open-container](https://github.com/opencontainers/image-spec/blob/main/annotations.md) labels.
Use sha commit for the GitHub action related to docker.
See https://github.com/elastic/apm-agent-nodejs/actions/runs/8878357355, didn't run with `push`
```
Run docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
with:
context: .
push: false
tags: docker.elastic.co/observability/apm-agent-nodejs:test-latest
labels: org.opencontainers.image.created=[2](https://github.com/elastic/apm-agent-nodejs/actions/runs/8878357355/job/24373834641#step:9:2)024-04-29T12:16:2[3](https://github.com/elastic/apm-agent-nodejs/actions/runs/8878357355/job/24373 …
```
> ci: use docker/metadata-action to gather tags/labels

- CHANGELOG.asciidoc
- package-lock.json
- package.json
This is a release to get a fix for https://github.com/elastic/apm-agent-nodejs/issues/4006 out.
> release 4.5.4

- CHANGELOG.asciidoc
This is asciidoc, not markdown.
> docs: fix markup in changelog

- .github/workflows/release.yml
- Dockerfile.wolfi
Release two flavours of Docker images:
- the one we always do
- the one based on [Wolfi](https://www.chainguard.dev/unchained/introducing-wolfi-the-first-linux-un-distro) from [Chainguard](https://edu.chainguard.dev/chainguard/chainguard-images/overview/) 
Please note that we are going to preserve the current `Dockerfile`, so that users will still be able to build their own custom images based on `Alpine`: this is needed because `docker.elastic.co/wolfi/chainguard-base` is not a public base image, so docker build would fail for unauthenticated users.
I refactored the release workflow to have three different jobs that run sequentially:
- release job, as usual
- docker build - so it can use the matrix format for `Dockerfile` and `Dockerfile.wolfi`
- notification - so if any of the above …
> ci: build and push Docker image based on Chainguard base image

- .ci/Makefile
- CHANGELOG.asciidoc
> fix: mark published AWS Lambda layers as supporting 'nodejs20.x' runtime

- .ci/updatecli/updatecli.d/update-json-specs.yml
- .ci/updatecli/updatecli.d/update-specs.yml
- .github/workflows/updatecli.yml
Use oblt-actions with GitHub secrets.
No need to use Vault secrets path
> ci: use updatecli with GitHub secrets

- CHANGELOG.asciidoc
- lib/instrumentation/modules/@smithy/smithy-client.js
Recently @aws-sdk/client-* releases started using v3 of smithy/smithy-client.
This updates our instr to allow patching v3.
> fix: patch @smithy/smithy-client@3 for release @aws-sdk/client-* releases

- .github/workflows/release.yml
This had been done for other uses in this workflow in #4025,
and then this additional usage was added a bit later in #4005.
> chore(release): switch to actions/attest-build-provenance

- package-lock.json
Bump transitive agentkeepalive dep to v3.5.3 that avoids using
the now-removed 'util._extend'.
Fixes: #4075
---
This was generated via `npm update agentkeepalive`.
The other package-lock changes: I'm not sure exactly why those are there. The entries being removed here were added with a recent bump of the fastify devDep. I see the same package-lock changes in another draft PR I have. I think it is harmless.
> chore, test: fix elasticsearch instr test with Node.js v23

- .github/workflows/release.yml
use GitHub secrets for slack and AWS publishing.
Plan to use keyless in a follow-up
> ci(github-secrets): slack and aws lambda publish

- docs/span-api.asciidoc
- docs/supported-technologies.asciidoc
- docs/transaction-api.asciidoc
- index.d.ts
- lib/instrumentation/generic-span.js
- lib/instrumentation/modules/@aws-sdk/client-sqs.js
- lib/instrumentation/modules/aws-sdk/sqs.js
- lib/instrumentation/modules/kafkajs.js
- lib/lambda.js
- lib/opentelemetry-bridge/OTelBridgeNonRecordingSpan.js
- lib/opentelemetry-bridge/OTelSpan.js
- package-lock.json
- test/instrumentation/span.test.js
- test/instrumentation/transaction.test.js
- test/opentelemetry-bridge/.tav.yml
- test/opentelemetry-bridge/OTelBridgeNonRecordingSpan.test.js
- test/opentelemetry-bridge/fixtures.test.js
- test/opentelemetry-bridge/fixtures/interface-span.js
- test/opentelemetry-metrics/fixtures/.tav.yml
- test/opentelemetry-metrics/fixtures/package-lock.json
- test/types/index.ts
This also updates a few places for the new otel/api v1.9.0.
Refs: #4071 (the dependabot update doesn't get everything)
Refs: #4070
Refs: #4069
Refs: #4077 (a separate issue for this other new feature in otel/api@1.9.0)
Refs: https://github.com/elastic/apm/pull/870
---
`@opentelemetry/api@1.9.0` added support for `span.addLink()` and `span.addLinks()`.
This updates our OTel bridge tracing support to work with those APIs.
This also adds public `addLink()` and `addLinks()` equivalent methods on our Transaction and Span APIs.
Note that the span links support still has limitations: only trace_id and span_id are sent/stored (no span link attributes, no 'tracestate' in the span context).
I created a separate issue for the other feature added to otel/api@1.9.0.
> feat: support OTel span.addLink, span.addLinks; add similar APIs to the APM agent API

- CHANGELOG.asciidoc
- docs/span-api.asciidoc
- docs/transaction-api.asciidoc
- package-lock.json
- package.json
A release to get otel/api@1.9.0 support for the OTel Bridge. Without a release a user of `@opentelemetry/api@1.9.0` would get no-op implementations with our bridge's supplied providers implementing the older 1.8.0 version.
> release 4.7.0

- test/instrumentation/modules/hapi/hapi.test.js
- test/instrumentation/modules/next/a-nextjs-app/pages/a-throw-in-page-handler.js
- test/instrumentation/modules/next/next.test.js
- test/opentelemetry-metrics/fixtures.test.js
- test/opentelemetry-metrics/fixtures/use-just-otel-sdk.js
- test/opentelemetry-metrics/fixtures/use-otel-api-with-registered-meter-provider.js
A number of TAV tests started failing in GH Actions recently, starting on Jun 12, 2024 (see x's at https://github.com/elastic/apm-agent-nodejs/commits/main/).
For example https://github.com/elastic/apm-agent-nodejs/actions/runs/9503644674
The failures were *all* of this basic form:
```
node_tests-1  | -- running test "node test/instrumentation/modules/hapi/hapi.test.js" with @hapi/hapi (env: {})
node_tests-1  | node:events:497
node_tests-1  |       throw er; // Unhandled 'error' event
node_tests-1  |       ^
node_tests-1  | 
node_tests-1  | Error: connect ECONNREFUSED 127.0.0.1:33547
node_tests-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
node_tests-1  | Emitted 'error' event on ClientRequest instance at:
node_tests-1  |     at Socket.socketErrorListener …
```
> test: fix 'localhost' ipv4 vs. ipv6 test failures in GH actions TAV tests

- dev-utils/update-4x-branch.sh
I noticed that the 'gh pr ...' command did not create a PR filled with
the intended title. That was due to the '--fill' option that we don't want.
This also adds a better body, so that the release PR will always get a
link-back from the docs update PR.
> chore: improve update-4x-branch.sh script instructions for the docs-update PR

- .github/workflows/release.yml
Use keyless authentication (OIDC) instead of credentials to authenticate with elastic-observability-prod in the release workflow
> Use keyless authentication in release

- .tav.yml
esclient v8.11.0's min support Node.js is v18
Refs: https://github.com/elastic/elasticsearch-js/pull/2055
> test: update Node.js versions with which we test the esclient

- package-lock.json
- test/opentelemetry-metrics/fixtures/package-lock.json
This obsoletes the few separate dependabot updates for these right now.
> chore(deps): update otel deps

- lib/instrumentation/noop-transaction.js
In the context of an AWS Lambda function wrapped with apm.lambda, if the APM agent hasn’t started yet, it will raise error like `TypeError: trans.setFaas is not a function`
> fix: add missing methods to noop-transaction

- .ci/docker/docker-compose.yml
- test/docker-compose.yml
The latest mcr.microsoft.com/mssql/server release (CU14) moves the sqlcmd
install location, breaking our healthcheck. Just updating the path hits
a different error. As a workaround, lets pin to the working mssql/server
docker image for CI.
Note that this docker compose file is used for TAV tests.
I'm not sure if hte mssql/server image used by GH Actions' mssql
'service' will be affected at some point as well.
Closes: https://github.com/elastic/apm-agent-nodejs/issues/4147
> ci: lock on older mssql/server Docker image to avoid healthcheck breakage

- CHANGELOG.asciidoc
- package-lock.json
- package.json
The import-in-the-middle update is worth a bug fix release.
It fixes a crash when using vue with ESM code.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/4143
> release 4.7.1

- .ci/docker/docker-compose.yml
- .github/workflows/test.yml
- examples/trace-tedious.js
- test/docker-compose.yml
- test/instrumentation/modules/tedious.test.js
- move to the latest CU (cumulative update) of SQLServer 2022
(which involves updating the healthcheck for internal changes)
- use MSSQL_SA_PASSWORD rather than the long since deprecated SA_PASSWORD
Refs: https://github.com/elastic/apm-agent-nodejs/issues/4147
---
A working healthcheck for the latest mssql/server image was provided by:
https://github.com/microsoft/mssql-docker/issues/892#issuecomment-2248045546
> test: modernize our mssql/server Docker image usage

- lib/instrumentation/modules/@aws-sdk/client-sns.js
- test/instrumentation/modules/@aws-sdk/client-sns.test.js
- test/instrumentation/modules/@aws-sdk/fixtures/use-client-sns.js
Before this change, instrumentation of `@aws-sdk/client-sns` would *crash*
if there wasn't a current transaction.
Fixes: #4138
> fix(@aws-sdk/client-sns): do not crash if there is no current transaction

- test/docker-compose.yml
For some testing (GitHub Actions test.yml is separate), we use test/docker-compose.yml
for test services. This standardizes on this healthcheck timing:
interval: 1s
timeout: 10s
retries: 30
The previous 'interval: 30s' for some services was unnecessarily slow.
It means the first healthcheck would always wait that long and one would
be waiting doing nothing. It is possibel with this change we will have a
very slow service not come up in time. If so, then we can increase the
retries or interval. Preceding values were willy-nilly.
> test: standardize on shorter healthcheck interval in docker-compose test config

- lib/config/schema.js
- test/start/file/elastic-apm-node.js
- test/start/file/test.test.js
This allows a "false" boolean value to override a "true" default value when loading the options via the elastic-apm-node.js config file
Fixes: #4112
Closes: #4112
> fix: allow file config to override true default values

- CHANGELOG.asciidoc
Updating the changelog with the last fixes merged into main.
> chore: update changelog

- .ci/Makefile
Before this change an errant AWS_REGION envvar would override the
AWS_DEFAULT_REGION envvar. Explcitly using --region=... will win.
Fixes: #4171
Refs: #4109
> fix(release): ensure we publish Lambda Layers to the intended AWS region

- CHANGELOG.asciidoc
- package-lock.json
- package.json
Highlights:
- wrapping of core Node.js modules loaded via  (#4160)
- fix publishing of the AWS Lambda Layer to all AWS regions (#4171)
Checklist:
> release 4.7.2

- .github/workflows/release.yml
We don't need vault secrets but GitHub secrets.
We are now using a service machine account that we own/control when to rotate the secrets.
> github-actions: use github secrets

- CHANGELOG.asciidoc
- package-lock.json
- package.json
This should fix the issue being hit here:
https://github.com/elastic/apm-agent-nodejs/issues/4143#issuecomment-2257585825
> release 4.7.3

- TESTING.md
- test/docker-compose.yml
- test/script/docker/run_tests.sh
- test/script/run_tests.sh
Two issues with testing locally on my dev laptop:
1. `docker-compose` (i.e. Docker Compose v1) is dead and, in some versions, now gone. Time for `docker compose ...` (i.e. v2): https://docs.docker.com/compose/migrate/
```
% npm test
> elastic-apm-node@4.7.3 test
> ./test/script/run_tests.sh
./test/script/run_tests.sh: line 93: docker-compose: command not found
```
2. The mysql image has no layer for ARM, i.e. that natively runs on Apple Silicon.
```
% npm test
> elastic-apm-node@4.7.3 test
> ./test/script/run_tests.sh
[+] Running 0/1
⠼ mysql Pulling …
```
> test: fix two issues running tests locally

- .tav.yml
- CHANGELOG.asciidoc
- lib/instrumentation/modules/tedious.js
- package-lock.json
- package.json
- test/instrumentation/modules/tedious.test.js
> feat: add support for `tedious` v19

- .tav.yml
We don't yet support instrumenting express@5. 5.0.0 was recently released.
Our TAV config was including express@5 in tests.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/4238
> test(express): drop express@5 from TAV tests

- test/spanStackTraceMinDuration.test.js
This test case has been occasionally fail in CI recently.
This bumps the timing to make a small timing issue less likely to
cause the test to fail.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3313#issuecomment-2382538762
> test: attempted fix of flaky 'span slower than configured spanStackTraceMinDuration' test

- CHANGELOG.asciidoc
- package-lock.json
- package.json
This should fix the sec issue [CVE-2024-47764](https://github.com/advisories/GHSA-pxg6-pf52-xh8x)
ref: https://github.com/elastic/apm-dev/issues/1083
> release 4.8.0

- .github/workflows/test.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been archived in favor of 
https://github.com/elastic/oblt-actions.
Requires https://github.com/elastic/oblt-actions/pull/16 to be merged.
If there are any questions, please reach out to the @elastic/observablt-ci
> github-action: use elastic/oblt-actions/check-dependent-jobs

- CHANGELOG.asciidoc
- lib/instrumentation/index.js
- lib/lambda.js
- test/lambda/fixtures/foo.js
- test/lambda/fixtures/handlermodule.cjs
- test/lambda/wrapper.test.js
Before this if the _HANDLER string had a '.' in the module path (the
part before the 'moduleName.functionExport'), then the parsing of
that handler string would silently produce bogus 'lambdaHandlerInfo'
that would result in a RITM path that would never actually get loaded,
hence no Lambda instrumentation.
Fixes: #4293
> fix(lambda): fix lambda instr to work with a '.' in the handler module path

- CHANGELOG.asciidoc
- lib/agent.js
- lib/apm-client/apm-client.js
- lib/config/config.js
- lib/instrumentation/index.js
- lib/instrumentation/transaction.js
This adds a periodic (once per minute) dump of effective config changes
from the default, once per minute at 'trace'-level.
This also fixes an issue where a central-config update of `log_level`
did not update the *child* logger on the APM client. Only the agent's
own logger's level was updated.
This adds trans.sampled to some debug logging output.
---
@david-luna Note this is targeting 3.x. If this looks reasonable, I'll adapt the patch for "main" as well.
> chore: better logging for config state and transaction sampling

- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
- .github/workflows/test.yml
- CHANGELOG.asciidoc
- Dockerfile.wolfi
- examples/nextjs/package.json
- lib/instrumentation/index.js
- lib/lambda.js
- package-lock.json
- package.json
- test/lambda/fixtures/foo.js
- test/lambda/fixtures/handlermodule.cjs
- test/lambda/wrapper.test.js
- test/opentelemetry-metrics/fixtures/package-lock.json
- test/opentelemetry-metrics/fixtures/package.json
> docs: update 4.x branch for v4.8.1 release

- .github/workflows/release.yml
Fixes: https://github.com/elastic/apm-agent-nodejs/issues/4307
> fix: ensure 3.x releases publish to npm with 'latest-3' dist-tag

- .github/workflows/microbenchmark.yml
- .github/workflows/release.yml
dependabot does not bump version for githubactions using semver and 'v1', see https://github.com/dependabot/dependabot-core/issues/10924
> github-actions: use v1 for the oblt-actions

- .ci/updatecli/values.d/scm.yml
- .ci/updatecli/values.d/update-compose.yml
- .github/workflows/updatecli.yml
- updatecli-compose.yaml
* Use the latest updatecli version for now
* Update policies for the specs/jsons
* Enable updatecli policies autodiscovery (but use the previous latest one, so I can test this PR)
Otherwise, https://github.com/elastic/apm-agent-go/pull/1671 won't work
🐔 🥚  since https://github.com/updatecli/updatecli/releases/tag/v0.86.0
> Sources were always executed before conditions and then targets.
With this change, sources, conditions, and targets can now depend on any other resource type to allow an advanced update scenario.
And there are errors like
```
target: target#agent-json-specs
-----------------------
**Dry Run enabled**
The shell 🐚 command "/bin/sh /tmp/updatecli/bin/68b2939c124c411192667268d8f6edefbaa79f085494796eb8122c21afdb37bf.sh" exited on error (exit code 2) with the following …
```
> ci(updatecli): add policies autodiscovery, bump updatecli version and specs/jsons policies

- .github/workflows/updatecli.yml
- .tool-versions
- updatecli-compose.yaml
Use `.tool-versions` to pin the [updatecli](https://www.updatecli.io/docs/prologue/quick-start/) version.
Enable auto-bump
> ci: pin updatecli version using .tool-versions and autobump

- CHANGELOG.asciidoc
- package-lock.json
- package.json
Release with:
- add support for `undici` v7. #4336
- fix to support a internal refactor in `mysql2` v3.11.5. #4334
- fix for truncate errors in http-client #4359
> release 4.9.0

- CHANGELOG.asciidoc
- lib/agent.js
- lib/apm-client/apm-client.js
- lib/config/config.js
- lib/instrumentation/index.js
- lib/instrumentation/transaction.js
- package-lock.json
- package.json
This cherry-picks an improvement from the 3.x branch:
> This adds a periodic (once per minute) dump of effective config changes
> from the default, once per minute at 'trace'-level.
>
> This also fixes an issue where a central-config update of `log_level`
> did not update the *child* logger on the APM client. Only the agent's
> own logger's level was updated.
>
> This adds trans.sampled to some debug logging output.
and prepares for a v4.10.0 release.
Refs: #4291 (equivalent on 3.x branch)
> better logging for config state; release 4.10.0

- package-lock.json
This is a workaround for `npm ci` failing with:
Invalid: lock file's process-warning@4.0.0 does not satisfy process-warning@4.0.1
Closes: #4396
---
Until this is merged we cannot do dev for this repo.
> fix: get 'npm ci' working again

- .ci/updatecli/values.d/scm.yml
- .ci/updatecli/values.d/update-compose.yml
- .github/workflows/labeler.yml
- .github/workflows/microbenchmark.yml
- .github/workflows/release.yml
- .github/workflows/updatecli.yml
- .tav.yml
- .tool-versions
- CHANGELOG.asciidoc
- Dockerfile.wolfi
- docs/supported-technologies.asciidoc
- lib/agent.js
- lib/apm-client/apm-client.js
- lib/apm-client/http-apm-client/index.js
- lib/config/config.js
- lib/instrumentation/index.js
- lib/instrumentation/modules/mysql2.js
- lib/instrumentation/transaction.js
- package-lock.json
- package.json
- test/_is_undici_incompat.js
- test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
- test/opentelemetry-metrics/fixtures/package-lock.json
- updatecli-compose.yaml
Refs: #4386 (release PR)
---
Note this also updates for the v4.9.0 release, because the 4.x branch wasn't updated for that release.
> docs: update 4.x branch for v4.10.0 release

- .tav.yml
- CHANGELOG.asciidoc
- lib/instrumentation/modules/@smithy/smithy-client.js
v3.723.0 and later of some aws-sdk-js v3 clients updated to use `@smithy/smithy-client@4`
which is part of what is instrumented.
---
TAV tests for client-s3, client-sns, and client-sqs started failing with the 3.723.0 version released earlier today.
E.g.: https://github.com/elastic/apm-agent-nodejs/actions/runs/12641762762/job/35224835256
```
$ npm info @aws-sdk/client-s3 time
...
'3.716.0': '2024-12-19T20:06:49.540Z',
'3.717.0': '2024-12-20T19:58:02.159Z',
'3.721.0': '2025-01-02T20:07:43.217Z',
'3.722.0': '2025-01-03T19:56:43.048Z',
'3.723.0': '2025-01-06T20:58:42.380Z'
```
The interesting part of the diff of those versions:
```diff
-        "@smithy/core": "^2.5.5",
-        "@smithy/smithy-client": "^3.5.1",
+        "@smithy/core": "^3.0.0",
+        "@smithy/smithy-client": "^4.0.0", …
```
> fix: instrumentation of `@aws-sdk/client-*` v3.723.0 and later now works

- dev-utils/update-4x-branch.sh
./dev-utils/update-4x-branch.sh [TARGTAG [LASTTAG]]
Passing TARGTAG is needed when the HEAD commit is no longer the tagged
release commit. Passing LASTTAG is necessary if the 4.x branch wasn't
updated for a particular release.
---
I needed these improvements for https://github.com/elastic/apm-agent-nodejs/pull/4399
> chore: support passing relevant release tags to update-4x-branch.sh as arguments

- .github/workflows/labeler.yml
E.g. note how https://github.com/elastic/apm-agent-nodejs/pull/4402 was so labeled and should not have been.
> chore(labeler): don't label PRs from our renovate bot as a community PR

- .github/workflows/addToProject.yml
- .github/workflows/edge.yml
- .github/workflows/labeler.yml
- .github/workflows/microbenchmark.yml
- .github/workflows/release.yml
- .github/workflows/slack.yml
- .github/workflows/tav-command.yml
- .github/workflows/tav.yml
- .github/workflows/test-docs.yml
- .github/workflows/test.yml
- .github/workflows/updatecli.yml
This is (a) to avoid the warnings in workflow runs, e.g.:
test-tav (@apollo/server 22) ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636
and (b) to try it out ahead of the switch.
> chore(ci): change from ubuntu-latest to ubuntu-24.04

- CHANGELOG.asciidoc
- docs/esm.asciidoc
- package-lock.json
- package.json
- Azure Functions Node.js programming model v4 support (#4426)
- Instrumentation fix for release `@aws-sdk/client-*` releases -- versions 3.723.0 and later. (#4398)
> release 4.11.0

- .github/dependabot.yml
- CHANGELOG.asciidoc
- Dockerfile
The Docker image of the agent is currently based in `alpine@3.9` which is almost 3y old and have some issues related to libssl@1.1. This PR updates it to version `3.21.3`.
> chore: update alpine base image in Dockerfile

- CHANGELOG.asciidoc
- lib/instrumentation/modules/@hapi/hapi.js
- test/instrumentation/modules/hapi/hapi.test.js
> fix(hapi): limit which event data fields are included in captured APM error object for Hapi 'log' and 'request' error events

- test/instrumentation/modules/bluebird/_coroutine.js
- test/instrumentation/modules/bluebird/bluebird.test.js
For example:
```
not ok 84 ping should be delayed min 9ms (delayed 8ms)
---
operator: ok
expected: true
actual:   false
at: assertPingPong (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/instrumentation/modules/bluebird/_coroutine.js:113:5)
stack: |-
Error: ping should be delayed min 9ms (delayed 8ms)
```
---
@david-luna This is for the flaky test failure you mentioned at https://github.com/elastic/apm-agent-nodejs/issues/3313#issuecomment-2717512344
> test: avoid an occasional flaky bluebird test failure

- CHANGELOG.asciidoc
- CONTRIBUTING.md
- package-lock.json
- package.json
https://github.com/elastic/apm-agent-nodejs/pull/4508
> release 4.11.2

- .github/dependabot.yml
- renovate.json
Use `dependabot` for updating docker images stored in our internal docker registry using [this](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot).
Closes https://github.com/elastic/apm-agent-nodejs/issues/4537
We already have secrets stored for accessing the internal docker registry. Use one dependency management tool with native support for GitHub actions and the [GH secrets access control](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). 
This has been already tested in the past in a sandbox repository and also in another GH internal repositories.
> dependabot: support for docker internal registry

- docs/release-notes/breaking-changes.md
- docs/release-notes/index.md
- docs/release-notes/known-issues.md
Updates the navigation titles for Known issues and Breaking changes pages in the release notes.
> Updates navigation titles for release notes

- CHANGELOG.md
Adds `CHANGELOG.md` that links to changelogs for all versions. Feel free to adjust the links as needed.
> [docs] Add `CHANGELOG.md`

- test/apm-client/http-apm-client/config.test.js
Node.js v23.11 has changed the error message when using a self signed certificate in a HTTP connection. It adds more details on how to solve it. This change makes an assertion to fail giving a false positive in test.
This was discovered in test [test FIPS workflow](https://github.com/elastic/apm-agent-nodejs/actions/runs/14326325034/attempts/1) since its installing the latest stable release. The usual test work flow is using v22 and below so it is not failing there.
> test: update assertion on self signed cert rejection

- docs/reference/azure-functions.md
- docs/reference/nextjs.md
- docs/reference/supported-technologies.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable.
> [docs] Fix image paths for docs-assembler

- docs/reference/starting-agent.md
- docs/release-notes/index.md
- examples/typescript/README.md
- examples/typescript/index.ts
- examples/typescript/package.json
- examples/typescript/tsconfig.json
- lib/stacktraces.js
This also modernizes the examples/typescript/... a bit and (notably) changes it to use ESM.
This was the repro example I was using for this fix -- though I removed the `apm.captureError(...)` I was manually using in examples/typescript/index.ts for dev.
Yes, I don't have a test case here. We should discuss if we're going to require that.
> feat: support sourcemap resolution for *ESM* stack frames in captured APM errors

- test/_is_restify_incompat.js
Update `_is_restify_incompat` check so `restify` test do not fail in Node.js v24. The 1st occurrence of the error happened in FIPS tests workflow
https://github.com/elastic/apm-agent-nodejs/actions/runs/15130108346/job/42529298106
The root cause is a issue in `http-deceiver` dependency
```sh
npm ls http-deceiver
elastic-apm-node@4.13.0 /Users/david/Documents/repos/el/apm-agent-nodejs
└─┬ restify@11.1.0
└─┬ spdy@4.0.2
└── http-deceiver@1.2.7
```
the module uses the following expression
```js
HTTPParser = process.binding('http_parser').HTTPParser;
```
and the internal `http_parser` module is not present in Node.js v24 so it fails in cascade when trying to load `restify`. I'm not sure if this internal module has been removed intentionally though
> tests: update `_is_restify_incompat` checks

- .github/dependabot.yml
Dependabot is configured per repo so we need your help to ensure that when “npm” is the package ecosystem that we set a cooldown to 14 days. See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
> Add cooldown for npm dependency updates
