.gitignore
.npmignore
docs/index.asciidoc
package.json
script/build_docs.sh

This is the basic doc structure needed for the elastic docs build. For convenience I added a script that can be executed with `npm run docs` to build the docs locally to see if the doc build passes and how the docs will look like.
As soon as we have Jenkins added as CI we should also add a build step for `npm run docs` to make sure we do not break the doc build.

Add basic docs structure to agent

---

docs/page_header.html

Adding this file to the docs directory will add a banner at the top of each page. I forgot that we only get the banner by default on master if we also have a released version.
I'll also create banners in the other repos.

[Docs] Add banner for preliminary docs

---

lib/instrumentation/queue.js

The purpose of the boot flush time is to be lower than the normal flush time in order to get a result quickly when the app first boots. But if a custom flush interval is provided and it's lower than the boot flush time, it doesn't make much sense anymore. In that case, just pretend we have already used the boot flush time.

Handle edge case where flushInterval < 5s

---

.tav.yml
.travis.yml
README.md
lib/instrumentation/index.js
lib/instrumentation/modules/elasticsearch.js
package.json
test/instrumentation/modules/elasticsearch.js
test/posttest.sh
test/pretest.sh

This adds traces for all Elasticsearch queries. The query is logged as well, but for now the index is not logged as that isn't easily available from the Elasticsearch driver.
Example of new Elasticsearch trace:
```js
{
name: 'Elasticsearch: POST /_search',
type: 'db.elasticsearch.request',
start: 2.241679,
duration: 8.883929,
stacktrace: [...],
context: {
db: { statement: '{"q":"pants"}', type: 'elasticsearch' }
}
}
```

Add simple Elasticsearch instrumentation

---

lib/instrumentation/index.js

Previously the queue was initialized prior to the agent configuration being processed. This meant that agent._flushInterval wasn't available. This commit moves the initialization of the queue to a later stage where the agent configuration have already been processed.

Fix setting of custom flushInterval

---

lib/config.js
lib/request.js

Previously these options were truncated for every request to the intake API. Now they are only truncated once the agent is started.

Only truncate config options once

---

lib/agent.js
lib/config.js
lib/request.js
test/agent.js
test/request.js

It's been decided by the Elastic APM project to no longer support logging of a git reference. Instead it's recommend to use the appVersion config option.

Remove appGitRef config option

---

test/posttest.sh
test/pretest.sh

Be smarter about stopping database after local testing.  
For MongoDB we can use a pid file and for PostgreSQL we instead use the `pg_ctl` command to control the database as a daemon.

Don't kill all databases after testing

---

lib/parsers.js
test/parsers.js

Normally HTTP requests start with a line like this:
GET /foo HTTP/1.1
But it is actually allowed to include both protocol and domain name in this line, eg:
GET https://example.com:8080/foo HTTP/1.1
This commit adds support for extracing these extra bits of information in case they are provided.
For more information about these type of requests, see section 5.1.2 in RFC 2616: https://tools.ietf.org/html/rfc2616#section-5.1.2

Support parsing http requests with full URI's

---

script/build_docs.sh

By default all headlines with level 2 (`==`) will get its own page.
When setting `--chunk=1`, all headlines with level 3 (`===`) will get its own page as well and will be shown in the ToC like so:

Ensure docs are build locally just as they are in prod

---

docs/agent-api.asciidoc
docs/api.asciidoc
docs/trace-api.asciidoc
docs/transaction-api.asciidoc

- This change gives direct access to each part of the API reference directly from the ToC:
- It also creates a new generic API page which needs some content, so I made this:
- And it shows each function and property in the sidebar for each of the 3 new pages:

Split up API reference into 3 separate pages

---

docs/index.asciidoc

The asciidoc reference doesn't resolve when rendered by GitHub, so we have to write the link in full.
The notice is also moved above the headline to make it more visible.
Example:

Fix docs link shown to GitHub users

---

docs/agent-api.asciidoc
lib/agent.js
lib/config.js
package.json
test/integration/abort-on-invalid-cert.js
test/integration/allow-invalid-cert.js
test/test.sh

By default the agent will validate the SSL/TLS certificates used by the APM Server (if running on HTTPS). This validation can now be turned off by setting the `validateServerCert` option to `false`. This is particularly useful if the APM Server is using self-signed certificates.

Add validateServerCert config option

---

docs/agent-api.asciidoc

This link changed in https://github.com/elastic/apm-server/pull/187
Please don't merge this PR before https://github.com/elastic/apm-server/pull/187 has been merged.

Fix link to APM Server Error API docs

---

lib/instrumentation/modules/graphql.js
test/instrumentation/modules/express-graphql.js

The operation name is included both in GraphQL trace names and in GraphQL transaction names.
This commit is just cherry picked from https://github.com/opbeat/opbeat-node/commit/48d5d021389461bd68e9c37311802af8925ac4bf

Include GraphQL operation name in trace and transaction names

---

.travis.yml

The greenkeeper.io service will create branches starting with `greenkeeper/` when ever a new dependency is released on npm. In this case we only need to test aganst the latest version of the dependency. So there's no reason to run the full dependency build stage in that case.

Don't run dependency tests on greenkeeper branches

---

lib/instrumentation/queue.js
test/instrumentation/modules/http/timeout-disabled.js
test/instrumentation/modules/http/timeout-enabled.js
test/integration/no-sampling.js

In the old Opbeat agent we would sample transactions. This is no longer done and this commit removes the old sampling logic.
Fixes #30

Don't sample transactions

---

lib/request.js

This is only used during development and is currently undocumented

Rename ELASTIC_APM_DEBUG_PAYLOAD to DEBUG_PLAYLOAD

---

lib/request.js

Before you'd need to run with `DEBUG=*` as well to get any output. Since this is only used during development it's ok to log directly to STDOUT.

Always log DEBUG_PAYLOAD info to STDOUT

---

lib/instrumentation/index.js
lib/instrumentation/queue.js
test/instrumentation/modules/http/timeout-disabled.js
test/instrumentation/modules/http/timeout-enabled.js
test/instrumentation/queue.js

The queue shouldn't have to know about transactions and what to do with them when it's flushed.
This commit makes the queue generic so it can hold any data. This makes it easier to test and is good practice in general (separation of concerns).

Simplify queue API

---

test/script/docker/run_docs.sh
test/script/docker/run_tests.sh

This enforces that the latest available docker image for the given version is pulled. 
E.g. nodejs version "8" should always be updated to latest version "8.x.y". 
It seems there was a bug in version 8.5 that prevented to properly work with npm4. Forcing to pull to latest node version should fix the issue, closes #61 .

test(docker): enforce pulling latest docker image.

---

docs/agent-api.asciidoc
lib/agent.js
lib/config.js
lib/instrumentation/http-shared.js
test/instrumentation/_agent.js
test/instrumentation/modules/http/aborted-requests-disabled.js
test/instrumentation/modules/http/aborted-requests-enabled.js
test/instrumentation/modules/http/basic.js
test/instrumentation/modules/http/outgoing.js

The two config options `timeout` and `timeoutErrorTreshold` are renamed to `errorOnAbortedRequests` and `abortedErrorThreshold` respectively. The associated environment variables have been renamed as well.
The old names were poorly chosen as they indicated the options had something to do with an HTTP timeout where in fact all they did was listen for TCP sockets that closed prior to completion of their HTTP requests.

Rename timeout config options

---

test/script/docker/cleanup.sh

It looks like there are leftovers of volumes on Jenkins. Adding the prune command to enforece cleaning up volumes.

fix(docker): force volume prune when cleanup docker

---

lib/instrumentation/transaction.js
test/instrumentation/modules/ioredis.js
test/instrumentation/modules/mongodb-core.js
test/instrumentation/modules/redis.js
test/instrumentation/transaction.js

We're moving away from thinking of transaction results as HTTP status codes. In most non HTTP cases and transaction either fails or succeeds.
Bear in mind that this is only the default value. For HTTP transactions we will still overwrite this.

Set default transaction.result to success

---

lib/request.js

Since the APM Server now allows `language.name` to be set without also specifying a version, we can just set the language as `javascript`.
I have on purpose not made this user configurable at the moment. After digging into the details of this I found that the subject was more complicated than simply adding a new configuration option. So I'd rather just get this in as a good sensible default that will cover most cases instead of trying to come up with the perfect solution that will take longer to get right.
Closes #6

Add language to APM Server requests

---

lib/instrumentation/modules/http.js
test/instrumentation/modules/hapi.js
test/instrumentation/modules/http/_assert.js
test/instrumentation/modules/koa-router/index.js

When recording an HTTP transaction we set its result to the HTTP status code. With this change we now only record the major group, e.g. `2xx` instead of `204` and `5xx` instead of `500` etc.
**Question:** This will obviously only work for HTTP status codes that are above 99 and less than 1000. Can we think of any case where people use an HTTP status code not in this range?

Log HTTP results in groups of 100

---

docs/agent-api.asciidoc
lib/instrumentation/queue.js

Randomize flush time to avoid servers started at the same time to all connect to the APM server simultaneously.
If the queue flush timer was started as soon as the server booted, this PR would solve the problem where multiple servers started at the same time and hence also flushed their queue at the same time.
But since our queue flush timers actually doesn't start until the first transaction have been ended, we might not even have a problem? So this PR might be trying to solve a problem that doesn't exist. Thoughts?
As noted by the TODO in the code, there might be an existing algorithm we can leverage instead of inventing our own

Add fuzziness to flushInterval

---

lib/instrumentation/async-hooks.js
lib/instrumentation/es6-wrapped-promise.js

The async-hooks.js file is a port of async-listener. The file have now been updated with the latest changes from async-listener up until (and including):
https://github.com/othiym23/async-listener/commit/9c0f9eaa62862a62911eb2358d0b812d6bbd78b3

Update patches to async code

---

docs/agent-api.asciidoc
lib/agent.js
lib/config.js
lib/instrumentation/protocol.js
lib/parsers.js
test/parsers.js

The sourceContext option allows disabling the inclusion of source
code lines with stack trace payloads, reducing payload size and
processing time.
This fixes #83.

feat(parser): support sourceContext option

---

test/instrumentation/_async-await.js
test/instrumentation/async-await.js

I wanted to get these tests into master to make sure that the switch to async-hooks doesn't break this functionality.
I think there shouldn't be any difference as (to the best of my knowledge) async/await is just syntactic sugar on top of native promises, so if our patching or async-hooks works with promises it should also work with async/await.
But I've never used this my self, and hence my knowledge is very very limited on this subject, so please correct me if I'm wrong or if the tests are actually not testing what I think they are testing 😅 
The idea of the test is to start one async operation and then start another that finishes before the first and hence potentially mess with the currently active transaction.

test(*): add tests to test async await instrumentation

---

test/instrumentation/transaction.js

It failed here: https://apm-ci.elastic.co/job/elastic+apm-agent-nodejs+pull-request+multijob-run-tests/65/NODEJS_VERSION=4,label=linux/console
It hasn't failed before, so this is probably really rare, but I like to improve these when I find them

test(transaction): reduce risk of race condition

---

docs/compatibility.asciidoc

Handlebars support was added in #98 
@Qard I forgot that we needed to update this page as well

docs(compatibility): add handlebars to list of instrumented modules

---

README.md
docs/index.asciidoc
docs/page_header.html

As Elastic APM 6.1 goes live we go into beta.
When this PR is merged into master, the official docs will be changed to show that we're in beta.
After merging this PR, do the following:

docs(*): we're now in beta!

---

lib/request.js

Example of error message outputtet by the agent after this change:
```
Elastic APM HTTP error (400): Problem validating JSON document against schema: I[#] S[#] doesn't validate with "error#"
I[#] S[#/required] missing properties: "app", "errors"
```

refactor(*): better format of error messages from the APM Server

---

package.json
test/integration/server-url-path.js

I've updated the elastic-apm-http-client module to support this feature and bumped the dependency.
Closes #115

feat(conf): allow serverUrl to contain a sub-path

---

.tav.yml

For the moment we do not support GraphQL 0.12.0 and above. Until support for these versions are added, we'll limit the TAV tests so that our builds don't break.

test(ci): don't test GraphQL >=0.12.0

---

lib/parsers.js

This check was added because we saw it in the wild. Maybe just a bug in an old version of V8, who knows, but let's keep the check. But let's also remove the TODO as the APM Server API requires the `lineno` property and it has to be an int, so there really isn't much within reason that we can do about it.

chore(*): remove TODO

---

.travis.yml

The order of the the different stages are now in the same order as they are executed on Travis and big headlines separate them so it's easier to read

chore(travis): improve readability of .travis.yml

---

lib/agent.js
lib/instrumentation/http-shared.js
lib/instrumentation/index.js
lib/instrumentation/protocol.js
lib/parsers.js
lib/request.js
test/agent.js
test/instrumentation/_agent.js
test/instrumentation/modules/http/aborted-requests-disabled.js
test/instrumentation/modules/http/aborted-requests-enabled.js
test/instrumentation/modules/http/blacklisting.js
test/instrumentation/protocol.js
test/parsers.js
test/start/env/test.js
test/start/file/test.js

Previously the agent inadvertently exposed some of the config options set when the user configured the agent, e.g. `agent.appName`. All these properties have now been moved under an `agent._conf` namespace to indicate that they should be considered private.
It was never intended that the user could manipulate these properties, but since they wasn't prefixed with an underscore, this might not have been clear.

refactor(agent): make all config properties private

---

.tav.yml
.travis.yml
test/.jenkins_tav.yml
test/instrumentation/modules/hapi.js

connectionless tests should not run before 15.0.2.
server.stop(...) requires a stop callback until 10.x.
Fixes #126

test(hapi): fix hapi tests

---

.travis.yml
docs/agent-api.asciidoc
docs/compatibility.asciidoc
lib/config.js
lib/instrumentation/async-hooks.js
lib/instrumentation/index.js
package.json
test/agent.js
test/instrumentation/async-hooks.js
test/instrumentation/github-issue-75.js

Use async_hooks for Node.js 8.2.0 and above

---

.tav.yml
.travis.yml
docs/agent-api.asciidoc
docs/express.asciidoc
lib/agent.js
lib/instrumentation/modules/express.js
test/.jenkins_tav.yml
test/instrumentation/modules/express.js

This enables automatic tracking of express errors, rather than requiring manual use of the middleware.
Fixes #84

feat(express): auto-track errors

---

lib/request.js
test/request.js

The process fields pid, title and argv have been moved into
a process namespace in the message envelopes.
Fixes #149

chore(*): move process fields to namespace

---

lib/agent.js
test/instrumentation/index.js

I've split this PR up into two commits on purpose to keep it clean. It should also merged using rebase.
Closes #147

Add `transaction.id` to all errors

---

docs/agent-api.asciidoc
lib/config.js
lib/request.js
test/agent.js

Fix #110 
BREAKING CHANGE: This changes the default stack trace limit. If the user doesn't already overwrite the `stackTraceLimit` config option, this commit will affect their setup.

Set default stack trace limit to 50 frames

---

lib/agent.js
lib/config.js
lib/instrumentation/protocol.js
lib/instrumentation/trace.js
lib/instrumentation/transaction.js
lib/parsers.js
package.json
test/request.js

Since dropping support for versions of Node.js older than 4, we no longer need the object-assign polyfill.

refactor(*): use native Object.assign

---

docs/agent-api.asciidoc

Now called 'parameterized message object'

docs(*): rename 'parameterized error object'

---

package.json

As of now the old and the new version of this field is the same, but when 10.x is released we don't want that to be covered as well.

chore(*): only list Node versions in 'engines' field that we support

---

docs/agent-api.asciidoc
lib/agent.js
lib/config.js
test/agent.js
test/config.js

~~Depends on #178 + #180~~
Adds `captureErrorLogStackTraces` config option.
Normally only `Error` objects have a stack trace associated with them. This stack trace is stored along with the error message when the error is sent to the APM Server. The stack trace points to the place where the `Error` object was instantiated.
But sometimes its valuable to know, not where the `Error` was instantiated, but where it was detected. For instance, when an error happens deep within a database driver, the location where the error bubbles up to, is sometimes more useful for debugging, than where the error occurred.
Set the `captureErrorLogStackTraces` config option to `always` to &mdash; besides the error stack trace &mdash; also capture a stack trace at the location where `captureError` was called.
By …

feat(errors): add captureError call location stack trace

---

.appveyor.yml
.npmignore
test/_assert.js
test/agent.js
test/instrumentation/modules/mysql/_utils.js
test/instrumentation/modules/mysql/mysql.js
test/instrumentation/modules/mysql/pool-release-1.js
test/parsers.js
test/request.js
test/script/appveyor/install-elasticsearch.ps1
test/script/appveyor/install-redis.ps1
test/sourcemaps/index.js

This PR tests the latest Node.js LTS version on Windows using the AppVeyor service.
Since AppVeyor doesn't allow parallel builds without payment, I'm only running one build, as it would otherwise take so long that we might end up waiting for the Windows tests. If we wanted to run all builds, this is how the `.appvoyer.yml` file would have to be modified:
```diff
PGUSER: "postgres"
PGPASSWORD: "Password12!"
MYSQL_PASSWORD: "Password12!"
+  matrix:
+    - NODEJS_VERSION: "9"
+    - NODEJS_VERSION: "8"
+    - NODEJS_VERSION: "6"
+    - NODEJS_VERSION: "4"
+    -
+      NODEJS_VERSION: "9"
+      ELASTIC_APM_ASYNC_HOOKS: "0"
+    -
+      NODEJS_VERSION: "8"
+      ELASTIC_APM_ASYNC_HOOKS: "0"
install:
- ps: .\test\script\appveyor\install-redis.ps1
- ps: …
```

Test on Windows using AppVeyor

---

README.md

Instead of wrapping lines at 72 chars, we wrap after punctuation marks. This ensures updates will have a much nicer diff.

docs: use same line wrap rules in README.md as in docs/*

---

docs/agent-api.asciidoc

docs: emphasize errors aren't ignored by ignore* config options

---

docs/agent-api.asciidoc
lib/agent.js
lib/config.js
lib/instrumentation/modules/express.js
lib/instrumentation/modules/hapi.js
lib/request.js
test/_apm_server.js
test/config.js
test/instrumentation/_agent.js
test/request.js

Add `frameworkName` and `frameworkVersion` config options.
Allow overwrite of autodetected framework name and version or to set these values in case they cannot be detected automatically.
Closes #209

feat: allow setting of framework name and version

---

docs/agent-api.asciidoc
lib/config.js
test/config.js

This is to align with the defaults found in the Python agent.
See elastic/apm-server#622 for details.

fix: don't collect source code for in-app span frames by default

---

lib/instrumentation/transaction.js
test/instrumentation/transaction.js

If a transaction isn't sampled, it will not have a `context` property. The code tried to set properties on the `context` property if a request or response had been associated with the transaction. That would result in errors like this:
TypeError: Cannot set property 'request' of null
This commit ensures that we only try to parse the associated `trans.req` and `trans.res` if the transaction is sampled.
Fixes #235

fix: don't add req/res to unsampled transactions

---

lib/instrumentation/modules/mongodb-core.js

In case a callback isn't provided when making a MongoDB query, we shouldn't try to create a span as we have no way of ending it.

refactor(mongodb): don't build spans that are not needed

---

lib/agent.js
package.json

To help us with debugging issues in user applications in the future, I've been working on adding more details to the initial debug output that we print when running with `DEBUG=elastic-apm-node`.
Please let me what you think and if there's something more that should be added to the output 😄 
Here's an example of the new output:
Here the object is formatted a little nicer:
```js
{ pid: 76707,
ppid: 8601,
arch: 'x64',
platform: 'darwin',
node: 'v9.4.0',
agent: '1.0.3',
requireAncestors:
[ '/Users/watson/code/node_modules/elastic-apm-node/index.js',
'/Users/watson/code/foo.js' ],
startTrace:
[ 'at Agent.start (/Users/watson/code/node_modules/elastic-apm-node/lib/agent.js:73:11)',
'at Object.<anonymous> (/Users/watson/code/foo.js:1:91)',
'at Module._compile (module.js:660:30)',
'at …
```

feat(debug): output more debug info on start

---

docs/agent-api.asciidoc
docs/api.asciidoc
docs/custom-spans.asciidoc
docs/span-api.asciidoc
lib/agent.js
test/agent.js

For now `agent.startSpan()` is just a convenience function that first calls `agent.buildSpan()` followed by `span.start()`.
This is step one in fixing #255.
The docs are updated to list the old `buildSpan` function as deprecated, but calling that function still works as before, so this is not a breaking change. This is how the deprecation warning looks:

feat: add agent.startSpan() function

---

lib/instrumentation/modules/mongodb-core.js

This would happen if sampling is enabled and the current transaction isn't sampled, or if the current transaction is ended, or if the current span is dropped.

fix(mongodb): don't throw if span cannot be built

---

docs/index.asciidoc
docs/upgrade-to-v1.asciidoc
docs/upgrading.asciidoc

This adds two pages to the documentation:
- An upgrade overview page (required if we want the list of upgrade guides to be collapsed on the index page - similar to the API page)
- A detailed page describing the upgrade path from 0.x to 1.x

docs: add guide for upgrading from v0.x to v1.x

---

docs/agent-api.asciidoc
lib/config.js

This will prevent overflowing the queue in high-traffic environments that have not been configured to sample requests.

fix(config): set default maxQueueSize to 100

---

README.md

This should not be merged until next 1.x version is published as the link currently only works in master

docs: add links to Upgrading docs from README.md

---

lib/instrumentation/span.js
package.json

I replaced the code that queues and waits for promises with something that just defers the queue until after the encode. The excessive promise usage had some noticeable overhead.
This may result in transactions entering the queue out of order, but I don't think that matters.

fix(span): Do not pass stack frames into promises 

---

lib/request.js

Depends on #281.
We should be able to safely assume that these properties will always be strings and that they will never be longer than 1024 bytes.

 refactor: don't stringify and truncate core values

---

docs/agent-api.asciidoc

I'm not sure that it's common knowledge that you can read the package.json file this easily in Node.js, so I thought we'd better include an example here.

docs: add frameworkVersion example

---

lib/instrumentation/index.js
package.json

The overhead of using the Promise API is too great. This reduces memory allocations and is easier on GC.
I took a stab at using your new module @Qard 😄 
As it doesn't have an `.all` function, I've implemented that manually. But it might make sense to build that into the async-value-promise module instead. If so I'll just update this PR.

refactor: don't use promises in the queue

---

docs/lambda.asciidoc

There's a minor bug in the "getting started with lambda" part of the docs in the latest release. This fixes it.

fix(doc): lambda getting started had old argument

---

lib/instrumentation/index.js
lib/queue.js
test/queue.js

The queuing logic isn't unique to transactions. It makes more sense to put it directly in the lib folder. This also allows us to use it for errors which we might want to do in the future.

refactor: prepare queue to be used by errors

---

test/instrumentation/modules/http/github-179.js

Spotted an unconverted `appName` in the tests.

fix(test): appName -> serviceName in http test

---

docker-compose.yml

This is only temporary. MySQL 8 was just released and our test suite doesn't seem to run on that version.
Here's an example of the failure:
https://apm-ci.elastic.co/job/elastic+apm-agent-nodejs+pull-request+multijob-run-tests/435/NODEJS_VERSION=8,label=linux/console
The issue is most like this one:
https://github.com/mysqljs/mysql/issues/1507

test(jenkins): pin mysql docker image to v5.7

---

lib/instrumentation/span.js

Discussion: https://discuss.elastic.co/t/node-agent-could-not-capture-stack-trace-for-span/130775

fix: encode spans even if their stack trace can't be captured

---

test/parsers.js

I was debugging the `prepareCallsite` tests and needed better output from the tests. Thought I might as well commit it.

test: improve test output for parsers.prepareCallsite()

---

lib/instrumentation/transaction.js

@watson I made this change while debugging the context loss in Node.js 10 and thought it might actually be a good idea to keep it. It might be good to do a similar thing to spans. 🤔

feat(transaction): add toJSON to transaction

---

.gitignore

Just wanted to ignore the `.vscode` config directory so git doesn't keep telling me to add it. 😅

chore: ignore .vscode directory

---

CONTRIBUTING.md

I used the guide when publishing 1.5.0 and found just one issue that I thought I'd improve in case `master` is not specified as a remote branch on `upstream`. Also I removed an optional step. But maybe you had good reasons to keep it in?

docs: improve npm release guidelines

---

lib/instrumentation/modules/express.js
lib/parsers.js
test/agent.js

fix: guard against non string err.message

---

docs/compatibility.asciidoc

This module was already instrumented, but was for some reason missing from the list.

docs: add elasticsearch-js to list of instrumented modules

---

test/agent.js

Not super important, but it was an untested code path in `lib/agent.js`. And as I was going over it anyway, I thought I might as well cover it.

test(agent): test agent.addFilter() with invalid argument

---

test/instrumentation/modules/http2.js

The tests broke due to a breaking change being backported from 9.x to 8.x. See https://github.com/nodejs/node/issues/20773 for details.

test(http2): fix broken tests on new Node v8.11.2 release

---

test/instrumentation/modules/hapi.js
test/instrumentation/modules/http2.js

This is a prerequisite for solving #316
The reason that I can't include this in the same commit that solves #316, is that I'm exploring the darker sides of Travis CI where I'm actually checking out master as part of the Travis `install` step and running the RC tests on that. So if this isn't in master the tests will fail.

test: allow test suite to run against Node.js release candidates

---

.travis.yml

This means that builds that would normally start up just to stop again when the if statement didn't trigger, now are not included in the job at all

test(ci): use conditional stages to quicker skip builds

---

lib/request.js

In this instance the function actually isn't anonymous in modern versions of V8 as the function will be given the name of the variable. But we prefer this style over the variable assignment style.

chore: don't use "anonymous" functions

---

docs/upgrade-to-v1.asciidoc

Just a minor thing I found while doing other stuff... major nitpick 😄

docs: fix asciidoc table syntax to match general style

---

lib/instrumentation/transaction.js

When serializing the transaction payload, we need the `remoteAddress` for the socket. This needs to happen before the socket is closed so we're sure that we still have access to the socket object. In HTTP/1.1 this didn't seem to be an issue, but in HTTP/2 the socket was set to `undefined` when the close event was emitted.

fix: get remoteAddress before req close event

---

test/_apm_server.js
test/agent.js

Previously these tests never ran through the tests for the 2nd request as the server was closed prematurely. The test would output the following error, but would not actual fail:
Error: connect ECONNREFUSED 127.0.0.1:52177
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)

test: fix silent error in lambda tests

---

docs/agent-api.asciidoc
lib/config.js
lib/instrumentation/index.js
lib/instrumentation/modules/elasticsearch.js
lib/instrumentation/modules/express-graphql.js
lib/instrumentation/modules/express.js
lib/instrumentation/modules/graphql.js
lib/instrumentation/modules/handlebars.js
lib/instrumentation/modules/hapi.js
lib/instrumentation/modules/http.js
lib/instrumentation/modules/http2.js
lib/instrumentation/modules/https.js
lib/instrumentation/modules/ioredis.js
lib/instrumentation/modules/knex.js
lib/instrumentation/modules/koa-router.js
lib/instrumentation/modules/mongodb-core.js
lib/instrumentation/modules/mysql.js
lib/instrumentation/modules/pg.js
lib/instrumentation/modules/redis.js
test/config.js
test/instrumentation/_agent.js

Here's a basic implementation for disabling instrumentation. It still needs docs and such.
@watson Does this approach seem okay?
Fixes elastic/apm-agent-nodejs#273

feat(config): disable instrumentation

---

package.json

We were previously stuck with old versions of these two modules, but now they are up to date.

chore: don't let greenkeeper ignore get-port and restify

---

docs/agent-api.asciidoc
lib/config.js
lib/request.js
test/config.js
test/request.js

Will truncate error messages to max 2048 bytes by default. This length can be configured using the new `errorMessageMaxLength` config option. If set to `-1` no truncation will occur.
Fixes #390

feat: truncate very long error messages

---

README.md

I just found my self having forgotten if our npm package was called `elastic-apm-node` or `elastic-apm-nodejs`. And since our repo name doesn't match the package name, I thought it would be a nice gesture to make is easier to see without having to leave the README file.

docs: add into about the npm pacakge to README.md

---

test/integration/api-schema/download-json-schemas.sh

Some times curl fails when trying to download a schema from GitHub. This is usually just a temporary error and will succeed if retried.
This commit retries downloads up to 5 times before failing permanently.

test: make schema integration tests more resilient

---

.tav.yml
package.json
test/instrumentation/modules/pg/knex.js

Newly released Knex v0.15.0 dropped support for Node.js 4+5

test: don't test knex on unsupported Node versions

---

.tav.yml
.travis.yml
lib/instrumentation/index.js
lib/instrumentation/modules/mimic-response.js
lib/instrumentation/shimmer.js
package.json
test/.jenkins_tav.yml
test/instrumentation/modules/http/github-423.js
test/instrumentation/modules/mimic-response.js

The `mimic-response` module exposes a single function with the following API:
```js
mimicResponse(fromStream, toStream)
```
If someone is calling `mimicResponse` where the `fromStream` have had its emitter functions bound using `bindEmitter(fromStream)`, the `toStream` will wrongly bind all its event listeners to the `fromStream`.
This becomes especially problematic in case the data is transformed either in the `toStream` or in between `fromStream` and `toStream`, eg:
```js
fromStream.pipe(zlib.createGunzip()).pipe(toStream)
```
In those cases, the data emitted by `toStream` will actually be the un-transformed data coming from the `fromStream`.
This commit patches `mimic-response` so that the event emitters of `toStream` runs in the expected context.
Fixes #423

fix: ensure correct streaming when using mimic-response

---

README.md

The old badge didn't show the correct dependency numbers, so let's just use a simpler one. As long as it links to the npm page then it's good 😄 
This is how it will look:

chore: change npm badge in README.md

---

README.md
docs/index.asciidoc
docs/performance-tuning.asciidoc
docs/performance.asciidoc

@watson I'm not sure this is quite done yet, but I don't have any more time to work on this tonight. Feel free to make your own edits, otherwise I'll get back to it next Tuesday.

doc: add performance tuning doc

---

lib/instrumentation/index.js
package.json
test/_agent.js

Ever since require-in-the-middle allowed multiple hooks to be added in the same app, the `Module.prototype.require` function was patched multiple times if the agent was initialized more than once in the same test file.
This resulted in a lot over overhead every time `require()` was called by any module. This was especially visible in the `disableInstrumentations` tests that would take about a minute to complete because of this.
With this commit, the `disableInstrumentations` tests only take a few seconds.

test: don't patch Module.prototype.require more than once

---

lib/instrumentation/modules/mimic-response.js

Version 1.0.1 of mimic-response have just been released with the following fix:
https://github.com/sindresorhus/mimic-response/pull/1
This fix makes our own patch redundant, so it's no longer necessary for us to patch this or newer versions. We should still continue to patch version 1.0.0 however.

perf: don't patch newer versions of mimic-response

---

docs/compatibility.asciidoc
test/instrumentation/modules/hapi.js

The bug in V8 that meant we couldn't instrument Node 10 was fixed and Node 10.4.0 shipped with a newer version of V8.
This is the original bug report in Node: https://github.com/nodejs/node/issues/20516
This is the PR that fixed it in Node: https://github.com/nodejs/node/pull/19989
Closes #448

docs: remove reference to Node 10 incompatibility

---

.travis.yml

As Node.js 9 is now EOL, no new nightlies or release candidates will be created for this version. It's therefore safe to remove these jobs from the Travis CI build matrix.

test: remove Node 9 nightly/rc jobs from Travis build matrix

---

.travis.yml

Travis CI just announced that we can now [customize the job names](https://docs.travis-ci.com/user/build-stages#Naming-your-Jobs-within-Build-Stages) 🎉 
This makes it easier to know what each job does:
I've just run a test build of this PR with all the different stages activated to see how it looks for each job:
https://travis-ci.org/elastic/apm-agent-nodejs/builds/405734487

test: use custom Travis CI job names

---

test/instrumentation/modules/tedious.js

The span ordering of the mssql prepare test was non-deterministic,
so this will sort the spans so the tests are not order-dependent.

test(mssql): fix non-deterministic tests

---

lib/instrumentation/modules/graphql.js
test/instrumentation/modules/graphql.js

This PR fixes handling of arguments passed to the graphql execute function by adding support for passing the arguments as an object. This is [how the latest version of apollo does it](https://github.com/apollographql/apollo-server/blob/e77701c77253db007171a2437fe361c5bb2c2312/packages/apollo-server-core/src/runQuery.ts#L232) and the implementation is based on [how this is handled in the graphql module itself](https://github.com/graphql/graphql-js/blob/3124fa32dc77c5844bf74ebc07e38239ad78e856/src/execution/execute.js#L164-L183).

fix(graphql): handle execute args object

---

test/instrumentation/modules/http/aborted-requests-disabled.js

It may take a bit of time for the transaction to get added to the queue, so use an interval check with a longer timeout to verify the transaction has been added, rather than a single short timeout.

test(http): improve http abort tests

---

lib/parsers.js
test/parsers.js

Use JSON.stringify by default but fall back to the slower fast-safe-stringify if it throws. This will be faster on larger more deeply nested bodies.
For details see:
https://github.com/davidmarkclements/fast-safe-stringify#protip

perf: improve request body parsing speed

---

test/instrumentation/modules/http/_echo_server_util.js
test/integration/api-schema/_utils.js

The api-schema tests break if the path to the repo contains a directory with a space in the name.

test(api-schema): fix to support paths with spaces

---

README.md

The uppercase `.MD` made the link go 404. Though the testing section still exists in the CONTRIBUTING.md document, it just instructs the reader to go to the TESTING.md file, so I thought we might as well update the link to point directly to that as well

docs: fix 404 link in README.md

---

test/instrumentation/modules/hapi.js

This ensures pre-release versions are skipped properly.

test: properly exclude failing version

---

docs/agent-api.asciidoc
docs/performance-tuning.asciidoc
lib/config.js
test/instrumentation/modules/http2.js

docs: add api docs for apiRequestTime and apiRequestSize

---

test/agent.js

This is a race condition. The tests would call t.end() before all their assertions had finished. This would not be an issue when running the tests normally, but when running via nyc it would fail.

test: fix agent lambda tests when run with nyc

---

lib/filters.js
package.json
test/filters.js

Fixes elastic/apm-agent-nodejs#468
Depends on Qard/set-cookie-serde/pull/1

feat(filters): filter set-cookie headers

---

lib/instrumentation/modules/express.js
test/instrumentation/modules/express.js

In strict mode you cannot set a property on a string, this causes a fatal error on my side. This proposed change does still report the error, but does not set the reported symbol, furthermore it prints out a warning that a string in strict mode cannot be correctly tracked.
Besides this it allows to disable the error handler at all (we are using redis/sentry for this anyway), and do not need this error reporting feature. 
Let me know what you think.

Fixes #509

---

lib/instrumentation/index.js

The require-in-the-middle module no longer patches the Module._load function. Let's change the debug message so it's not implementation specific to avoid this problem in the future.

chore: update debug message to match reality

---

test/instrumentation/modules/restify.js

If an error would occur during the tests, the agent would try to send it to https://localhost:8200 which would fail. In that case the user would not be shown the stack trace of the actual error, but instead only see the error message from the agent.
Normally I wouldn't make a PR like this just in case there might be an error, but this actually occurred to me when modifying the Restify tests to work with API v2, so thought I'd better fix it 😅 Here's what it looks like:
```
$ node test/instrumentation/modules/restify.js
TAP version 13
Sending error b9c573e3-213e-4312-9df0-992ce50c82e9 to Elastic APM
An error occrued while communicating with the APM Server: connect ECONNREFUSED 127.0.0.1:8200
```

test: don't swallow errors in Restify tests

---

test/config.js

This should make the `disableInstrumentations` test stop failing due to the agent being unable to connect to apm-server.

test: do not capture exceptions in disableInstrumentations test

---

lib/instrumentation/index.js
test/agent.js

If there wasn't any transactions in the queue, the flush callback would never be called

fix: always call agent.flush() callback

---

lib/agent.js
lib/instrumentation/index.js

Probably this isn't going to change much as the code path is cold. I also looked over `Transaction` and `Span` as those are much hotter, but they all conformed to best practices.

perf: declare instance properties in constructor

---

test/_agent.js
test/config.js

Sometimes the `test/config.js` tests would run long enough for one of the agents created during the tests to flush its queue. The agent had its filters mocked and wasn't expected to actualy send data anywhere, so this would result in an uncaught exception.
This fix does away with mocking of the filters as there was really no reason for it. It also patches the test that wrongly added a transaction to the queue. So now the queue should never be flushed no matter how long the tests run.
Fixes #535

test: fix flaky `disableInstrumentations` tests

---

package.json

The upstream issue that required us to pin the wait-on package have now been fixed: https://github.com/jeffbski/wait-on/issues/28

chore: un-pin wait-on devDependency

---

test/agent.js

This issue was introduced by: https://github.com/elastic/apm-nodejs-http-client/pull/16

test: fix testing for process version

---

lib/instrumentation/transaction.js
test/instrumentation/transaction.js

Fixes elastic/apm-agent-nodejs#552
Depends on elastic/apm-agent-nodejs#557

feat(transaction): span_count.total

---

package.json

Version 3.2.1 was just released which no longer works on Node.js 4. Version 3.x never officially supported Node.js 4, but did run fine until now.
This commit and be reverted once the following PR is released:
https://github.com/maxogden/dependency-check/pull/99

chore(package): pin dependency-check to 2.x version range

---

test/_apm_server.js
test/agent.js
test/integration/server-url-path.js

After I merged the update to the HTTP client these tests have started to fail as we haven't pinned the new API v2 HTTP client to any particular commit/version yet.

test: update intake API endpoint path

---

test/instrumentation/modules/mongodb-core.js

This should (hopefully) solve the mongodb tav issues we've been having.

test(mongodb): ensure spans are sorted by start time

---

test/integration/api-schema/basic.js
test/integration/api-schema/download-json-schemas.sh

This PR technically depends on elastic/apm-server#1447 and on another PR (that I'll make in a sec) that refactors the agent to use the new microsecond timestamps. But we can't all land it in the same PR, so even though this PR will not pass CI, it's cleaner to land it alone as the current state of the api-v2 branch is broken because of this anyway.

test: fix api schema integration tests

---

test/integration/api-schema/download-json-schemas.sh

This file is only used in v1_*.json schemas.

test: remove unnecessary download of JSON schema

---

package.json

v4.x requires Node.js 6+, so this goes into api-v2

chore(package): upgrade read-pkg-up to ^4.0.0

---

docs/agent-api.asciidoc
lib/config.js
test/config.js

fix: use correct default value for apiRequestSize

---

docs/upgrade-to-v2.asciidoc
docs/upgrading.asciidoc

This page is similar to the one we made for [upgrading to v1](https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrade-to-v1.html).
When rendered, the page looks like this:
This PR also adds a link to the page to the [Upgrading page](https://www.elastic.co/guide/en/apm/agent/nodejs/current/upgrading.html):

docs: add v2 upgrade guide

---

docs/agent-api.asciidoc
docs/api.asciidoc
docs/custom-spans.asciidoc
docs/custom-stack.asciidoc
docs/express.asciidoc
docs/hapi.asciidoc
docs/intro.asciidoc
docs/koa.asciidoc
docs/lambda.asciidoc
docs/performance-tuning.asciidoc
docs/restify.asciidoc
docs/setup.asciidoc
docs/span-api.asciidoc
docs/troubleshooting.asciidoc
docs/upgrading.asciidoc

Cleaned up some spelling and grammar issues I found in the docs. No content changes, so probably only needs to be reviewed by one of you?

Fix documentation spelling and grammatical errors

---

docs/agent-api.asciidoc

Typescript removes unused imports, so we should recommend using the `-r elastic-apm-node/start` loading method instead.
Fixes #608

docs: add note about typescript import

---

lib/instrumentation/patch-async.js
lib/instrumentation/shimmer.js

The current error in #632 happens because several functions in the crypto module became property descriptors. This change ensures we don't accidentally try to patch a property that is not writable.

feat(shimmer): safely handle property descriptors

---

docs/agent-api.asciidoc
lib/agent.js
test/agent.js

feat(agent): return uuid in captureError callback

---

.tav.yml
lib/instrumentation/modules/express-graphql.js

CI is failing right now because express-graphql 0.7.x was released and, while the tav ranges tried to test against them, the patch range did not apply the patch, resulting in test failures.

test(express-graphql): update test and patch ranges to match

---

.tav.yml
.travis.yml
docs/compatibility.asciidoc
lib/instrumentation/index.js
lib/instrumentation/modules/apollo-server-core.js
package.json
test/.jenkins_tav.yml
test/config.js
test/instrumentation/modules/apollo-server-express.js

Added instrumentation for apollo-server-express. As the actual instrumentation happens in apollo-server-core it might also work with all other apollo-server-*, but hasn't been tested yet.
Fixes #641

feat(apollo-server-express): add support for apollo-server-express

---

docs/agent-api.asciidoc
docs/span-api.asciidoc
docs/transaction-api.asciidoc
docs/upgrade-to-v1.asciidoc
docs/upgrade-to-v2.asciidoc
lib/agent.js
lib/instrumentation/http-shared.js
lib/instrumentation/index.js
lib/instrumentation/modules/cassandra-driver.js
lib/instrumentation/modules/elasticsearch.js
lib/instrumentation/modules/graphql.js
lib/instrumentation/modules/handlebars.js
lib/instrumentation/modules/http2.js
lib/instrumentation/modules/ioredis.js
lib/instrumentation/modules/mongodb-core.js
lib/instrumentation/modules/mysql.js
lib/instrumentation/modules/mysql2.js
lib/instrumentation/modules/pg.js
lib/instrumentation/modules/redis.js
lib/instrumentation/modules/tedious.js
lib/instrumentation/modules/ws.js
lib/instrumentation/span.js
lib/instrumentation/transaction.js
test/instrumentation/_agent.js
test/instrumentation/github-issue-75.js
test/instrumentation/index.js
test/instrumentation/modules/http/sse.js
test/instrumentation/span.js
test/instrumentation/transaction.js
test/script/cli.js

This removes `agent.buildSpan`, `transaction.buildSpan`, and `span.start`. In there place is `agent.startSpan` and now `transaction.startSpan`. All the prior starting logic from `span.start` is now part of the `Span` constructor.
This is an alternative to #600.

feat: simplified spans

---

lib/instrumentation/transaction.js
test/instrumentation/transaction.js

We previously replaced . and * with _ characters, however, the " character is also invalid so that should be converted too.
Fixes #659

feat: replace double-quotes with underscores

---

docs/agent-api.asciidoc

Fixes changed link in APM Server documentation.
**Only merge after https://github.com/elastic/apm-server/pull/1530**

docs: update links for v2

---

package.json

~~This fixed the issue with correctly counting the size of the sent data so it now counts compressed data instead of uncompressed.~~
Edit: Eh no, too many releases 😅 This fixes the bug with aborting the outgoing request as soon as the server responds

chore(package): bump elastic-apm-http-client to ^6.0.1

---

lib/instrumentation/async-hooks.js

This is an attempt to improve the reliability of the map cleanup with `async_hooks`. This will cleanup _all_ contexts related to a transaction when the transaction is sent. This _does_ mean it would no longer be possible to continue creating spans within a transaction after the transaction itself is ended, but we don't currently really support that officially anyway.

fix(async_hooks): more reliable cleanup

---

lib/instrumentation/async-hooks.js

The biggest change here is not setting the keys in the `transactions` map to `null` but deleting them when the current transaction is being set to `null`.
Besides reducing the size of the of the map, this makes the check for `transactions.has(asyncId)` correct, and though means less overhead trying to access a transaction that is actually just `null`.

perf: improve Async Hooks implementation

---

lib/config.js

We need to output the errors returned from the APM Server in some way.
This is a first attempt and might not be optimal. Hardcoding this in the general transport might not be a good idea either. But it's a good way to get the discussion started.

fix: output APM Server error messages

---

test/agent.js

Sometimes the error would arrive before the span and the tests would fail.
Since we don't actually care about the arrival of the span or the transaction, we can just not end those and the test will not have a race condition anymore.

test: fix possible race condition

---

lib/config.js

APM Server API errors are emitted by the HTTP client as 'request-error' events.
In case of more serious errors, the 'error' event is still used, but indicates that the client could not recover from the error.
The `request-error` event is emitted here: https://github.com/elastic/apm-nodejs-http-client/blob/5d364e1fe9150bde74b6fde8732187f1e2c00e48/index.js#L59

fix: log APM Server API errors correctly

---

docs/troubleshooting.asciidoc

We changed the 1 minute to 10 seconds with the release of version 2.0.0 of the agent, but forgot to update the Troubleshooting docs to match.

docs: improve debug documentation

---

README.md
docs/agent-api.asciidoc
docs/compatibility.asciidoc
docs/intro.asciidoc

These changes are not critical as none of the links are technically broken, but it would just be nicer if the links to the APM Server for version 1.x of the agent pointed to version 6.4 of the APM Server.
@Qard This is the first time we do a PR into an old branch, but I guess this is how we would do it right?

docs: fix APM Server links to 6.4

---

docs/index.asciidoc
docs/redirects.asciidoc

Add hidden `redirects.asciidoc` file to handle "redirect" on current (as we're not supposed to redirect current). Should also backport to 2.x. Will set up website redirect for 2.x as well.

docs: add redirects file

---

lib/instrumentation/modules/hapi.js
test/instrumentation/modules/hapi.js

In certain cases, hapi will tag internal events as "errors" when they are not really errors from a user-facing point of view. This didn't surface until Node.js 11 started to emit them consistently.
This will fix the hapi-related issues in #632.

fix(hapi): ignore internal events channel

---

docs/agent-api.asciidoc
docs/compatibility.asciidoc
docs/index.asciidoc
docs/intro.asciidoc

Versions 1.x links to APM Server and APM Overview v6.4 per elastic/apm/issues/19.

docs: fix cross document links (1.x)

---

docs/agent-api.asciidoc
docs/index.asciidoc
docs/intro.asciidoc
docs/supported-technologies.asciidoc

Versions master links to APM Server and APM Overview v6.5 per elastic/apm/issues/19.
Needs to be backported to 2.x (but with `:node-branch: 2.x` instead of `master`) - is it easier if I just create a new PR in 2.x?

docs: fix cross document links (master)

---

docs/index.asciidoc

Fixes issue discussed in #703. `node-branch` is not needed. `branch` is needed for Elasticsearch and Kibana links.

docs: version fix

---

lib/instrumentation/http-shared.js

The `url.URL` object was added in Node.js v6.13.0. If you tried to perform a `foo instanceof url.URL` on earlier versions, the code would throw the following exception:
```
TypeError: Expecting a function in instanceof check, but got undefined
```
This is a prerequisite for #705 but might also solve #710 - We'll see when it's merged into master.

fix: don't throw on older versions of Node.js 6

---

.tav.yml

In preparation of us starting to backport to the 1.x branch, we need to make sure the tests pass first. Recently a new version of `ws` was released that wasn't compatible with Node.js 4 which made our tests fail. This PR fixes that by omitting it from our TAV tests.

test(ws): fix tests for ws on older Node versions

---

lib/instrumentation/modules/hapi.js
test/instrumentation/modules/hapi.js

- fix(hapi): ignore internal events channel  (#700)

[1.x] fix(hapi): ignore internal events channel (#700)

---

.tav.yml
docs/compatibility.asciidoc
lib/instrumentation/express-utils.js
lib/instrumentation/modules/restify.js
package.json
test/instrumentation/modules/restify.js

- fix(restify): support an array of handlers  (#709)

[1.x] fix(restify): support an array of handlers (#709)

---

README.md

The Compatibility page was renamed to Supported Technologies in version 2.0.0

docs: fix wrong link in README.md ToC

---

package.json

The previous version accidentally included devDependencies as regular dependencies which made the footprint of this package much larger than necessary.

chore(package): bump random-poly-fill to ^1.0.1

---

package.json

It wrongly stated support for Node.js 4 which was dropped in v2.0.0 and it also didn't include version 11.

chore: update engines field in package.json

---

.backportrc.json
.npmignore

This is used by https://github.com/sqren/backport

chore: add .backportrc.json

---

docs/supported-technologies.asciidoc

Closes elastic/apm-agent-nodejs#424 by removing "experimental support" text

docs: remove experimental support text

---

lib/instrumentation/modules/graphql.js
test/instrumentation/modules/graphql.js

Fixes module graphqls error handling with syntax errors in queries
On our project we ran into the problem, that elastic-apm-node would break the working integration of graphql in our app.
Instead of returning a Promise.resolve() with an error object graphql() will throw an error when used with elastic-apm-node.
The pr will fix this behavior by adding a try/catch around the query parsing.
I hope i didn't miss any steps required for this PR.
- testing was done via `npm test all 10 graphql ` and returned "OK"
elastic/apm-agent-nodejs#746

Fix graphql error handling (#1)

---

test/instrumentation/_instrumentation.js
test/instrumentation/span.js
test/instrumentation/transaction.js

Remove check to test if a transaction is ended in all tests where the transaction isn't ended.
In some of these cases, the tests wrongly included assertions that were never run as the callback usually called when a transaction ends obviously wasn't called. In other cases, an assertion validating that the callback wasn't called has been removed as well as the assertion wasn't central to what was being tested.

test: simplify transaction tests

---

lib/instrumentation/span.js

Just a tiny nit that I found. Would normally have done this as part of the refactor in the span tags PR, but I missed it.

refactor: improve span payload encoding

---

test/integration/api-schema/_utils.js
test/integration/api-schema/basic.js
test/integration/api-schema/download-json-schemas.sh

This fixes the latest schema change issues, but should also make the tests more reliable. As far as I'm aware, the rest of the object structure doesn't really matter, but I can restore that, if you think it's important.

test(schema): improve reliability

---

test/instrumentation/modules/apollo-server-express.js

- test(ci): fix apollo-server-express tests on older Node versions  (#743)

[1.x] test(ci): fix apollo-server-express tests on older Node versions (#743)

---

lib/instrumentation/modules/tedious.js

I ran TAV on all versions locally after this change and all passed ✅ 
Fixes:
```
running: test\instrumentation\modules\tedious.js
TAP version 13
not ok 1 no error
---
operator: error
expected: |-
undefined
actual: |-
[TypeError: Class constructor Connection cannot be invoked without 'new']
at: withConnection.then (C:\projects\apm-agent-nodejs\test\instrumentation\modules\tedious.js:74:7)
stack: |-
TypeError: Class constructor Connection cannot be invoked without 'new'
at new Connection (C:\projects\apm-agent-nodejs\lib\instrumentation\modules\tedious.js:35:26)
at Promise (C:\projects\apm-agent-nodejs\test\instrumentation\modules\tedious.js:38:18)
at new Promise (<anonymous>)
at withConnection (C:\projects\apm-agent-nodejs\test\instrumentation\modules\tedious.js:37:10)
at Test.test …
```

fix(tedious): don't fail on newest tedious v4.1.3

---

.tav.yml
docs/supported-technologies.asciidoc
lib/instrumentation/modules/mongodb-core.js
package.json

Version 3.1.10 of mongodb-core removed the _find method that we depended upon to start new spans. Until we find a workaround for this, we'll have to drop support for this and newer versions.

fix: we don't support mongodb-core v3.1.10+

---

.tav.yml
docs/compatibility.asciidoc
lib/instrumentation/modules/mongodb-core.js
package.json

- fix: we don't support mongodb-core v3.1.10+  (#792)

[1.x] fix: we don't support mongodb-core v3.1.10+ (#792)

---

lib/instrumentation/modules/graphql.js
test/instrumentation/modules/graphql.js

- fix(graphql): don't throw on invalid query  (#747)

[1.x] fix(graphql): don't throw on invalid query (#747)

---

lib/instrumentation/transaction.js

This was introduced by elastic/apm-nodejs-http-client#36 and should ideally be fixed in that repo. For now we fix it here.
Fixes #813

fix: ensure request.url.port is a string on transactions

---

docs/configuration.asciidoc
lib/agent.js
lib/config.js
lib/instrumentation/transaction.js
lib/parsers.js
test/instrumentation/_agent.js
test/parsers.js

Still needs more tests and documentation.
Fixes #739

feat(config): add captureHeaders config

---

docs/api.asciidoc
docs/configuration.asciidoc
docs/setup.asciidoc

Fixes #758, fixes configuration precedence, updates some links from `agent-api` to `configuration`. 
After looking at this a little deeper, it doesn't make sense to nest the `configuration` options within the `Agent API` - it's simply too big.
I'm wondering what you think of this solution. 
In this PR, I've moved the configuration options out of the API reference and into the `Advanced Setup and Configuration` section. Alternatively, I could move the config out of Advanced setup and into the API reference. Either way, the content was being duplicated and it'd be best if it only lived in one place.

[docs] Restructure configuration

---

lib/instrumentation/transaction.js
lib/parsers.js
test/instrumentation/modules/hapi.js
test/parsers.js

The request context parser is actually used in multiple places, so the port fix should be applied centrally.
Fixes #819

fix(parsers): move port fix into parser

---

lib/instrumentation/span.js

This becomes important if we want to support OpenTracing as that makes use of this option.

fix: don't ignore custom trace context on spans

---

docs/agent-api.asciidoc
lib/instrumentation/generic-span.js
lib/instrumentation/index.js
lib/instrumentation/span.js
lib/instrumentation/trace-context.js
lib/instrumentation/transaction.js
test/agent.js
test/instrumentation/span.js
test/instrumentation/trace-context.js
test/instrumentation/transaction.js

Simplify the API for marking a span or transaction as a child of another span or transaction, either local to the process or across processes via the `traceparent` header.
A parent can now be provided either as a Transaction, Span, or TraceContext object, or as a `traceparent` string. And no matter which format the parent is provided in, the parameter name is `childOf`.

refactor: simplify API for resuming traces

---

lib/instrumentation/generic-span.js
lib/instrumentation/trace-context.js
test/instrumentation/trace-context.js

This just makes the code less complex.

refactor: remove sampled property alias from trace context

---

docs/index.asciidoc
docs/opentracing.asciidoc

This is heavily inspired by the [Java agent OpenTracing docs](https://www.elastic.co/guide/en/apm/agent/java/master/opentracing-bridge.html). I've left out the section about the different modes as we don't currently have an easy way to disable auto instrumentation while still being able to manually create spans and transactions.
Here's the location of the new menu item:
Here's how the new page is rendered:

docs: add OpenTracing docs

---

test/_mock_http_client.js

This part of the mock was not actually used in the test suite, so it never failed any tests, but it resulted in some test output log spam.

test(mock): add sendMetricSet to http client mock

---

.tav.yml

The previously passing range of apollo-server-express versions is now failing due to a breaking change in an in-range version of core-js, which it depends on. This excludes that range.
See: https://github.com/apollographql/apollo-tooling/issues/962

test(apollo-server-express): exclude range broken by core-js

---

test/instrumentation/_agent.js

Tests using the agent mock were not exiting properly due to the metrics reporter not being disabled.

ci: fix agent mock metricsInterval

---

package.json

Prior to 4.10, it was possible to create nested tests without needing to call `t.end()`. This was considered a bug and the capability was removed in 4.10, however our test suite is currently heavily dependent on this behaviour.
Fixes #845 
Fixes #846 
Fixes #847 
Related substack/tape#459

ci: pin tape as 4.10 breaks test suite

---

docs/metrics.asciidoc

Move metrics documentation to one page for better readability.
Closes #855.

[docs] Fix metrics docs formatting

---

Jenkinsfile

* Convert the exception always to string before to call error
- [NA] Add tests
- [NA] Update documentation

[APM-CI] some exceptions are not convert to String when you call error step error step

---

lib/metrics/registry.js

Apparently timers with a duration of 0 do not always unref correctly on Node 6. This PR prevents the linux platform stats collector from starting a timer if the given duration is zero.
This was the cause of Jenkins hanging sometimes on Node 6.x.

fix(metrics): prevent 0ms timers from being created

---

lib/lambda.js
test/lambda/mock/agent.js
test/lambda/mock/transaction.js
test/lambda/promises.js

Looks for the `elastic-apm-traceparent` header in the lambda event, using it as the parent transaction ID if it is found.

feat: Accept parent transaction in lambda wrapper

---

package.json

This version includes a fix that ensures that all reported http headers
are always strings or array of strings.
Fixes #888

chore(package): bump elastic-apm-http-client to ^7.1.1

---

test/config.js

This would mostly appear on CI systems, but only sometimes.
This should hopefully fully fix this issue that has been plaguing us for a long time making the tests unstable.

test: fix race condition in custom transport test

---

test/integration/api-schema/basic.js

The span transaction id is no longer a required property

test: fix intake API integration test

---

lib/agent.js

This should improve autocompletion and hints in editors like VS Code.
Here are some example screenshots of how this changes the experience in VS Code:
Gotcha: Because there already exist TypeScript definitions on DefinitelyTyped, those will actually overwrite any in-code hints like these, so if the users editor is set up to download type definitions from DefinitelyTyped, this will not have any effect (related: #917).

chore: make Agent method signatures more explicit

---

package.json

See [commitlint-config-squash-pr](https://github.com/watson/commitlint-config-squash-pr) for details of what extra commit lint rules this PR adds.
The maximum allowed length of a commit message is normally 72 chars. Currently our PR id's have a length of 3 (`764` in the case of this PR). That means that the commit message shouldn't be longer than 65 chars to accommodate the ` (#764)` suffix (72-4-3=65). I've on purpose made the length of this commit message 66 to test that it works. When merging the trailing ` xxxxxxx` should be removed.

test: ensure squashed commit messages doesn't exceed limit

---

docs/span-api.asciidoc

See https://github.com/elastic/docs/pull/724

Add code snippet to fix Asciidoctor link

---

lib/agent.js

Before this, we might have lost context in case the callback was queued internally in the http client (which would often happen).
There's another issue to use AsyncResource in the http client: https://github.com/elastic/apm-nodejs-http-client/issues/48

fix: bind the agent.flush callback

---

Jenkinsfile

* avoid having to change the Jenkinsfile every time we set a pipeline shared library as a stable version to use.
* limit max PR builds per hour to 60
* set quiet period to 10 seconds
* remove flyweight Jenkins nodes
- [N/A] Add tests
- [N/A] Update documentation

ci(jenkins) use current as pipeline shared library version

---

package.json

This release replaces the bunyan reporter with console-log-level. The reason for this is because bunyan has an optional dependency on the dtrace-provider native module. While optional dependencies are generally fine to fail installing, it's problematic with a native module because it may fail to install on Windows due to not having Python installed, which actually fails the entire install process, not just the optional dependency install.
Fixes #900

chore(package): update measured-reporting to 1.41.0

---

lib/agent.js

It has always been specified as optional in the docs, but the code didn't allow it.

fix(agent): allow flush callback to be undefined

---

lib/instrumentation/transaction.js

I found this when I was implementing the TypeScript `.d.ts` file

fix(transaction): don't set transaction result of it's null

---

.npmignore

These two files had been added to `.gitignore` previously, so we should also add them here.
Together with #941, this should clean up our npm build

chore(npm): add missing files to .npmignore

---

package.json

This version includes fixes for AWS Lambda context mutation issues when using the `agent.lambda()` API.

fix(package): bump elastic-apm-http-client to ^7.1.2

---

lib/instrumentation/http-shared.js

This would make the request fail by invalidating the request signature and return this error:
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Brought to my attention by this post: https://discuss.elastic.co/t/aws-s3-getobject-failure-signature-mismatch-while-updating-apm-to-2-x/173275/3

fix: don't add traceparent header to S3 requests

---

lib/instrumentation/http-shared.js
lib/instrumentation/modules/http.js
lib/instrumentation/modules/https.js
test/instrumentation/modules/http/aborted-requests-enabled.js
test/instrumentation/modules/http/outgoing.js

For `http.get` this was broken in Node.js 8 and up
For `https.get` this was broken in Node.js 9 and up
Fixes #953

fix: instrument http/https.get requests

---

docs/configuration.asciidoc
lib/config.js
lib/instrumentation/express-utils.js
lib/instrumentation/transaction.js
package.json
test/config.js

Closes elastic/apm-agent-nodejs#904 
Add usePathAsTransactionName config option.
elastic/apm-agent-nodejs#903 
elastic/apm-agent-nodejs#850

feat(config): add usePathAsTransactionName config option

---

index.d.ts
test/types/index.ts

This callback has always been optional, I just incorrectly marked it as required in the TypeScript `.d.ts` file

fix(ts): handleUncaughtExceptions callback is optional

---

docs/agent-api.asciidoc
docs/index.asciidoc
docs/span-api.asciidoc
docs/transaction-api.asciidoc

Here's a WIP PR that fixes #925. Still lots to clean up, but wanted to get this up.

[docs] Standardize API reference

---

lib/agent.js

Fixes elastic/apm-agent-nodejs#960 
This fix sets the users `package.json` into the `logger.trace` object and also removes any falsy values from the array returned from the _ancestors while loop. 
I believe this also Fixes elastic/apm-agent-nodejs#973

fix(agent): set package.json

---

lib/instrumentation/http-shared.js

The very act of adding a `response` listener to outgoing requests could trigger a memory leak in case the user didn't also attach a `response` listener.

fix: don't add response listener to outgoing requests

---

docs/agent-api.asciidoc
docs/span-api.asciidoc
docs/transaction-api.asciidoc

I left out a few API's as those actually need to list dates when they changed (e.g. the `agent.addFilter()` was added in v0.1.0, but the API changed in v2.0.0). But I didn't want to tackle that in this PR.
I also touched up the new `traceparent` API's to use the new docs layout.

docs: add info about when API's were added

---

index.d.ts
lib/agent.js
test/types/index.ts

The docs specify that `agent.currentTransaction` can return a string or `null`, but in reality, it could return a string or `undefined`. So this PR also updates that API to return `null` in case there's no active span or transaction.

fix(ts): add TypeScript typings for new traceparent API

---

package.json

This fixes a bug where Kubernetes metadata was not correctly sent to the APM Server and hence therefore not associated with the logged transactions, errors etc.

fix(package): bump elastic-apm-http-client to ^7.2.2

---

lib/agent.js

This would happen if no serverUrl was provided and the agent defaulted to localhost:8200.
This is an implementation of a fix described in #794

fix: don't create spans for APM Server requests

---

docs/agent-api.asciidoc
docs/custom-stack.asciidoc
docs/express.asciidoc
docs/fastify.asciidoc
docs/hapi.asciidoc
docs/koa.asciidoc
docs/lambda.asciidoc
docs/redirects.asciidoc
docs/restify.asciidoc
docs/span-api.asciidoc
docs/transaction-api.asciidoc
index.d.ts
lib/agent.js
lib/instrumentation/generic-span.js
lib/instrumentation/span.js
lib/instrumentation/transaction.js
test/agent.js
test/instrumentation/span.js
test/instrumentation/transaction.js
test/integration/api-schema/basic.js
test/types/index.ts

I've renamed tags to labels in the API, as suggested by [ECS](https://github.com/elastic/ecs). This includes renaming in the docs. I'm unsure if the old anchors should be left. Do we want to leave the whole sections in-tact with some sort of deprecation notice? I tried searching the docs for other deprecation warnings and didn't find anything to copy. 🤔 
Fixes #962

chore: rename tags to labels

---

test/_apm_server.js

This fixes the issue with `test/config.js` hanging for a bit after running.

ci: fast-close apm-server mock

---

lib/config.js
package.json
test/config.js

This enables key/value pair configs to also be objects or entries arrays.

feat(config): more flexible key/value pairs

---

docs/agent-api.asciidoc

Implements: elastic/apm#77
~Blocked by: elastic/apm-server#2129~

docs: add tip/warning to labels

---

docs/configuration.asciidoc
lib/config.js
test/config.js

This makes kubernetes environment variables consistent with other agents while not breaking the prior behaviour. We should consider deprecating and removing the old environment variables in the next major.
Fixes #1028

fix(config): do not use ELASTIC_APM_ prefix for k8s

---

lib/instrumentation/index.js
test/instrumentation/index.js

I fixed the event emitter leak described in https://discuss.elastic.co/t/elastic-apm-node-memory-leak/179245 by ensuring calls to remove listeners use the wrapped function when given the unwrapped function.

fix(instrumentation): prevent handler leak in bindEmitter

---

docs/agent-api.asciidoc
docs/index.asciidoc

Fixes elastic/apm-agent-nodejs#932 
I've only just started working with this library so I may have misjudged what some of the options are doing.

docs: document additional capture error options

---

.travis.yml

FYI: This PR is based of a branch in this repo instead of my own so that I could trigger a cron job on Travis to see these tests in action.
You can see the cron job here: https://travis-ci.org/elastic/apm-agent-nodejs/builds/529865281

ci(travis): add Node.js 12 pre-release tests

---

lib/instrumentation/index.js

This PR is a replacement for #957:
> Closes the webpack issue causing https://github.com/elastic/apm-agent-nodejs/issues/955. Personally, I'd just avoid the API where people can define paths at all - it'll never work in bundlers and it just adds additional code. I'm not sure I understand the value except late requires, but that seems negligible.
> 
> Fixes #1048

fix(instrumentation): explicitly use `require`

---

lib/instrumentation/express-utils.js

The `parseurl` module receives a request object while `url.parse` expects to receive the url string. This should fix that. I'm not sure how to test this though, as it loads the url module as a fallback when first running the module. An alternative would maybe be to just add `parseurl` to the dependencies and _always_ use it. 🤔

fix: url.parse expects req.url not req

---

.tav.yml

test(fastify): exclude v2.4.0 from test matrix

---

.travis.yml
docs/scripts/build_docs.sh
package.json

* Fixes https://github.com/elastic/apm-agent-nodejs/issues/1072 by using docker and asciidoctor to build the docs.
* Fixes https://github.com/elastic/apm-agent-nodejs/issues/1071 by removing the docs build from travis
I was bored last night so I played around with this. I think I need your help, not sure what the best way to have a "build" and an "open" script is. In this potential solution I added a `docs:open` script that opens the documentation and a `docs:build` script that just builds it. Not sure what a best practice would be though.

[docs] update npm run docs

---

.travis.yml

Travis was getting to a point where the builds would time out because they reached the two-hour max limit. By splitting the TAV tests into five groups per Node.js version instead of 4, we should hopefully get a little more breathing room.

test(travis): split TAV builds into 5 groups per Node.js version

---

test/script/run_tests.sh

This is required for Jenkins to behave correctly because the output of the tests are piped into a tap parser:
https://github.com/elastic/apm-agent-nodejs/blob/9abb4aa926fdca65e70c570735f8f91985905952/test/script/run_tests.sh#L48

test(jenkins): fail test if part of pipeline fails

---

lib/instrumentation/http-shared.js
package.json
test/instrumentation/modules/http/aws.js

If the outgoing HTTP request is signed with an AWS version 4 signature, this traceparent header will not be added by the agent.
Fixes #1055

fix: don't add traceparent header to signed AWS requests

---

lib/instrumentation/express-utils.js
test/instrumentation/modules/express-graphql.js
test/instrumentation/modules/express/basic.js
test/instrumentation/modules/graphql.js

Previously all `app.use()` routes would be treated as unknown routes. With this commit, only the following routes will be considered unknown:
- `app.use(fn)`
- `app.use('/', fn)`
All other routes, e.g. `app.use('/foo', fn)`, will have their transactions named accordingly. Note that the HTTP method will still be part of the transaction name, even if the route is defined using `app.use()`. I.e. `GET /foo` and `POST /foo` will be part of two different transaction groups even though they might be served by the same router function.
Fixes elastic/apm-agent-nodejs#1008

fix(express): improve names for routes added via app.use()

---

lib/metrics/platforms/linux/index.js
lib/metrics/platforms/linux/stats.js
lib/metrics/registry.js

CPU usage metrics are reported to the APM Server at a set interval. Instead of looking at the time spend on CPU since the last reporting, the CPU usage metrics on Linux only looked at the last 100th fraction of that time. E.g. if reporting metrics every 10 seconds (the default), the CPU usage numbers in each reporting would only cover the last 100ms - leaving a big gap of 9900ms unreported.
In reality, the entire 10 seconds was calculated, but in chunks of 100ms. And only the calculation for the last 100ms interval was kept. So not only was the data from the 9900ms lost, it also incurred an
unnecessary calculation overhead. This overhead is now also avoided.
Fixes #1068 
(snuck in some minor unrelated cleanup as will - hope you don't mind)

fix(metrics): report correct CPU usage on Linux

---

.tav.yml

To avoid merge conflicts, this PR doesn't add set-framework tests for Express as that's taken care of in #1111

test(tav): add set-framework tests to tav test matrix

---

test/script/run_tests.sh

This PR fixes the following CI error:
```
Fail! Modules in package.json not used in code: tap-junit
```
If during CI, `npm install` is run without the `-g` flag, the agents dependencies are updated. This might introduce hard to debug errors or as in this case fail the tests.

ci(jenkins): don't pollute package.json with tap-junit

---

Jenkinsfile

This is a replacement for #1115. The only difference is that this PR is against `master` instead of `2.x`

ci(jenkins): new notifications and reports to Elasticsearch

---

.travis.yml

This will not trigger until in master, so there's no need to wait for passing tests

ci(travis): add Node.js v12 nightly (no async hooks) build

---

.npmignore

We forgot to add this when the `.ci` folder was added

chore: add .ci folder to .npmignore

---

test/integration/api-schema/download-json-schemas.sh

These broke because 4 new files were added in:
https://github.com/elastic/apm-server/pull/2265

test: fix broken intake API schema tests

---

Jenkinsfile

- It will enable to use the integrations tests either from pull requests which are coming from a forked repo or from this one.

ci(jenkins): enable pull requests using the upstream repo

---

.ci/jobs/apm-agent-nodejs-downstream.yml
.ci/jobs/apm-agent-nodejs-mbp.yml
.ci/jobs/defaults.yml

- periodic-folder-trigger has now defaulted for the main pipeline.
- Suppresses automatic SCM triggering for the main pipeline.
- https://docs.openstack.org/infra/jenkins-job-builder/project_workflow_multibranch.html

ci(jenkins): disable builds in jenkins

---

.ci/jobs/apm-agent-nodejs-schedule-daily.yml
.ci/jobs/apm-agent-nodejs-schedule-weekly.yml
.ci/schedule-daily.groovy
.ci/schedule-weekly.groovy
Jenkinsfile

Right now, we have the cron task configured on the Jenkins file, this means that every branch and PR uses these settings, so we launch ever branch and PR every day. We want only to launch on daily period only the master branch so we would schedule the task on a special job for that. From here we can schedule daily or weekly whatever we want on a controlled way.
* Daily scheduled job
* Weekly scheduled job
* remove cron from the Jenkinsfile

ci(jenkins): move schedule to a scheduler job

---

.npmignore
dev-utils/docker-compose.yml
package.json

This command will run a temporary Docker container with access to the root of your local agent directory and place you in a bash shell inside it.
This allows you to test things in a Linux environment when you're not running Linux yourself.

chore: add 'npm run docker:dev' to open cwd in Docker

---

docs/supported-technologies.asciidoc
lib/instrumentation/modules/knex.js

Knex v0.18.0 was just released, and as has come apparent in #1184, we don't yet support this version.
The issue is in this line:
https://github.com/elastic/apm-agent-nodejs/blob/fe8ff8ac6c71a6a21ba7e0dd787e570e6655f498/lib/instrumentation/modules/knex.js#L36
The `runner` object no longer have a `query` function in knex v0.18.0 and above.

fix(knex): abort early on unsupported version of knex

---

.ci/docker/node-container/Dockerfile
.ci/scripts/docker-test.sh

Node.js 6 is failing to install `http-signature`, locally with docker failed in the same package, outside Docker fails on an optional dependency and can continue, it is a little bit erratic. So I have forced to install `npm@6.9.0` (latest is 6.10.0) and it works so there is something that breaks the `npm install` on `Node.js 6` and `npm@6.10.0`
```
node_tests_1     | 801 http fetch GET 304 https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz 84ms (from cache)
node_tests_1     | 802 silly fetchPackageMetaData error for http-signature@^1.2.0 zlib: zlib binding closed
```
this start happens 6 days ago that it is the same date that npm@6.10.0 was release.

fix: use npm@6.9.0 fixed version for Node.js < 8

---

.gitignore

This was added in a commit (see https://github.com/elastic/apm-agent-nodejs/commit/d8351ffffe0ce981890dff652b8143146b068bf4#commitcomment-34232598). This file shouldn't exist though. If it comes back, we should look into why and fix the root cause.

chore: clean .gitignore

---

.ci/downstreamTests.groovy

user error step, allow empty junit results

fix: user error step, allow empty junit results

---

.ci/jobs/apm-agent-nodejs-schedule-weekly.yml

The weekly job points to the library repo it is not correct.

ci(jenkins): set Node.js repo for weekly job

---

.ci/jobs/apm-agent-nodejs-mbp.yml
.ci/jobs/defaults.yml

- Enable polling once a day even though it's push-based.
- Enable scm triggering for the PRs as it used to be.

ci(jenkins): enable polling for change request/branches

---

.ci/jobs/apm-agent-nodejs-mbp.yml

- This is the way to exclude the greenkeeper branches. See the below screenshot as the outcome of applying this change.

ci(jenkins): exclude greenkeeper branches

---

Jenkinsfile

Since the documentation team has elastic-ci/docs build in place for all our PRs, our Documentation stage lose sense, we are doing the same and we have to maintain it. Because of that, we will start to remove this stage from all projects.

ci(jenkins): remove the documentation stage

---

docs/metrics.asciidoc
lib/config.js
lib/instrumentation/span.js
lib/instrumentation/timer.js
lib/instrumentation/transaction.js
lib/metrics/index.js
lib/metrics/registry.js
lib/metrics/reporter.js
package.json
test/_mock_http_client.js
test/instrumentation/github-issue-75.js
test/instrumentation/index.js
test/metrics/breakdown.js
test/sourcemaps/index.js

This expands the timer and transaction classes to enable capturing breakdown graph metrics. I don't really like the flatten/unflatten thing, but I'm not sure there's a better way, since measured doesn't support the nested dimensions we need to separate transaction and span data. 🤔 
Closes #1064

feat(metrics): breakdown graphs

---

lib/agent.js
lib/instrumentation/generic-span.js

The previous implementation would spam the logs if one of these functions were called one or more times per request for instance.
While you're sure to get peoples attention by this, it's also super annoying for the user, which wasn't the intention. So this PR dials it down a bit.

fix: only log deprecation warning once per function

---

.travis.yml

Travis CI recipe to cache elasticsearch-6.6.0.deb to make builds more resilient to network connectivity issues.

ci(travis): cache elasticsearch deb

---

package.json

v3.3.0 doesn't support Node.js 6 anymore.

chore: pin wait-on to 3.2.0

---

.travis.yml

The npm cache used to be off by default on Travis, but since July 2019 they changed it to be on by default. This hides errors in our tests as updated to dependencies are no longer installed.
For details see:
https://docs.travis-ci.com/user/caching/#npm-cache

ci(travis): disable npm cache

---

docs/setup.asciidoc

[docs] Add information for explicitly calling `apm.start()`

---

Jenkinsfile

- Nothing about the smart TV but adding more verbose output when running the smartTAV.
- Caused by https://github.com/elastic/apm-agent-nodejs/pull/1144#issuecomment-519472951
- `changeRequest()` method is not allowed within the steps but within the when sections. 
- changeRequest is not returning a boolean.
```
[2019-08-08T13:29:06.337Z] env.GITHUB_COMMENT=null
[2019-08-08T13:29:06.337Z]    params.Run_As_Master_Branch=false
[2019-08-08T13:29:06.337Z]    changeRequest()=@changeRequest()
[2019-08-08T13:29:06.337Z]    env.TAV_UPDATED=false
```
- There is a potential use case to refactor this particular method and then provide a shared library step. The reason, our lovely shared library does use the JUnitPipeline framework, so, therefore, more test coverage. Meanwhile, let's use this PR to …

ci(jenkins): more debug output for smartTAV

---

docs/supported-technologies.asciidoc

Somehow we had it listed with the name `elasticsearch-js`. I guess this link has never worked.

docs: fix invalid link to elasticsearch npm package

---

lib/instrumentation/span.js

The same error was accidentally logged twice (once on the `debug` level and once on the `warning` level). We decided in #1261 to only log on the `debug` level.

fix: be less chatty if span stack traces cannot be parsed

---

lib/agent.js
lib/config.js
lib/instrumentation/generic-span.js
lib/instrumentation/http-shared.js
lib/instrumentation/index.js
lib/instrumentation/modules/express-graphql.js
lib/instrumentation/modules/express.js
lib/instrumentation/modules/graphql.js
lib/instrumentation/patch-async.js
lib/instrumentation/shimmer.js
lib/instrumentation/span.js
lib/instrumentation/transaction.js
lib/metrics/platforms/generic/index.js
lib/metrics/platforms/linux/index.js
lib/metrics/platforms/linux/stats.js
lib/metrics/reporter.js
lib/metrics/runtime.js
lib/parsers.js
test/integration/skip-internal-http-spans.js

Changed all uses for `forEach` inside of the `lib` folder to be for-of loops. I left out two instances as they looked better with `forEach`:
- https://github.com/elastic/apm-agent-nodejs/blob/245aa4520ced15e1932bd7d79507739d27090c2f/lib/filters/http-headers.js#L24
- https://github.com/elastic/apm-agent-nodejs/blob/245aa4520ced15e1932bd7d79507739d27090c2f/lib/filters/http-headers.js#L34
There's still quite a few uses of `forEach` in the tests but I didn't feel the need to change those. Let me know if we should do that (though many of those use the `index` argument of the `forEach` callback, so I don't think it's worth it).
I also changed all uses of `let` in existing for-of loops to `const` where possible.

perf: use for-of instead of forEach

---

.ci/scripts/get_tav.sh

- Support `@folder/module` format as requested with: https://github.com/elastic/apm-agent-nodejs/pull/1266
- Return a sorted and unique list of TAV modules.
- `CHANGE_TARGET=master GIT_SHA=c4a81ae4a258b447de60bb6eb6f79c1454720b2d .ci/scripts/get_tav.sh /tmp/file.txt`
```
TAV:
- @elastic/elasticsearch
- elasticsearch
- hapi
```
- `CHANGE_TARGET=v2.12.0 GIT_SHA=2cd65f2283c0e3da1b02ba21dc047e10ef044efc .ci/scripts/get_tav.sh /tmp/file.txt`
```
TAV:
- apollo-server-express
- bluebird
- cassandra-driver
- elasticsearch
- express
- express-graphql
- express-queue
- fastify
- finalhandler
- generic-pool
- graphql
- handlebars
- hapi
- http
- http2
- ioredis
- jade
- knex
- koa
- koa-router
- mimic-response
- mongodb-core
- mysql
- mysql2
- pg
- pug
- redis
- restify
- tedious
- ws
```
NOTE: I …

ci(jenkins): support for @path/module in smart tav

---

Jenkinsfile

- Async hooks false branches run in parallel, aka less waste of time for getting feedback.
- Nodejs-6.x with async hook false is disabled.
- `generateStep` is now responsible to inject the `ELASTIC_APM_ASYNC_HOOKS` if `disableAsync` parameter is true. The default behavior as used to be, aka without the env variable.
- Nodejs6.X for async configuration is not enabled

ci(jenkins): async hook false runs in parallel

---

lib/agent.js
lib/config.js
lib/instrumentation/http-shared.js
lib/instrumentation/modules/elasticsearch.js
lib/instrumentation/modules/http2.js
lib/instrumentation/transaction.js
lib/metrics/platforms/linux/stats.js
lib/metrics/reporter.js
test/config.js
test/instrumentation/modules/http/aws.js
test/instrumentation/modules/mongodb-core.js
test/instrumentation/transaction.js
test/metrics/breakdown.js
test/metrics/index.js
test/parsers.js
test/script/cli.js
test/test.js

We can't upgrade to the new version of 'standard' currently because we still use the deprecated `url.parse` API in several locations (see issue no #1254). But to ensure fewer merge conflicts between the 2.x and the upcoming 3.x branch), we'll fix as many future linting issues as possible already now.

chore: prepare code style for new version of linter

---

package.json

This includes a fix for an issue where stack traces would not be captured in situations where `Error.prepareStackTrace` was overwritten after this module was loaded.
A common culprit for this is the [`source-map-support`](https://www.npmjs.com/package/source-map-support) module, used by - among others - [`@babel/register`](https://www.npmjs.com/package/@babel/register).
Fixes #369

fix(package): bump stackman to ^4.0.0

---

lib/agent.js
test/config.js

Previously, the agent would log the following message on the info level if `active: false`:
Elastic APM agent is inactive due to configuration
This proved problematic for CLI applications that ships with the agent turned off by default.
In cases where `active` is set to `false` on purpose, it shouldn't be necessary to log this message on the info level, instead we now log this more specific message on the debug level:
Elastic APM agent disabled (`active` is false)

fix: change agent active status log message to debug level

---

.ci/downstreamTests.groovy
Jenkinsfile

- `master` worker could be used but causes bottlenecks in some cases.
- This will allow to use of another worker and get rid of any potential bottlenecks when the build queue is massive.

ci(jenkins): avoid builds in the master worker

---

lib/instrumentation/async-hooks.js
test/instrumentation/async-hooks.js

This fixes an issue discovered in #1298 due to changing the `test/_agent.js` file to use a _real_ config object rather than a mock, which exposed that the mock would implicitly have `asyncHooks: false` in its settings by omission.

fix(async_hooks): properly update sync flag

---

docs/configuration.asciidoc
docs/setup.asciidoc
lib/config.js

This is required to land elastic/kibana#43548

feat: add configFile config option

---

.ci/downstreamTests.groovy
Jenkinsfile

This reverts commit 8b585c6814796d87203c031ede6a4ed9d959a66c.
- As long as we use the share step `gitCheckout` we might need to use the agent top-level to share the env variables between stages.
- It's not ideal but even though the changes were quite straight, its behavior was not as expected. 
- Let's keep the pipeline stable for now and we will figure out what's going on.

Revert "ci(jenkins): avoid using the any to skip the master (#1304)"

---

lib/lambda.js
test/lambda/promises.js

Headers coming from API Gateway to Lambda may not be
lowercase, so when extracting the elastic-apm-traceparent
header, compare case-insensitively.
Fixes #1315

fix(lambda): handle traceparent case-insensitively

---

.ci/jobs/apm-agent-nodejs-downstream.yml
.ci/jobs/apm-agent-nodejs-mbp.yml

it will replace the generic context `continuous-integration/jenkins/*` for a fixed one that points to the name of the instance that generates the context `apm-ci`, it is important when we have multiple multibranch jobs listening on a repo to avoid to overwrite contexts.
**Now**
**After**

ci(jenkins): Set GitHub notification context to apm-ci

---

.ci/schedule-daily.groovy

The `Run_As_Master_Branch` parameter is the one in charge to manage what stages are enabled/disabled. PRs do not run all the stages but branches should run all of them.
In other words, TAV stage will be enabled on a daily basis for the master branch which it's handled within the daily job.

ci(jenkins): run all the stages

---

lib/instrumentation/http-shared.js

As discovered in #1298, context propagation breaks in the http response handler on Node.js 12.0 to 12.2. This ensures that continuation is restored.

fix(http): response context propagation on Node.js 12.0 - 12.2

---

lib/instrumentation/index.js

The patches are not called with the four arguments `exports`, `name`, `version`, and `enabled`, but instead with three arguments: `exports`, `agent`, `options`.
However, this worked fine previously because we were just passing the arguments straight through to the patch function. But it made reading the code very confusing.

chore: fix patch method argument names

---

lib/instrumentation/express-utils.js
lib/instrumentation/http-shared.js
lib/instrumentation/modules/http2.js
lib/parsers.js

feat: change code to use url.URL instead of url.parse

---

Jenkinsfile

- Enforce the TAV module when using GitHub comments as stated in https://github.com/elastic/apm-agent-nodejs/pull/1346#issuecomment-531694730
- Replace any `'` or `"` within the GitHub comment and single quote those modules afterward.
```
node {
def modules = [ 'bla', '@foo/bar', '"@foo/bar"', "'@foo/bar'"]
def tav = readYaml(text: """TAV:${modules.collect{ it.replaceAll('"', '').replaceAll("'", '') }.collect{ "\n  - '${it}'"}.join("") }""")    
echo """TAV:${modules.collect{ it.replaceAll('"', '').replaceAll("'", '') }.collect{ "\n  - '${it}'"}.join("") }"""
echo "$tav"
}
```
caused
```
[Pipeline] readYaml
[Pipeline] echo
TAV:
- 'bla'
- '@foo/bar'
- '@foo/bar'
- '@foo/bar'
[Pipeline] echo
[TAV:[bla, @foo/bar, @foo/bar, @foo/bar]]
```

ci(jenkins): tav with different formats

---

.ci/scripts/get_tav.sh

Previously if there was a change to any of our patches for a Node.js core modules (e.g. `http`), Jenkins would try to run TAV tests for the `http` module. This is just a waste of resources as there are no TAV tests for core modules.
This commit will filter out any core module from the list of modules being considered for TAV tests.

ci(jenkins): don't run TAV tests for Node.js core modules

---

docs/agent-api.asciidoc
docs/span-api.asciidoc
docs/transaction-api.asciidoc
lib/agent.js
lib/instrumentation/ids.js
lib/instrumentation/index.js
lib/instrumentation/span.js
lib/instrumentation/transaction.js
test/agent.js
test/instrumentation/span.js
test/instrumentation/transaction.js

This enables logging spans and transactions in a string form
which can be used for log correlation.

feat: add toString methods for logging

---

.ci/scripts/get_tav.sh
lib/instrumentation/modules/http.js

- TAV file should be always created even when no matches.

ci(jenkins): create the yaml header

---

test/_apm_server.js

It would throw an error when trying to access `requests[0]` later in the function if no `mockOpts` object was provided. This made it hard to debug certain things.

test: allow mock APM Server to be initiated without args

---

test/_apm_server.js
test/_promise_rejection.js
test/instrumentation/modules/bluebird/bluebird.js
test/test.js

If the function given to `getPort().then()` accidently threw a syncrounous error in Node.js versions earlier than 6.6.0, we would never know about it and the tests would just fail in weird ways that would take hours to debug.
This commit ensures to log that error and exit the process with a non-zero exit code.
For Node.js version 12+ all tests are run with `--unhandled-rejections=strict` to ensure they crash in case of an unhandled rejection instead of just emitting a warning.
For Node.js versions less than 12, a global `unhandledRejection` listener is added for each test file being run through `test/test.js`.

test: don't swallow promise rejections during test

---

lib/instrumentation/http-shared.js
lib/instrumentation/modules/http2.js
test/instrumentation/modules/elasticsearch.js
test/instrumentation/modules/http2.js

Rather than the shortened 'ext' use full 'external' in span types
Fixes #1225

feat: use external as span type

---

docs/configuration.asciidoc
index.d.ts
lib/config.js
lib/instrumentation/modules/http.js
lib/instrumentation/modules/http2.js
lib/instrumentation/modules/https.js
test/config.js
test/instrumentation/_agent.js
test/instrumentation/index.js
test/instrumentation/modules/http/disabling.js

PR for splitting disabling of outgoing http requests from incoming http requests.
Closes elastic/apm-agent-nodejs#434

feat(http): add monitorIncomingHTTPRequests config

---

test/instrumentation/modules/http/disabling.js

The PR #1298 introduced a bug in the tests as it expected the span.type for outgoing http requests to start with `ext.*`. This was changed to `external.*` in the PR #1291, but #1298 was just never updated to be up to date with master before it was merged.

test: fix http disabling test

---

lib/instrumentation/async-hooks.js
test/_agent.js
test/config.js

This was all the code that came out of trying to solve a weird CI related issue in #1114.
I thought it was best to submit it as a separate PR in case we want to backport it.

test: ensure proper cleanup between config tests

---

lib/parsers.js
test/parsers.js

fix(parsers): ensure non-string bodies are converted

---

.backportrc.json
CONTRIBUTING.md
package.json

The commit no longer requires you to have the backport tool installed globally.

chore: update backport tooling and docs

---

docs/configuration.asciidoc
lib/instrumentation/index.js
test/_mock_http_client.js
test/config.js

Fixes elastic/apm-agent-nodejs#858

feat: allow manual instrumentation when instrument is set to false

---

docs/supported-technologies.asciidoc

mongodb 3.3+ no longer uses mongodb-core, so it needs to be instrumented directly.
Several libraries have already updated to the 3.x line and therefore are not
currently supported.
Fixes #1369

docs: set upper bounds for current mongo support

---

docs/supported-technologies.asciidoc

- docs: set upper bounds for current mongo support (#1375)

[2.x] docs: set upper bounds for current mongo support (#1375)

---

lib/instrumentation/async-hooks.js
test/_agent.js
test/config.js

- test: ensure proper cleanup between config tests (#1373)

[2.x] test: ensure proper cleanup between config tests (#1373)

---

lib/parsers.js
test/parsers.js

- fix: capture all non-string http bodies (#1376)

[2.x] fix: capture all non-string http bodies (#1376)

---

.ci/scripts/test_types_babel_esm.sh
package.json
test/esm/index.mjs
test/script/run_tests.sh

I found this bug in the tests while working on #1383.
I've created it as a separate PR so we can backport it to `2.x`.
Once merged, #1383 can be rebased against master.

ci: run esm tests on all 9+ Node.js versions

---

.ci/schedule-daily.groovy

- Enable the pipeline for the `2.x` branch on a daily basis.
- To clarify the benchmark stage only runs when a new commit is merged into the `master` branch.

ci(jenkins): 2.x branch on a daily basis

---

.ci/scripts/test_types_babel_esm.sh
package.json
test/esm/index.mjs
test/script/run_tests.sh

- ci: run esm tests on all 9+ Node.js versions (#1387)

[2.x] ci: run esm tests on all 9+ Node.js versions (#1387)

---

lib/agent.js
test/agent.js

Previously, an error would be thrown if the user returned either `null` or `undefined` from a filter if the event being filtered was an error.
Fixes #1385

fix: support all falsy return values from error filters

---

lib/agent.js
test/agent.js

- fix: support all falsy return values from error filters (#1389)

[2.x] fix: support all falsy return values from error filters (#1389)

---

docs/configuration.asciidoc

- docs: add missing breakdownMetrics option (#1395)

[2.x] docs: add missing breakdownMetrics option (#1395)

---

docs/span-api.asciidoc

- docs: fix 'added in' for span API docs (#1397)

[2.x] docs: fix 'added in' for span API docs (#1397)

---

test/instrumentation/modules/http/aborted-requests-enabled.js

This test has a tendency to get stuck on Jenkins and never complete. Instead of waiting 3 hours until Jenkins times out, we'll just time out the test after 10 seconds.
Obviously this doesn't fix the issue but merely stops us from consuming Jenkins resources.

ci(jenkins): time out problematic test if running too long

---

docs/agent-api.asciidoc
docs/transaction-api.asciidoc

Same fix as #1397 but in different files.
I should have checked when I fixed the Span API docs if there were more than that occurrence but it didn't occur to me until later. This should be the last of them.

docs: fix 'added in' for transaction+agent API docs

---

CHANGELOG.md

@bmorelli25 as [you suggested](https://github.com/elastic/apm-agent-nodejs/pull/1388#discussion_r328062588), here's the first changelog PR as a result of a new release in the `2.x` branch.

docs(changelog): update changelog from 2.x branch

---

Jenkinsfile

This is a replacement for #1374 to not suppress any errors on Node.js 6 in the `2.x` branch.

ci(jenkins): don't suppress Node.js 6 errors

---

docs/agent-api.asciidoc
docs/transaction-api.asciidoc

- docs: fix 'added in' for transaction+agent API docs (#1399)

[2.x] docs: fix 'added in' for transaction+agent API docs (#1399)

---

test/instrumentation/modules/http/aborted-requests-enabled.js

- ci(jenkins): time out problematic test if running too long (#1400)

[2.x] ci(jenkins): time out problematic test if running too long (#1400)

---

test/instrumentation/modules/http/aborted-requests-enabled.js

- ci(jenkins): end test properly even if it times out (#1409)

[2.x] ci(jenkins): end test properly even if it times out (#1409)

---

lib/instrumentation/express-utils.js
lib/instrumentation/http-shared.js
lib/instrumentation/modules/http2.js
lib/parsers.js
test/central-config-enabled.js

All supported versions of Node.js now supports the new `url.URL` API.

chore: don't use parseUrl fallback anymore

---

docs/agent-api.asciidoc
docs/redirects.asciidoc
docs/span-api.asciidoc
docs/transaction-api.asciidoc
docs/upgrade-to-v3.asciidoc
index.d.ts
lib/agent.js
lib/instrumentation/generic-span.js
test/agent.js

BREAKING CHANGE: The following deprecated APIs has been removed:
- `apm.setTag()`
- `apm.addTags()`
- `transaction.setTag()`
- `transaction.addTags()`
- `span.setTag()`
- `span.addTags()`

chore: remove deprecated APIs

---

.ci/scripts/test_basic.sh
test/lint-commits.sh

Closes https://github.com/elastic/apm-agent-nodejs/issues/1407
- Enable support to Jenkins using https://github.com/elastic/apm-agent-nodejs/pull/1325/files#diff-04fe4fa9c5ef3988af8ec44be5151292 in addition.
- https://github.com/elastic/apm-agent-nodejs/pull/1416/commits/af4e267f0da883b86c9499676e5edfd9431dd44f caused a lint error, see [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-linting-mbp/detail/PR-1416/4/pipeline)
```
[2019-09-30T10:48:07.919Z] + commitlint --from=origin/master --to=af4e267f0da883b86c9499676e5edfd9431dd44f
[2019-09-30T10:48:08.490Z] ⧗   input: Trigger notification to test the commit-lint
[2019-09-30T10:48:08.490Z] ✖   subject may not be empty [subject-empty]
[2019-09-30T10:48:08.490Z] ✖   type may not be empty …
```

ci(jenkins): enable commit lint

---

lib/instrumentation/http-shared.js
lib/instrumentation/modules/http.js

I wrapped `req._headers` calls in a ternary operator to not access `req._headers` in Node 12.x and above.
REF: elastic/apm-agent-nodejs#1073

workaround(s) to suppress DEP0066 warnings

---

.ci/downstreamTests.groovy
.ci/linting.groovy
Jenkinsfile

- Let's reuse the top-level agent to reduce the number of fo requested agents and speed up just a bit the builds.
- Reset labels to be `linux && immutable` to help with what kind of OS is required to be used.
- Time improvements per Stage
- From the very beginning to the tests stage used to take ~3 minutes and now 1.30 minutes.
- TAV stage doesn't require a new worker, so roughly another 1minute approx of improvement.
- TAV has been launched explicitly with the comment: https://github.com/elastic/apm-agent-nodejs/pull/1425#issuecomment-538056979

ci(jenkins): reuse top level agent

---

docs/configuration.asciidoc
lib/config.js
test/config.js
test/uncaught-exceptions/log-uncaught-exceptions-off.js
test/uncaught-exceptions/log-uncaught-exceptions-on.js

Even though it would be best to log stack traces of uncaught exception to STDERR by default, this would be a breaking change. To land this feature in the current major, we'll change the default to be `false`.

fix: change logUncaughtExceptions default to false

---

lib/instrumentation/generic-span.js
lib/instrumentation/span.js
lib/instrumentation/transaction.js

- perf: cache 'ids' value of transactions and spans (#1434)

[2.x] perf: cache 'ids' value of transactions and spans (#1434)

---

docs/agent-api.asciidoc
docs/configuration.asciidoc
docs/custom-spans.asciidoc
docs/custom-stack.asciidoc
docs/custom-transactions.asciidoc
docs/express.asciidoc
docs/fastify.asciidoc
docs/hapi.asciidoc
docs/index.asciidoc
docs/intro.asciidoc
docs/koa.asciidoc
docs/lambda.asciidoc
docs/log-correlation.asciidoc
docs/opentracing.asciidoc
docs/redirects.asciidoc
docs/restify.asciidoc
docs/set-up.asciidoc
docs/setup.asciidoc
docs/shared-set-up.asciidoc
docs/source-maps.asciidoc
docs/supported-technologies.asciidoc

WIP. For https://github.com/elastic/apm-agent-nodejs/issues/1427.
This PR accomplishes the following:
* Use shared version attributes
* Rename the APM UI to "APM app"
* Updates to the new documentation structure
* Adds a top level heading for log correlation
* Adds a section on how the Agent does instrumentation
* Closes #1023 (duplication in getting started pages).
New layout (only one link changes)

[docs] Documentation restructure

---

lib/instrumentation/http-shared.js
test/instrumentation/modules/http/aborted-requests-enabled.js

This fixes a race condition that in some cases meant that a request transaction was never ended if the underlying TCP socket was closed by the client and the server didn't discover this in time.
Fixes #1411

fix: always end transaction when socket is closed prematurely

---

CHANGELOG.asciidoc
docs/redirects.asciidoc
docs/release-notes.asciidoc

Backports:
* [docs] Add release notes to documentation #1435.
**Must merge concurrently with https://github.com/elastic/docs/pull/1271.**

[2.x] docs: add release notes to documentation (#1435)

---

lib/instrumentation/http-shared.js
test/instrumentation/modules/http/aborted-requests-enabled.js

- fix: always end transaction when socket is closed prematurely (#1439)

[2.x] fix: always end transaction when socket is closed prematurely (#1439)

---

lib/instrumentation/modules/tedious.js

In 6.5, tedious began using a version of TypeScript which locks property descriptors of exports. This prevents us from being able to re-assign functions with shimmer.
Fixes #1472

fix(tedious): support 6.5+

---

lib/instrumentation/modules/graphql.js
package.json

Instead of relying on that the `__esModule` is the only property that not enumerable, use the smarter `shallow-clone-shim` module to ensure the clone is identical while still shimming the getters for `graphql` and `execute`.

refactor: use smarter shimming of graphql module

---

lib/instrumentation/transaction.js
test/metrics/breakdown.js

The `transaction.breakdown.count` value in metricsets should not be reported when breakdown metrics are disabled. This issue was discovered in #1460.

fix(metrics): do not send transaction breakdowns when disabled

---

lib/instrumentation/modules/tedious.js

Depends on #1476 (so that `shallow-clone-shim` is available)
Ensure that the tedious module is copied faithfully so that the interface of the shimmed module is as identical to the original module as possible.
The old implementation would convert getters to their returned values and would not copy non-enumerable values. The new implementation copies both enumerable and non-enumerable values and preserves getters and setters.

fix(tedious): ensure shimmed module exposes same API

---

.ci/docker/docker-compose-node-edge-test.yml

The edge test stuff missed an environment variable for memcached. The instrumentation for memcached landed around the same time, so I think it was just overlooked when merging the two.

ci(memcached): ensure host env var is available in edge tests

---

lib/instrumentation/http-shared.js
lib/instrumentation/modules/http2.js
lib/instrumentation/span.js
package.json
test/instrumentation/modules/http/outgoing.js
test/instrumentation/modules/http2.js
test/instrumentation/span.js

feat(http,http2): add http context info

---

lib/instrumentation/modules/tedious.js

- fix(tedious): support 6.5+ (#1473)

[2.x] fix(tedious): support 6.5+ (#1473)

---

lib/instrumentation/transaction.js
test/metrics/breakdown.js

- fix(metrics): do not send transaction breakdowns when disabled (#1466)

[2.x] fix(metrics): do not send transaction breakdowns when disabled (#1466)

---

.ci/docker/docker-compose-node-edge-test.yml

- ci(memcached): ensure host env var is available in edge tests (#1484)

[2.x] ci(memcached): ensure host env var is available in edge tests (#1484)

---

lib/instrumentation/modules/graphql.js
package.json

- refactor: use smarter shimming of graphql module (#1476)

[2.x] refactor: use smarter shimming of graphql module (#1476)

---

lib/instrumentation/modules/tedious.js

- fix(tedious): ensure shimmed module exposes same API (#1477)

[2.x] fix(tedious): ensure shimmed module exposes same API (#1477)

---

lib/instrumentation/modules/knex.js
lib/instrumentation/shimmer.js
test/instrumentation/modules/pg/knex.js

I figured out how to get stack traces working properly in knex. It was a result of knex switching from Bluebird to native promises in 0.18. In the process, they also switched to using async functions, which our version of shimmer apparently was unable to patch correctly because it used a `toString()` check to identify functions rather than a simple `typeof`, and async functions have a different name than regular functions.

fix(knex): make stack traces work in 0.18+

---

docs/configuration.asciidoc
lib/config.js
package.json
test/config.js

feat(config): add serviceNodeName

---

lib/instrumentation/modules/knex.js
lib/instrumentation/shimmer.js

- fix(knex): make stack traces work in 0.18+ (#1497)

[2.x] fix(knex): make stack traces work in 0.18+ (#1497)

---

docs/lambda.asciidoc
docs/set-up.asciidoc

Adds a note to the documentation that Lambda functions are no longer supported.
Closes https://github.com/elastic/apm-agent-nodejs/issues/1511.

docs: deprecate lambda support

---

docs/lambda.asciidoc
docs/set-up.asciidoc

- docs: deprecate lambda (#1513)

[2.x] docs: deprecate lambda (#1513)

---

lib/metrics/registry.js

If metrics are disabled (metricsInterval is 0), then we should not register any collectors.
Later we might want to make this dynamic, starting/stopping collectors in response to dynamic changes to the metricsInterval value made via central config. For now, let's just fix the bug.
The runtime collector creates a loop delay monitor which will accumulate data while enabled until it is either disabled or reset. As we only reset the monitor when collecting metrics, starting the collector without later calling its "collect" method would lead to unbounded memory growth.
Closes https://github.com/elastic/apm-agent-nodejs/issues/1515

fix(metrics): only register collectors if enabled

---

lib/instrumentation/modules/ioredis.js
test/instrumentation/modules/ioredis.js

Fixes #1518
The use of `finally` without updating `command.promise` causes a bifurcation. The onFinally handler will rethrow, and nothing can catch it, leading to an unhandled promise rejection.
Let's simplify the code a bit, and just use `.then` regardless, which avoids this issue.

fix(ioredis): prevent unhandled promise rejection

---

.ci/Jenkinsfile

The signature for isGitRegionMatch has been changed to support different comparators, such as glob or regexp. By default glob is the comparator.
This should be merged only once the library has been released. Likely sometime this week.

ci(jenkins): update argument

---

package.json

~- [ ] Add tests~
CI has already been updated to test against Node 13 in https://github.com/elastic/apm-agent-nodejs/pull/1464
Closes #1516

chore: add Node 13 to supported engines

---

README.md

It adds Jenkins badge for the 2.x branch
We want to keep al projects in sync in terms of CI, so that we can be even more transparent about the status of the project.

ci(jenkins) Add Jenkins badge for 2.x branch

---

README.md

It adds Jenkins badge for the master branch, fixing the URL for Travis CI
We want to keep al projects in sync in terms of CI, so that we can be even more transparent about the status of the project.

ci(jenkins) Update CI badges

---

.travis.yml

Fixes elastic/apm-agent-nodejs#1532

ci(travis): don't update npm to latest version

---

package.json

Bumping non-dev-dependencies in separate PR's to make a future `git bisect` easier in case any of these has unforeseen side-effects

fix(package): bump shallow-clone-shim to ^2.0.0

---

package.json

Bumping non-dev-dependencies in separate PR's to make a future `git bisect` easier in case any of these has unforeseen side-effects

fix(package): bump semver to ^6.3.0

---

README.md

As discussed in #1530, Travis' master branch badge must point to latest release: 3.x

ci(jenkins): Use 3.x branch for CI badges

---

.ci/docker/docker-compose-edge.yml

This PR adds memcached to the docker-compose used in edge tests
Tests are failing because of this reason, although they bring up different failures related to Node Edge and APM Server. With this change, the test code is not waiting for a memcached service.
Closes #1537

ci(jenkins): add memcached to edge tests

---

lib/config.js
test/central-config-enabled.js

Extend central config support to accept `transaction_max_spans` and `capture_body`.
Relates to https://github.com/elastic/apm/issues/138

feat(config): extend central config support

---

.ci/Jenkinsfile

Optimize and abort all the old builds which are still running in the CI then we can reduce the number of active resources, aka Jenkins workers, and being able to have a healthy build queue.
Only for PRs. As for any branches/tags we want to keep track when a particular build failed. The pipeline for the branches/tags might be slightly different in some cases, sometimes it's required to run more exhaustive tests, benchmarks or other goals.
- It depends on the new release of the library. Waiting for [build](https://apm-ci.elastic.co/job/apm-shared/job/apm-pipeline-library-mbp/job/master/355/)
- It might not be 100% effective if there are try/catch/catchWarn/catchErr steps within downstream jobs. But that's the closest we can enable this behavior at the moment without tweaking the pipelines.

ci(jenkins): cancel previous running builds

---

.ci/Jenkinsfile

Add a final stage in the release process to bump the opbeans agent dependency.
When a new tag, aka a new release, is created then, the automation will kick the opbeans build which consists of the following tasks:
This particular pipeline will push the changes into the `master` branch for the opbeans-node and tag it with the name of the tag version too. Therefore, the opbeans-node pipeline will trigger two builds, the one for its master branch and the other one for the just created tag. This particular flow is implemented within the opbeans-node.

ci(jenkins): trigger opbeans release process

---

.ci/Jenkinsfile
.ci/downstreamTests.groovy
.ci/linting.groovy

The linting in the branches are not working properly.
docker label is not required anymore for linux agents.

ci(jenkins): fix linting in branches and tidyup

---

test/integration/api-schema/download-json-schemas.sh

The file `message.json` has been added to the `docs/spec` folder in the APM Server repo and also needs to be downloaded here for the tests for work properly.

test: add missing API schema file

---

.ci/jobs/apm-agent-nodejs-downstream.yml
.ci/jobs/apm-agent-nodejs-linting-mbp.yml
.ci/jobs/apm-agent-nodejs-mbp.yml

Adds reference repos.
These correspond to repos and download locations which can be seen in [the Jenkins job which mirrors them](https://apm-ci.elastic.co/job/jenkins-git-fetch-reference/).

Add reference-repo for CI

---

test/integration/api-schema/download-json-schemas.sh

- test: add missing API schema file (#1584)

[2.x] test: add missing API schema file (#1584)

---

.ci/scripts/test_types_babel_esm.sh
test/script/run_tests.sh

Babel has an issue under Node.js 13.0 and 13.1. This commit just skips the babel tests in those circumstances.

test: fix babel tests

---

lib/config.js
lib/instrumentation/http-shared.js
lib/lambda.js
test/instrumentation/_agent.js
test/instrumentation/modules/http/aws.js
test/instrumentation/modules/http/basic.js
test/instrumentation/modules/http/outgoing.js
test/lambda/promises.js

This PR adds support for W3C TraceContext `traceparent` header while still keeping the `elastic-apm-traceparent` header. The use of the elastic header is controlled by `ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER` config option. For more see: #994

feat: support W3C TraceContext traceparent header

---

.ci/packer_cache.sh
.ci/scripts/test.sh

Cache the docker images used in the test stage. For such, it does build the docker image with docker-compose and trap the error to be reported afterward, then it does run the docker-compose.
Speed up the CI overall execution time.
```bash
$ hub checkout pr 701
$ sh .ci/packer_cache.sh 
```
Output should look like the below snippet:
```
13: Pulling from observability-ci/apm-agent-nodejs
Digest: sha256:cd3d5d77b2e0d689f3a16363188e98e5a9f9365ef4fa521ae9af559ebe845320
Status: Image is up to date for docker.elastic.co/observability-ci/apm-agent-nodejs:13
docker.elastic.co/observability-ci/apm-agent-nodejs:13
13.0: Pulling from observability-ci/apm-agent-nodejs
Digest: sha256:12061362c5c2c7db1a842bb535d4f38b867df5f0f3b169817aa9a3b26003061b
Status: Image is up to date for …
```

ci(jenkins): cache docker images in the CI workers

---

.ci/docker/docker-compose.yml
.tav.yml
lib/instrumentation/modules/cassandra-driver/_async_connect_patch.js
lib/instrumentation/modules/cassandra-driver/index.js
lib/instrumentation/patch-async.js
package.json
test/docker-compose.yml
test/instrumentation/modules/pg/pg.js
test/integration/api-schema/download-json-schemas.sh

- test: fix APM Server schema tests (#1636)
- fix(cassandra): improve support for cassandra-driver v4.4.0+ (#1636)
- ci(jenkins): ensure postgres container doesn't need password (#1636)
- fix: support promisifying setTimeout and friends (#1636)
- ci(tav): fix got TAV tests (#1636)
- ci(tav): fix @hapi/hapi TAV tests (#1636)
- test(pg): fix pg TAV tests (#1636)

[2.x] Fix CI (#1636)

---

package.json

- fix(package): bump require-in-the-middle to ^5.0.2 (#1544)

[2.x] fix(package): bump require-in-the-middle to ^5.0.2 (#1544)

---

docs/supported-technologies.asciidoc

- docs: add @hapi/hapi v19.x to support matrix (#1643)

[2.x] docs: add @hapi/hapi v19.x to support matrix (#1643)

---

LICENSE

- chore: bump copyright year (#1648)

[2.x] chore: bump copyright year (#1648)

---

.ci/Jenkinsfile

Let's fix the linting issues when running in the master branch. This is caused by the git reference repo that's not exposed in the docker container.
```
[2020-02-26T11:55:05.964Z] + npm run lint:commit
[2020-02-26T11:55:05.965Z] 
[2020-02-26T11:55:05.965Z] > elastic-apm-node@3.4.0 lint:commit /app
[2020-02-26T11:55:05.965Z] > test/lint-commits.sh
[2020-02-26T11:55:05.965Z] 
[2020-02-26T11:55:05.965Z] + [[ -n https://apm-ci.elastic.co/ ]]
[2020-02-26T11:55:05.965Z] ++ npm bin
[2020-02-26T11:55:05.965Z] + export PATH=/app/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2020-02-26T11:55:05.965Z] + PATH=/app/node_modules/.bin:/usr/local/lib/node_modules/npm/node_module …
```

ci(jenkins): mount ref repo in the docker container

---

CHANGELOG.asciidoc

Sometimes when backporting, changes need to made to the code being backported. If we just referenced the original PR, the user clicking the link would not see those differences. Alternatively, we could link to both PRs, but I think that would be too much noise. And since the backported PR references the original PR in the PR description, just referencing the backported PR should suffice.

docs: fix CHANGELOG to refence backported PRs

---

CONTRIBUTING.md

The tag is not allowed to be a valid semver range

docs: fix npm dist-tag used when publishing old versions

---

docs/distributed-tracing.asciidoc
docs/index.asciidoc
docs/transaction-api.asciidoc

**http://apm-agent-nodejs_1650.docs-preview.app.elstc.co/guide/en/apm/agent/nodejs/master/distributed-tracing.html**
This PR adds a distributed tracing guide to the Node.js documentation. The guide explains the following:
1. What distributed tracing is (briefly).
2. How to correlate distributed tracing with the RUM Agent.
3. How to use distributed tracing with a protocol other than HTTP(S).
Closes https://github.com/elastic/apm-agent-nodejs/issues/1155.
Related to https://github.com/elastic/apm-agent-rum-js/pull/632.

[docs] Add distributed tracing guide

---

lib/parsers.js
package.json
test/parsers.js

+ fix #1590 
+ Currently our error stack construction depends on v8 API stack generation function hook which would be called whenever error stack is created, but when the error stack property is changed somewhere in the code/modules, we wont be able to access the callsite information. 
+ This PR provides a sensible fallback when we cannot access the callsite information for errors and also for errors that have additional `originalError` property which reveals the true error (graphqljs adds this property and creates GraphqlError which has this originalError property). 
An example error in Apollo server would look like this in our UI.

feat: parse error stacks manually

---

package.json

This ensures that we use the latest `error-callsites` module which is a dependency of `stackman`. The old version could end up in an infinite loop if used together with the `stackback` module as both would overwrite the `Error.prepareStackTrace` function and both would call each other when `Error.prepareStackTrace` was called.

fix(package): bump stackman to ^4.0.1

---

.ci/Jenkinsfile

- Any builds for any branch or PR that only contains changes related to the asciidoc then it will skip all the stages but the `checkout`
Docs validation happens with the `elasticsearch-ci/docs` therefore there is no need to validate anything in our end.

ci(jenkins): disable stages for only docs

---

.ci/Jenkinsfile

Use the chocolatey nodejs-lts to see if the 12.16.1 version is solved there.
```
[2020-03-31T12:47:34.649Z] Getting latest nodejs-lts version for 12 ...
[2020-03-31T12:47:37.975Z] 
[2020-03-31T12:47:37.975Z] nodejs-lts 12.16.1 [Approved]
[2020-03-31T12:47:37.975Z] nodejs-lts 12.16.0 [Approved]
[2020-03-31T12:47:37.975Z] nodejs-lts 12.15.0 [Approved]
[2020-03-31T12:47:37.975Z] nodejs-lts 12.14.1 [Approved]
[2020-03-31T12:47:37.975Z] nodejs-lts 12.14.0 [Approved]
[2020-03-31T12:47:37.975Z] nodejs-lts 12.13.1 [Approved]
[2020-03-31T12:47:37.975Z] nodejs-lts 12.13.0 [Approved]
[2020-03-31T12:47:42.187Z] Installing nodejs-lts version: 12.16.1 ...
[2020-03-31T12:47:42.187Z] Chocolatey v0.10.11
[2020-03-31T12:47:42.449Z] Installing the following packages:
[2020-03-31T12:47:42.449Z] nodejs-lts …
```

ci(jenkins): use nodejs lts in the windows stage

---

.ci/Jenkinsfile

Backports the following commits to 3.x:
- ci(jenkins): use nodejs lts in the windows stage (#1702) (7b933627)

[3.x] ci(jenkins): use nodejs lts in the windows stage (#1702) (7b933627)

---

.ci/Jenkinsfile

- ci(jenkins): use nodejs lts in the windows stage (#1702) (7b933627)

[2.x] ci(jenkins): use nodejs lts in the windows stage (#1702) (7b933627)

---

docs/metrics.asciidoc
lib/metrics/runtime.js
test/metrics/index.js

This ticket adds some metrics missing of #309.
I've added the metrics `nodejs.memory.external.bytes` and `nodejs.memory.arrayBuffers.bytes` (available from node 13.x).
All memory related data is now collected using `process.memoryUsage()` which has a better documentation than the internal v8 methods: https://nodejs.org/docs/latest/api/process.html#process_process_memoryusage

Add metrics for external memory

---

test/integration/api-schema/download-json-schemas.sh

This file was added to the APM Server repo in:
https://github.com/elastic/apm-server/pull/3729

test: add missing APM Server API Schema file cloud.json

---

test/integration/allow-invalid-cert.js
test/integration/api-schema/download-json-schemas.sh

- test: fix APM Server cert test to work with 13.9.0+ (c3c119b1)
- test: add missing APM Server API Scheme file cloud.json (#1738)

[2.x] test: fix APM Server cert test to work with 13.9.0+ (c3c119b1) | test: add missing APM Server API Scheme file cloud.json (#1738)

---

docs/performance-tuning.asciidoc

PR for elastic/apm-agent-nodejs#1701 - adding a hint to the performance tips showing how to ignore spans having a short duration.
Needs to be checked by a native English speaker ...

docs: hint how to ignore spans if very short

---

.ci/Jenkinsfile

It retries to get the worker IP if the return string is empty or null
closes https://github.com/elastic/apm-agent-nodejs/issues/1744

ci: retry to grab the worker IP

---

package.json

- chore(package): bump standard to version ^14.3.3 (#1677)

[2.x] chore(package): bump standard to version ^14.3.3 (#1677)

---

package.json

- fix(package): bump stackman to ^4.0.1 (#1679)

[2.x] fix(package): bump stackman to ^4.0.1 (#1679)

---

.ci/Jenkinsfile

Enable some debug logs to gather the IP for the Linux CI Worker that's used internally to spin up all the services that are required to run the tests in Windows.
[here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1757/1/pipeline/148#step-404-log-2) and [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1757/1/pipeline/148#step-173-log-1)
Closes https://github.com/elastic/apm-agent-nodejs/issues/1744

ci(jenkins): debug windows worker reqs

---

.tav.yml
docs/supported-technologies.asciidoc
lib/instrumentation/modules/knex.js
package.json

Only breaking change that affects us is the drop of support for Node.js v8, due to that I've created a new tav item for versions that require Node.js > 8
Fixes #1786

feat(knex): add support for 0.21.x

---

lib/instrumentation/modules/elasticsearch.js
test/instrumentation/modules/elasticsearch.js

fix(elasticsearch): ensure requests can be aborted

---

test/integration/api-schema/download-json-schemas.sh

The new schema ref was introduced in elastic/apm-server#4056.
Fixes #1809

fix(tests): api-schema has a new schema ref

---

CONTRIBUTING.md
test/integration/api-schema/download-json-schemas.sh

This PR makes a small addition to `CONTRIBUTING.md` to encourage folks to continue tests with any new code.  It also fixes the CI so we can land this PR.
Prior to this PR the CI was broken due to `download-json-schemas.sh` failing. The `download-json-schemas.sh` was failing [because the APM Server's schema had changed](https://github.com/elastic/apm-server/tree/master/docs/spec) and `download-json-schemas.sh` was missing files.  
Since [this isn't the first time this has happened](https://github.com/elastic/apm-agent-nodejs/pull/1810), this PR changes our approach to downloading these schema files, [cribbing from our friends in python](https://github.com/elastic/apm-agent-python/blob/master/tests/scripts/download_json_schema.sh)

ci: fix schema downloader and make less fragile, suggest PRs have tests

---

test/instrumentation/modules/ioredis.js

ioredis@4.19.0 includes a bug when using `redis.quit()` that can leave
a setInterval uncleared. See luin/ioredis#1215.
Fixes elastic/apm-agent-nodejs#1838

fix(tests): fix hang in ioredis test

---

lib/instrumentation/generic-span.js
lib/instrumentation/http-shared.js
lib/tracecontext/index.js
lib/tracecontext/tracestate.js
test/tracecontext/tracestate.js

This PR closes #1797.
This pull request implements the tracestate functionality for the elastic node agent.  The new `TraceState` class is capable of getting/setting values under a single list-member of the tracestate string while preserving the values of the other list-members.  It can also produce output in either the W3C string format or the W3C binary format (via a hex string). 
The pull request also uses this new tracestate functionality to add an `es` list-member to the root trace node with an `s` key that records the transaction sample rate.  This header is initially set on the root trace node.  If the transaction is the child of another transaction the priority is not explicitly set, and instead the tracestate header is simply propagated on. 
This pull request also replaces the …

feat: tracestate

---

test/instrumentation/modules/pg/knex.js

fix(tests): skip testing knex >=0.21 with node v8

---

.ci/Jenkinsfile

Fixes elastic/apm-agent-nodejs#1847

ci: skip TAP/JUnit and codecov processing for TAV tests

---

lib/instrumentation/modules/redis.js

- instrumentation of redis 2.x was accidentally in v3.7.0
- before the addition of destination metadata in commit aa8eb56 (v3.6.0)
didn't work for redis 2.3.0 .. 2.5.3
Fixes #1850

fix: redis@2.x instrumentation was broken

---

.tav.yml
docs/supported-technologies.asciidoc
lib/instrumentation/modules/tedious.js
package.json
test/instrumentation/modules/tedious.js

This PR will do a couple things:
- Clarify which tedious versions are supported (current state is a little inconsistent between .tav.yml, the guard in the actual instrumentation code, and the "supported modules" doc).
- Fix tedious@9.x breakage (at least breakage of the tests).
The intent is to fix elastic/apm-agent-nodejs#1849

fix(tedious): fix tedious@9.x breakage and clarify supported version range

---

test/instrumentation/modules/ws.js

Short: The PR modifies this test's use of the the `mockClient` ___ parameter, and instead relies on the default mock client test ending behavior.  This fixes the TAV tests for the `ws@1.x` module, at the cost of no longer testing that there were exactly two writes to the HTTP client.
Long:  The `ws@1.x` failures were introduced [in this PR](https://github.com/elastic/apm-agent-nodejs/commit/0d0eeaa7a46ba721e509ac3c4c4d9b05e4b09893#diff-7cb2e6576b8a433a53a30518c4f99782e993baecc8bcdcdb1086f22f7c248798), when we moved to tape 5.  
Tape 5 fixed [a long standing bug](https://github.com/substack/tape/commit/e925bb15b5f21eac357a3f86170da1241cca3439) where tape didn't enforce `t.end()`.  This `tape` fix revealed that the `ws.js` tests have haven been incorrectly written, in that test assertions …

ci: fix ws@1.x TAV tests

---

.tav.yml

Also, clarify the hapi @hapi/hapi test matrix.
Fixes elastic/apm-agent-nodejs#1857

tests(hapi): do not test hapi@<=v15 on node >=v14

---

.gitignore
Makefile

Also anchor many gitignore'd files to the top project dir with '/'.

chore: convenience Makefile, ignore local tmp dir for scratch files

---

test/integration/api-schema/download-json-schemas.sh

Fixes: #1859
MacOS `tar` has `--wildcards` behavior by default.  This PR sniffs for Darwin (I don't know of a an easy/clean feature sniff for a tar flag) and then invokes the same tar command, just without the `--wildcards`.
Tested locally, but since none of our CI a second set of eyes/fingers would be appreciated here.

fix: remove gtar dep

---

test/instrumentation/modules/pg/pg.js

Fixes: https://github.com/elastic/apm-agent-nodejs/issues/1866
It looks like there was an incorrect assumption in the the test that was submitted along with https://github.com/elastic/apm-agent-nodejs/pull/1846  
This PR adds guard clauses that match the behavior of the guard clauses in the `pg` instrumentation 
https://github.com/elastic/apm-agent-nodejs/blob/8a5e908b8e9ee83bb1b828a3bef980388ea6e08e/lib/instrumentation/modules/pg.js#L93
to ensure this test only runs when/where it needs to. 
The tests were failing in older versions of `pg` without promise support.  Putting the tests behind the `pg@5.1` guard clause resulted in errors in the 6.x branch because the agent is adding `then` and `catch` callbacks to the promise in versions of `pg` without an `on` method (i.e. the 6.x line of …

fix: tests correct codepath for pg span ending
