- lib/parsers.js
- test/parsers.js
This API schema change was introduced in elastic/apm-server#49
> Support new context.response status code format

- docs/index.asciidoc
Add a link to the Github repository.
> Add experimental note to doc build

- lib/config.js
- lib/instrumentation/transaction.js
- lib/request.js
> Unify intake API field max length

- package.json
@watson in case you are fine with the new structure, I think this PR should fix the broken `test-cli`, I introduced in PR #19.
> Adapt test-cli to new structure.

- README.md
- docs/index.asciidoc
> Alpha launch

- lib/parsers.js
> Ensure order of properties in context.request.url

- README.md
> Document DEBUG_PAYLOAD flag

- test/.jenkins_tav.yml
- test/script/docker/run_tests.sh
Jenkins cannot handle commas in Urls, so the input for the tavs needs to
be changed.
> test(jenkins): change structure of tavs for jenkins.

- docker-compose.yml
- test/script/docker/cleanup.sh
Update docker file to use ES 6.0.0-rc2.
Minor bugfix in removing docker containers.
> test(docker): Update Elasticsearch docker file.

- docs/agent-api.asciidoc
- lib/agent.js
- lib/config.js
- lib/instrumentation/index.js
- lib/instrumentation/queue.js
- test/instrumentation/queue.js
Use the maxQueueSize option to force a flush of the queue when it reaches a certain size.
> Add maxQueueSize config option

- docs/compatibility.asciidoc
This is how the change will be rendered:
> Note that we don't support Node.js v7.10.x

- .travis.yml
This should enable reporting coverage data to codecov
Fixes #89
> Send coverage reports to codecov

- .tav.yml
- .travis.yml
- lib/instrumentation/index.js
- lib/instrumentation/modules/handlebars.js
- package.json
- test/.jenkins_tav.yml
- test/instrumentation/modules/handlebars.js
I went for the simple approach and just instrumented the outer compile function and the render function it returns.
@watson Do you think it's worthwhile going deeper than this?
Fixes #85.
> Instrument handlebars

- .tav.yml
- lib/instrumentation/modules/graphql.js
- test/instrumentation/modules/graphql.js
> fix(graphql): support sync execute

- .npmignore
- codecov.yml
> test(ci): add codecov.yml for status indicators

- lib/instrumentation/modules/bluebird.js
- lib/instrumentation/modules/express-graphql.js
- lib/instrumentation/modules/express.js
- lib/instrumentation/modules/generic-pool.js
- lib/instrumentation/modules/graphql.js
- lib/instrumentation/modules/hapi.js
- lib/instrumentation/modules/ioredis.js
- lib/instrumentation/modules/koa-router.js
- lib/instrumentation/modules/mongodb-core.js
- lib/instrumentation/modules/mysql.js
- lib/instrumentation/modules/pg.js
- lib/instrumentation/modules/redis.js
- lib/instrumentation/modules/ws.js
I tried to follow the trend on the commit message guidelines, but let me know if I should tweak it. I also signed the CLA.
> chore(*): fix typos in supported-module-version debug messages

- docs/agent-api.asciidoc
- docs/api.asciidoc
- docs/compatibility.asciidoc
- docs/custom-stack.asciidoc
- docs/custom-traces.asciidoc
- docs/custom-transactions.asciidoc
- docs/express.asciidoc
- docs/hapi.asciidoc
- docs/intro.asciidoc
- docs/koa.asciidoc
- docs/setup.asciidoc
- docs/source-maps.asciidoc
- docs/trace-api.asciidoc
- docs/transaction-api.asciidoc
- docs/troubleshooting.asciidoc
Adds direct link to relevant page at [elastic.co](https://www.elastic.co/guide/en/apm/agent/nodejs/current/intro.html) docs. Resolves #152
> Added links to relevant page in docs from each .asciidoc file

- .tav.yml
- docs/compatibility.asciidoc
- lib/instrumentation/modules/ws.js
Version 4.0.0 of the ws module was released 3 days ago
> feat(ws): add support for ws@4.x

- docs/agent-api.asciidoc
- lib/config.js
- lib/instrumentation/transaction.js
- test/instrumentation/transaction.js
> feat(transaction): add transactionMaxSpans config

- lib/parsers.js
- package.json
- test/instrumentation/protocol.js
- test/parsers.js
> feat(*): add full to url

- docs/agent-api.asciidoc
> docs: add missing docs for special parameterized error object

- docs/agent-api.asciidoc
- lib/config.js
- lib/instrumentation/index.js
- lib/instrumentation/protocol.js
- lib/instrumentation/transaction.js
- lib/request.js
- test/agent.js
- test/instrumentation/_agent.js
- test/instrumentation/index.js
- test/instrumentation/protocol.js
This is a basic random sampling implementation.
Fixes #148
> feat(instrumentation): support sampling

- docs/agent-api.asciidoc
- lib/config.js
- lib/instrumentation/queue.js
- test/instrumentation/modules/http/aborted-requests-disabled.js
> chore(config): update flushInterval to 10 seconds

- .travis.yml
This will make the tests run faster and give feedback to the user more quickly.
> test(ci): merge test and coverage build stages

- lib/agent.js
> chore(errors): always include handled flag

- lib/instrumentation/modules/elasticsearch.js
- test/instrumentation/modules/elasticsearch.js
>  chore(elasticsearch): Only include db context for _search queries

- .tav.yml
- docs/compatibility.asciidoc
- lib/instrumentation/modules/mongodb-core.js
Went through all the functions that we patch and there doesn't seem to be any breaking changes in those between v2 and v3, so we should be good to go
> feat(mongodb): add support for mongodb-core 3.x

- docker-compose.yml
- test/script/docker/run_tests.sh
cc @beniwohli 
Change to use a named volume as we experienced repeated docker issues with stopping containers.
> test(docker): use named volumes

- package.json
This update speeds up parsing of source code for context lines dramatically.
Fixes #203
> chore(*): bump stackman dependency to ^3.0.1

- README.md
- docs/index.asciidoc
- docs/page_header.html
When merging, remember to also update the GitHub repo description
> chore(*): remove beta label

- lib/agent.js
- lib/instrumentation/express-utils.js
- lib/instrumentation/modules/express.js
- lib/instrumentation/modules/hapi.js
- lib/instrumentation/modules/ioredis.js
- lib/instrumentation/modules/knex.js
- lib/instrumentation/modules/mysql.js
- lib/instrumentation/modules/pg.js
- lib/instrumentation/patch-async.js
- lib/instrumentation/shimmer.js
- lib/instrumentation/transaction.js
- lib/symbols.js
- test/_agent.js
> refactor: use symbols to store values on 3rd party objects

- lib/instrumentation/modules/express.js
- test/instrumentation/modules/express.js
> fix(express): prevent invalid errors from reporting

- docker-compose.yml
- test/script/docker/run_tests.sh
This should reduce the amount of images created on Jenkins CI
> test(docker): tag built docker images

- .github/issue_template.md
- .github/pull_request_template.md
- .npmignore
Just a suggestion - let me know what you think 😃
> chore: add GitHub issue and PR templates

- docs/agent-api.asciidoc
Missed this when creating PR #227
> docs: improve ignoreUserAgents example

- .github/pull_request_template.md
I think "Checklist" is better than "To-do", which I also think the Node.js core project is using if I remember correctly
> chore: improve GitHub PR template

- docs/agent-api.asciidoc
- lib/agent.js
- lib/config.js
- lib/request.js
- package.json
- test/config.js
- test/request.js
Fixes #210 
This depends on https://github.com/elastic/apm-nodejs-http-client/pull/1 landing and getting released.
> feat(config): add serverTimeout

- README.md
As this project is now GA, there's no reason to use the language "If you are trying out...".
> docs(readme): improve README.md copy

- package.json
This was supposed to have been included in PR #267
> test(ws): bump devDependency ws to ^5.0.0

- lib/request.js
- test/request.js
> feat(request): include ppid

- docs/agent-api.asciidoc
> docs: fix addFilter example in API docs

- docs/agent-api.asciidoc
- lib/agent.js
- lib/instrumentation/transaction.js
- test/instrumentation/transaction.js
Fixes elastic/apm-agent-nodejs#105
> feat(transaction): add addTags method

- docs/agent-api.asciidoc
- docs/transaction-api.asciidoc
- lib/instrumentation/transaction.js
- test/instrumentation/transaction.js
> feat(transaction): call end with result

- CONTRIBUTING.md
I've added some basic release process instructions.
> doc: release process instructions

- package.json
> chore: allow Node.js 10 in package.json engines field

- docs/custom-stack.asciidoc
> docs: add link to lambda docs from custom stack docs

- test/instrumentation/index.js
I created this test while debugging a related issue. It turned out not to be related to sampling, but I thought it would be a good test to have nonetheless, so here it is
> test: test that unsampled http transactions have the expected result

- package.json
> test: un-pin devDependency

- .travis.yml
- README.md
Should we add others than `nightly` and `rc`?
See a full list of possibilities here: https://nodejs.org/download/
> test(ci): test unreleased versions of Node.js

- lib/instrumentation/modules/http2.js
- test/instrumentation/modules/http2.js
Fixes elastic/apm-agent-nodejs#124 
Depends on
- ~~elastic/apm-agent-nodejs#205~~
- ~~elastic/apm-agent-nodejs#371~~
> feat(http2): instrument client requests

- test/instrumentation/modules/bluebird/_coroutine.js
> test(bluebird): more reliable coroutine test

- docs/agent-api.asciidoc
> docs: improve disableInstrumentations docs

- test/instrumentation/modules/bluebird/_coroutine.js
> test: fix randomly failing Bluebird tests

- .tav.yml
- .travis.yml
- docs/compatibility.asciidoc
- lib/instrumentation/index.js
- lib/instrumentation/modules/express-queue.js
- package.json
- test/.jenkins_tav.yml
- test/config.js
- test/instrumentation/modules/express-queue.js
This fixes the continuity issue with express-queue.
Fixes #373
> feat(express-queue): retain continuity through express-queue

- docs/agent-api.asciidoc
> docs: improve captureBody documentation

- test/instrumentation/modules/mysql/mysql.js
Once in blue moon this test fails - yolo
> test: reduce likelihood of flaky mysql test failing

- docs/agent-api.asciidoc
- lib/agent.js
- test/agent.js
> feat(agent): add currentTransaction getter

- .appveyor.yml
- .tav.yml
- docker-compose.yml
- docs/compatibility.asciidoc
- lib/instrumentation/index.js
- lib/instrumentation/modules/tedious.js
- package.json
- test/instrumentation/modules/tedious.js
This is the beginnings of mssql instrumentation, via the lower-level `tedious` driver. Still needs some more testing though.
Fixes elastic/apm-agent-nodejs#304
> feat(mssql): instrumentation

- docs/troubleshooting.asciidoc
> doc(troubleshooting): update debug mode instructions

- lib/instrumentation/modules/tedious.js
- test/.jenkins_tav.yml
> fix(mssql): prepare identification

- test/script/appveyor/install-cassandra.ps1
- test/script/appveyor/install-elasticsearch.ps1
- test/script/appveyor/install-redis.ps1
> test(appveyor): abort tests if install scripts fail

- CHANGELOG.md
I tried to see if I could write the links in some form of shorthand, but that only works in descriptions/comments - not in markdown files apparently. If anybody knows of a better way, let me know 😄
> docs: add PR links to CHANGELOG.md

- test/instrumentation/modules/hapi.js
Fixes elastic/apm-agent-nodejs#455
> test(hapi): reenable for 10.8+

- lib/agent.js
- lib/config.js
> fix: ensure logger config can update

- README.md
- lib/agent.js
- lib/config.js
Changes for intake API v2
Depends on https://github.com/elastic/apm-nodejs-http-client/pull/9
> chore: add payloadLogFile debug config option

- test/integration/api-schema/download-json-schemas.sh
Fixes #519
Depends on elastic/apm-server#1304
> fix(tests): api-schema has a new tags file

- .tav.yml
- .travis.yml
- docs/agent-api.asciidoc
- docs/compatibility.asciidoc
- docs/index.asciidoc
- docs/intro.asciidoc
- docs/restify.asciidoc
- lib/instrumentation/index.js
- lib/instrumentation/modules/restify.js
- package.json
- test/.jenkins_tav.yml
- test/instrumentation/modules/restify.js
Fixes elastic/apm-agent-nodejs#440
Depends on elastic/apm-agent-nodejs#521
> feat(restify): instrumentation

- CHANGELOG.md
This was removed by a mistake previously
> docs: add # in front of PR numbers in CHANGELOG.md

- package.json
See https://github.com/jeffbski/wait-on/issues/28
> chore: pin wait-on@2.1.0

- lib/config.js
- lib/queue.js
- test/config.js
I'll add another config option to list in an upcoming PR
> refactor: convert maxQueueSize -1 to Infinity at boot

- docs/agent-api.asciidoc
- lib/config.js
- test/config.js
~~Depends on #566~~
Fixes #555
> fix: default transactionMaxSpans to 500

- test/integration/api-schema/basic.js
The APM Server updated the schemas, so the tests started failing
> test: fix json schema tests

- test/integration/api-schema/basic.js
> fix: v2 schema tests

- lib/instrumentation/modules/ws.js
> fix(ws): allow disabling

- test/integration/api-schema/download-json-schemas.sh
> Fix schema tests

- docs/agent-api.asciidoc
- lib/config.js
- test/config.js
- test/instrumentation/async-hooks.js
> feat(config): change config order

- docs/agent-api.asciidoc
- lib/config.js
- test/config.js
> feat(config): support byte suffixes

- .travis.yml
- lib/config.js
- package.json
- test/config.js
Fixes elastic/apm-agent-nodejs#606
> feat(config): stricter boolean parsing

- docs/custom-transactions.asciidoc
> docs: improve custom transactions example

- docs/agent-api.asciidoc
- docs/configuration.asciidoc
- docs/performance-tuning.asciidoc
- docs/upgrade-to-v2.asciidoc
Spelling/grammar cleanup on `api-v2` branch before merge.
> docs: api-v2 cleanup

- docs/transaction-api.asciidoc
- lib/instrumentation/trace-context.js
- lib/instrumentation/transaction.js
- test/instrumentation/trace-context.js
> feat(transaction): add ensureParentId

- README.md
- docs/supported-technologies.asciidoc
Depends on ~~elastic/docs#457~~
> docs: bump minimum supported version of APM Server

- docs/transaction-api.asciidoc
> docs: update transaction.ensureParentId() code example

- docs/intro.asciidoc
Update agent `intro.asciidoc` per elastic/apm-dev#387
> Docs: Update agent introductions

- .travis.yml
- test/.jenkins_tav.yml
> test(finalhandler): add finalhandler to tav test-matrix

- lib/instrumentation/trace-context.js
- package.json
> fix: use randomFillSync polyfill on Node.js <6.13.0

- lib/agent.js
> Closes #732

- lib/instrumentation/modules/koa-router.js
- test/instrumentation/modules/koa-router/_async-await.js
- test/instrumentation/modules/koa-router/_generators.js
- test/instrumentation/modules/koa-router/index.js
This adds support for correctly naming transactions when using middlewares and/or nested routes.
Fixes #742
> fix(koa-router): support more complex routes

- docs/agent-api.asciidoc
- docs/express.asciidoc
- docs/hapi.asciidoc
- docs/koa.asciidoc
- docs/lambda.asciidoc
- docs/restify.asciidoc
Fixes elastic/apm-agent-nodejs#640
> docs: update code samples

- lib/agent.js
- test/agent.js
> feat: include sampled flag on errors

- lib/agent.js
This should help a bit with avoiding startup log spam mentioned in #31.
> feat(config): validate serverUrl port

- lib/filters/http-headers.js
> fix: filter outgoing http headers with any case

- lib/agent.js
- test/agent.js
> feat: add transaction.type to errors

- docs/configuration.asciidoc
- lib/config.js
- package.json
- test/config.js
Fixes elastic/apm-agent-nodejs#693 
Fixes elastic/apm-agent-nodejs#737
Depends on elastic/apm-nodejs-http-client#42
> feat(config): add container info options

- NOTICE.md
The NOTICE file lists external dependencies which have been vendored into the project due to the need for minor changes.
Fixes #768
> docs: added NOTICE file

- lib/instrumentation/generic-span.js
- lib/instrumentation/span.js
- lib/instrumentation/transaction.js
> refactor: change order of args to GenericSpan

- NOTICE.md
- docs: added NOTICE file  (#783)
> [1.x] docs: added NOTICE file (#783)

- docs/agent-api.asciidoc
- lib/agent.js
- test/agent.js
> feat: add ability to set custom timestamp for errors

- docs/agent-api.asciidoc
- lib/agent.js
- test/agent.js
> feat: add ability to set custom log message for errors

- lib/metrics/platforms/linux/stats.js
> fix(metrics): ensure NaN becomes 0, not null

- test/instrumentation/transaction.js
This is just to appease Jenkins...
> ci(transaction): increase acceptable duration range

- Jenkinsfile
- test/docker-compose.ci.yml
- test/docker-compose.yml
- test/instrumentation/transaction.js
- test/script/docker/cleanup.sh
- test/script/docker/run_tests.sh
- test/script/run_tests.sh
Jenkins file to build the APM Agent Node.js with the multibranch pipeline job https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/
> [APM-CI] Jenkins Pipeline for Agent Node.js

- lib/instrumentation/express-utils.js
- lib/instrumentation/modules/express.js
- lib/instrumentation/modules/graphql.js
- test/instrumentation/modules/express.js
Fixes elastic/apm-agent-nodejs#443
> fix(express): ensure correct transaction names

- docs/configuration.asciidoc
- lib/config.js
- test/config.js
> fix(config): apiRequestSize should be 768kb

- Jenkinsfile
* Bump shared lib version to 1.0.7
* Use flyweight Jenkins agents for light tasks
- [NA] Add tests
- [NA] Update documentation
> ci(jenkins): Bump shared lib version to 1.0.7

- test/script/docker/run_tests.sh
* set flag `--no-ansi` to remove control characters from the output
* set flag `--log-level ERROR` to show only errors in the output
- [NA] Add tests
- [NA] Update documentation
> ci(jenkins): put docker-compose in quiet mode

- lib/instrumentation/modules/elasticsearch.js
> fixing #860 unhandled promise rejection on elastic client reject

- package.json
Dunno why I forgot to do this in my last PR
> test(fastify): bump fastify dev dependency to ^2.0.1

- docs/supported-technologies.asciidoc
See https://github.com/elastic/docs/pull/724
Space doesn't work. Needs to be removed
> Docs: fix rendering of table

- lib/metrics/index.js
- test/config.js
> fix(metrics): use noop logger in metrics reporter

- lib/lambda.js
> fix(lambda): do not wrap context

- .npmignore
> chore(npm): don't include Jenkinsfile in npm build

- .tav.yml
- docs/agent-api.asciidoc
- docs/index.asciidoc
- index.d.ts
- lib/agent.js
- lib/instrumentation/modules/express.js
- lib/instrumentation/modules/fastify.js
- lib/instrumentation/modules/hapi.js
- lib/instrumentation/modules/koa.js
- lib/instrumentation/modules/restify.js
- package.json
- test/agent.js
- test/config.js
- test/instrumentation/_agent.js
- test/instrumentation/modules/express/basic.js
- test/instrumentation/modules/express/set-framework.js
- test/instrumentation/modules/fastify/set-framework.js
- test/instrumentation/modules/hapi/basic.js
- test/instrumentation/modules/hapi/set-framework.js
- test/instrumentation/modules/koa/set-framework.js
- test/instrumentation/modules/restify/basic.js
- test/instrumentation/modules/restify/set-framework.js
- test/test.js
- test/types/index.ts
Fixes #688
This is how the new docs will look:
> feat: add agent.setFramework() method

- lib/instrumentation/modules/express.js
- test/instrumentation/modules/express/basic.js
Fixes elastic/apm-agent-nodejs#935
> fix(express): transaction default name is incorrect

- docs/troubleshooting.asciidoc
- lib/agent.js
> feat(debug): initiate debugging on trace

- Jenkinsfile
* Update codecov step to the new versions
* remove a wrong redundant condition
- [N/A] Add tests
- [N/A] Update documentation
> ci(jenkins) update codecov step

- lib/instrumentation/generic-span.js
- lib/instrumentation/index.js
- lib/instrumentation/span.js
- lib/instrumentation/transaction.js
- test/instrumentation/span.js
- test/instrumentation/transaction.js
> feat: sync flag on generic span

- lib/agent.js
> Initialize config/logger before instrumentation

- .tav.yml
- package.json
> test(tav): don't test broken version of knex

- .tav.yml
For details see:
https://github.com/restify/node-restify/issues/1773
> test(tav): restify v8+ only works on Node.js 8.6+

- docs/configuration.asciidoc
- lib/config.js
- package.json
- test/_apm_server.js
- test/config.js
Depends on elastic/apm-nodejs-http-client#57
Fixes #963
> feat(config): support global labels

- docs/configuration.asciidoc
This pr just adds an example of how to configure the new globalLabels environment variable.
> added doc example for globalLabels env var

- docs/agent-api.asciidoc
Closes elastic/apm-agent-nodejs#1022
> docs: fix location of custom context

- package.json
- test/config.js
- test/instrumentation/modules/restify/basic.js
- test/instrumentation/modules/restify/set-framework.js
> chore(package): update restify to version 8.3.1

- docs/opentracing.asciidoc
~~[ ] Add tests~~ (Because I fixed a typo in the documentation)
Closes #1051
> docs(opentracing): fix typo in object definition

- lib/config.js
I'm trying to make a habit of adding these - especially now that we're close to removing Node.js 6 😅
> chore: add missing TODO

- lib/instrumentation/modules/express.js
- test/instrumentation/modules/express/basic.js
Fixes elastic/apm-agent-nodejs#1067
> fix(express-slash): expose express handle properties

- lib/instrumentation/generic-span.js
> fix(span): use correct logger location

- test/integration/skip-internal-http-spans.js
> test: verify internal http requests are ignored

- .travis.yml
See https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
> Force Trusty distribution instead of relying on default

- Jenkinsfile
- Create GH checks with the most important stages in the CI Pipeline.
- This particular change might help to debug when there are errors in the CI and identify them easily within then PR itself.
> ci: github checks for the pull requests

- .ci/downstreamTests.groovy
- .ci/jobs/apm-agent-nodejs-downstream.yml
- .ci/jobs/defaults.yml
* New downstream job
* Refactor JJBB jobs defaults, we move the SCM section and the script-path setting to each YAML job file
* report IT test stats
This PR create a new job, it does not affect existing ones and it is not triggered with GitHub changes
> ci(jenkins): downstream job

- .ci/scripts/lint-commits.sh
- .ci/scripts/test_basic.sh
- Jenkinsfile
* add lint commit messages stage
* use node:12 Docker image
Closes #1157
> ci(jenkins): add lint commit messages stage

- docs/configuration.asciidoc
- lib/config.js
- test/config.js
> feat(config): default serviceVersion to package version

- lib/config.js
> fix: standardize user-agent header

- Jenkinsfile
This is a regression caused when pushing https://github.com/elastic/apm-agent-nodejs/commit/c1847b3b75865ddf2ff04af1662e6de109c64aad accidentally to master. 😢
> fix: a regression caused with previous commit

- .tav.yml
- docs/agent-api.asciidoc
- index.d.ts
- lib/agent.js
- lib/instrumentation/index.js
- test/types/index.ts
Just a few things we missed in #1246 
I added it all in one PR, but named it after the main change. Hope that's ok.
> feat: allow agent.clearPatches to be called with array of names

- docs/configuration.asciidoc
- lib/config.js
- lib/metrics/registry.js
- lib/metrics/reporter.js
- package.json
- test/config.js
- test/metrics/index.js
> feat(metrics): add metricsLimit option

- .github/ISSUE_TEMPLATE/Bug_report.md
A lot of people leave these texts in the final issue, which makes them harder to read. This is an attempt to "fix" that.
> chore: improve GitHub issue template

- test/instrumentation/modules/http/_assert.js
- test/instrumentation/modules/http/aborted-requests-enabled.js
This test sometimes never completes when running on Jenkins. This commit adds en extra assertion that might help us identify why.
> test: improve test output

- test/instrumentation/modules/mongodb-core.js
This should fix the CI issues we've been having with the mongodb-core tav tests.
Fixes #1337
> test(mongodb-core): fix tav tests

- lib/instrumentation/modules/graphql.js
- test/instrumentation/modules/apollo-server-express.js
- test/instrumentation/modules/express-graphql.js
- test/instrumentation/modules/graphql.js
Closes elastic/apm-agent-nodejs#1230
> refactor(graphql): use custom transaction type for graphql requests

- docs/configuration.asciidoc
> docs: add missing breakdownMetrics option

- test/instrumentation/modules/http/aborted-requests-enabled.js
> ci(jenkins): end test properly even if it times out

- lib/instrumentation/http-shared.js
- lib/instrumentation/modules/http.js
Backport of #1417 for `2.x` branch
> chore(http): workaround(s) to suppress DEP0066 warnings

- .tav.yml
- docs/supported-technologies.asciidoc
- lib/instrumentation/index.js
- lib/instrumentation/modules/mongodb.js
- package.json
- test/_mock_http_client_states.js
- test/instrumentation/modules/mongodb.js
> feat(mongodb): instrumentation

- Jenkinsfile
- Fix leftover from https://github.com/elastic/apm-agent-nodejs/pull/1425
> ci(jenkins): fix wrong label

- .tav.yml
- docs/supported-technologies.asciidoc
- package.json
- test/instrumentation/modules/pg/knex.js
> chore(knex): bump knex dependency and fix tests

- .github/pull_request_template.md
This just makes it harder to forget :)
> chore: update GitHub PR template

- docs/release-notes.asciidoc
Backports https://github.com/elastic/apm-agent-nodejs/pull/1503.
> [2.x][docs] fix pull link (#1503)

- .ci/Jenkinsfile
> ci(jenkins): update argument (#1522)

- docs/agent-api.asciidoc
- index.d.ts
- lib/agent.js
- lib/metrics/index.js
- test/agent.js
- test/metrics/index.js
> feat: add custom metrics API (experimental)

- docs/scripts/build_docs.sh
Adds `--direct_html` flag to the doc build script. See https://github.com/elastic/docs/pull/1636 for more info.
> [docs] update doc build script

- docs/agent-api.asciidoc
change `agent.createSpan` to `agent.startSpan`
> [docs] update doc code snippet

- .ci/Jenkinsfile
> ci(jenkins): apm-its-downstream params has changed

- .tav.yml
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/redis.js
- package.json
+ Adds support for the new Redis 3.x versions
> feat(redis): add support for v3.x

- .ci/Jenkinsfile
> ci: avoid spurious TAV Test failure from not having TAP output

- lib/instrumentation/modules/pg.js
- test/instrumentation/modules/pg/pg.js
Fixes: elastic/apm-agent-nodejs#1829
> fix(pg): prevent unhandled promise rejection

- package.json
> feat: expand k8s pod ID discovery regex

- test/fixtures/json-specs/sql_signature_examples.json
- test/fixtures/json-specs/sql_token_examples.json
- test/fixtures/json-specs/wildcard_matcher_tests.json
APM agent specs automatic sync
*Manually forced with the CI automation job.*
> test: synchronizing json spec

- .github/labeler-config.yml
- .github/workflows/labeler.yml
This GitHub Workflow adds the "agent-nodejs" label to all new issues and pull requests
> Added GitHub Workflow for auto-labeling

- CHANGELOG.asciidoc
- lib/instrumentation/async-hooks.js
- test/instrumentation/async-hooks.js
> fix: obviously sync spans are not sent as sync

- docs/configuration.asciidoc
- lib/wildcard-matcher.js
Quick follow-on typo fixes from a prior PR.
> chore: grammar/typo fixes

- lib/filters/http-headers.js
- test/filters.js
Re-submission of https://github.com/elastic/apm-agent-nodejs/pull/1835
> Closes #1834 fix: Treat set-cookie in response headers as sensitive data

- .github/pull_request_template.md
Adds item to PR checklist reminding contributors to write a `CHANGELOG.asciidoc` entry.
> docs: add changelog to PR checklist

- lib/parsers.js
- test/parsers.js
Also refactor lib/parsers.js slightly. No functional change.
Fixes: #1918
> test: add tests for parsers._moduleNameFromFrames

- CHANGELOG.asciidoc
- docs/agent-api.asciidoc
- docs/span-api.asciidoc
- docs/transaction-api.asciidoc
- index.d.ts
- lib/agent.js
- lib/instrumentation/generic-span.js
- test/agent.js
Support boolean and numeric labels.
Fixes #1598
> Supports boolean and number labels. Fixes #1598

- .github/workflows/addToProject.yml
Added GitHub action to automatically add milestoned issues to the APM Agents project
> GitHub action to automatically add milestoned issues to the project

- docs/agent-api.asciidoc
- index.d.ts
Undoes unintentional push to master.
> fix: restores docs build

- docs/configuration.asciidoc
> docs: doc new 7.11 central config vars as Central/Dynamic

- test/central-config-enabled.js
Reduce noise in the "test/central-config-enabled.js" test output.
Test output length before:
```
% ./node_modules/.bin/tape test/central-config-enabled.js 2>&1 | wc -l
551
```
Test output length after:
```
% ./node_modules/.bin/tape test/central-config-enabled.js 2>&1 | wc -l
73
```
Full output before:
```
% ./node_modules/.bin/tape test/central-config-enabled.js
TAP version 13
ok 1 should be strictly equal
ok 2 should be deeply equivalent
Remote config success. Updated transactionSampleRate: 0.42
ok 3 should be deeply equivalent
Remote config success. Updated transactionMaxSpans: 99
ok 4 should be deeply equivalent
Remote config success. Updated captureBody: all
ok 5 should be deeply equivalent
Remote config success. Updated transactionIgnoreUrls: foo
ok 6 should be deeply equivalent …
```
> test: reduce noise in "test/central-config-enabled.js" test output

- test/integration/api-schema/apm-server-schema/error.json
- test/integration/api-schema/apm-server-schema/metadata.json
- test/integration/api-schema/apm-server-schema/metricset.json
- test/integration/api-schema/apm-server-schema/span.json
- test/integration/api-schema/apm-server-schema/transaction.json
APM agent json schema automatic sync
*Manually forced with the CI automation job.*
> synchronize schema spec

- test/central-config-enabled.js
This test was failing with the new v9.6.0 of elastic-apm-http-client.
The issue is that it was calling `agent.destroy()` in the mock
apm-server request handler. This destroys the agent *before* the
agent-side test code testing the config updating would run ... unless
`agent.destroy()` didn't actually destroy the socket between the
mock apm server and the agent.  Before v9.6.0 that was the case because
the socket being used was from Node's global http agent rather than one
from the `agent._transport._agent`.
This also changes the structure of the test to be a little more direct,
as is done in some of the tests lower down in this file.
```
% node --require /Users/trentm/el/apm-agent-nodejs5/test/_promise_rejection.js test/central-config-enabled.js
TAP version 13
ok 1 mock apm-server got …
```
> test: fix test end handling when http client is using keep-alive agent

- .ci/packer_cache.sh
> ci: skip packer cache on ARM

- lib/agent.js
> fix: crash on start if trace-logging and no process.argv[1]

- .ci/docker/node-edge-container/Dockerfile
> test: edge jenkins tests ("Nightly" and "RC") were broken

- .ci/Jenkinsfile
- .ci/scripts/prepare-benchmarks-env.sh
- .ci/scripts/run-benchmarks.sh
- test/benchmarks/scripts/run-benchmarks-ci.sh
- test/benchmarks/scripts/run-benchmarks.sh
This also bumps that ver from the intended 12 to 14.
Fixes: #2057
> fix: get the benchmarks run in CI to stick to a constant major ver of node

- DEVELOPMENT.md
> docs: dev note on running the Benchmark suite in Jenkins

- test/agent.js
Specifically that captured request and response headers, and request
body (if captureBody config var allows it) are sanitized.
Refs: https://github.com/elastic/apm-dev/issues/623
> test: ensure sanitizeFieldNames is applied to captured errors

- test/benchmarks/utils/bench.js
> chore: ensure no logging during benchmark runs which can break analysis

- .tav.yml
> tests: run S3 tests with each aws-sdk TAV version test

- .ci/scripts/test.sh
A relatively frequent error in Jenkins CI is this at the end of an
otherwise successful test run:
error while removing network: network docker_default id 873ad... has active endpoints
This is an attempted workaround to force removal and to print some
possibly helpful debug info.
> ci: workaround for common 'network docker_default id $id has active endpoints' jenkins error

- test/instrumentation/modules/@elastic/elasticsearch.test.js
> tests: update workaround for ES client bug to be for all 7.14.x versions

- test/metrics/breakdown.test.js
No functional change.
Namespacing these test cases under an "acceptance" group doesn't
add anything, and it gets in the way of using `test.only` when
debugging this test file.
> refactor: remove the unhelpful test suite namespacing

- test/metrics/breakdown.test.js
This improvements these tests to be less susceptible to a metricsInterval
and sendMetricSet race. In the context mgmt feature branch, CI would
fairly reliably fail on this race. The agent doesn't provide a mechanism
to "wait for breakdown metrics for all currently ended transactions and
spans".
> tests: make breakdown.test.js less racy

- test/_utils.js
- test/errors.test.js
This is an independent change I'm pulling out of #2181 work to get that PR smaller.
> refactor: move test util dottedLookup to utils file

- docs/lambda.asciidoc
> Fixing broken link to AWS Lambda Extension documentation

- CHANGELOG.asciidoc
- examples/trace-http2-request.js
- lib/instrumentation/index.js
- lib/instrumentation/modules/http2.js
- test/instrumentation/modules/http2.test.js
> fix: run-context for 'http2.request' instrumentation

- CHANGELOG.asciidoc
- examples/trace-pg.js
- lib/instrumentation/modules/pg.js
- test/instrumentation/modules/pg/pg.test.js
> fix: ensure correct run-context for pg instrumentation

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- examples/trace-express-graphql.js
- lib/instrumentation/modules/express-graphql.js
- lib/instrumentation/modules/graphql.js
- package.json
- test/instrumentation/modules/express-graphql.test.js
> feat: support express-graphql 0.10.0 - 0.12.0

- .ci/Jenkinsfile
- .ci/jobs/apm-agent-nodejs-mbp.yml
- .ci/jobs/apm-agent-nodejs-schedule-daily.yml
- .ci/jobs/apm-agent-nodejs-schedule-weekly.yml
- .ci/schedule-daily.groovy
- .github/pull_request_template.md
- .github/workflows/lint.yml
- .github/workflows/test.yml
- CHANGELOG.asciidoc
- CONTRIBUTING.md
- DEVELOPMENT.md
- dev-utils/jenkins-build-slow-steps.sh
- docs/configuration.asciidoc
- lib/config.js
- lib/instrumentation/modules/aws-sdk/s3.js
- lib/instrumentation/transaction.js
- lib/lambda.js
- lib/logging.js
- lib/tracecontext/index.js
- test/config.test.js
> Neutral naming for apm-agent-nodejs

- docs/configuration.asciidoc
> docs: correct 'serverTimeout' config var description

- docs/log-correlation.asciidoc
Apologies for all the documentation noise. This was missed in the previous update.
* 3.x: https://github.com/elastic/apm-agent-nodejs/pull/2545
> docs: update log-correlation.asciidoc

- docs/log-correlation.asciidoc
Same change as https://github.com/elastic/apm-agent-nodejs/pull/2544, but for the 3.x branch.
> docs: [3.x] update log-correlation.asciidoc

- lib/cloud-metadata/callback-coordination.js
- test/cloud-metadata/index.test.js
Fixes #2562
- ~[ ] Update TypeScript typings~
- ~[ ] Update documentation~
- ~[ ] Add CHANGELOG.asciidoc entry~
- ~[ ] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)~
> fix: deescalate no cloud metadata response warning

- CHANGELOG.asciidoc
- lib/lambda.js
- test/lambda/transaction.test.js
> feat: capture faas.name and faas.version for Lambda

- test/test.js
Replaces the static list of test directories with a call to a function that will build this list of directories by recursively searching through `./test` for folders that contain files named with the `*.test.js` pattern.  Excludes the `./test/start/env` and `./test/start/file` folders which are already legacy special cases that require additional setup in the `mapSeries` callback.
The intent of this PR is to allow repo-users (us) to add new tests to the project without needing to remember to add the new folder to the array in `./test/test.js`.
> fix: auto detect tests in ./test

- .ci/Jenkinsfile
Fixes #2625 
However there is some space for improvements
> chore:Publish to npm on release

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- lib/instrumentation/modules/tedious.js
- package-lock.json
- package.json
- test/config.test.js
- test/instrumentation/modules/tedious.test.js
Fixes: #2517
Add support for tedious v10 and above
I've manually tested each version with this change.
Looking forward for feedback ❤️.
> Feature: Add support for tedious v10 and above

- .ci/Jenkinsfile
- .ci/Makefile
- Dockerfile
- dev-utils/make-distribution.sh
- dev-utils/push-docker.sh
Adds a step in the CI to create a Docker image for the agent
> Build docker image

- .ci/Jenkinsfile
Removed role_id and secret_id in Jenkinsfile's Push Docker step
> Fix docker image Jenkins stage

- docs/lambda/configure-lambda-widget.asciidoc
- docs/lambda/configure-lambda.asciidoc
- docs/lambda/nodejs-arn-replacement.asciidoc
Depends on:
- https://github.com/elastic/apm-aws-lambda/pull/204
> Added container image tab to lambda setup docs

- .tav.yml
- package-lock.json
- package.json
Refs: https://github.com/fastify/fastify/issues/3998
> test: skip broken fastify@4.0.1 in TAV tests

- .ci/docker/docker-compose.yml
- .github/workflows/test.yml
- CHANGELOG.asciidoc
- lib/agent.js
- lib/errors.js
- lib/instrumentation/modules/@elastic/elasticsearch.js
- test/docker-compose.yml
- test/instrumentation/modules/@elastic/elasticsearch.test.js
> feat: add Elasticsearch client API error type to captured error.exception.type for better grouping

- .ci/Jenkinsfile
From now on we will use the same CI workers for the benchmarking
> ci: use the microbenchmarks-pool

- lib/cloud-metadata/callback-coordination.js
Closes:  #2065
Change the log message to be less alarmist.
> feat: change log message

- CHANGELOG.asciidoc
- docs/configuration.asciidoc
- lib/config.js
- test/sanitize-field-names/_fixtures.js
> feat: Add '*principal*' to `sanitizeFieldNames` to redact possible auth headers

- docs/performance-tuning.asciidoc
Fixed header name with sampled flag in docs.
> docs: header name with sampled flag

- .ci/Jenkinsfile
- .github/workflows/opentelemetry.yml
- .github/workflows/snapshoty.yml
Use GitHub action for the `snapshoty`
> action: snapshoty

- .tav.yml
- CHANGELOG.asciidoc
- docs/supported-technologies.asciidoc
- examples/trace-mongodb.js
- lib/instrumentation/modules/mongodb.js
- package-lock.json
- package.json
- test/_is_mongodb_incompat.js
- test/config.test.js
- test/instrumentation/modules/mongodb.test.js
https://github.com/mongodb/node-mongodb-native/releases/tag/v5.0.0
- min supported node is v14.20.1
- support for callbacks in the mongodb API was dropped
Closes: #3138
> mongodb@5 support

- test/stacktraces/stacktraces.test.js
> test: correct sense of test message

- docs/lambda.asciidoc
> docs: correct version in which partial Lambda transactions will be released

- dev-utils/ci-tav-slow-jobs.sh
- package-lock.json
- fix to use the "main" branch
- skip in-progress or queue'd TAV workflow runs
---
The util accidentally had debugging code that locked it to
an old dev/test branch.
> chore: fix dev-utils/ci-tav-slow-jobs.sh

- docs/log-correlation.asciidoc
Fixes broken `Ingest your logs into Elasticsearch` docs link in `main`.
> docs: Fixes broken es logs link in `main`

- docs/log-correlation.asciidoc
Fixes broken `Ingest your logs into Elasticsearch` docs link in `3.x`.
> docs: Fixes broken es logs link in `3.x`

- test/instrumentation/modules/pg/pg.test.js
Node.js has had native Promise since v0.12.
Review suggestion: Ignore whitespace for a smaller diff: https://github.com/elastic/apm-agent-nodejs/pull/3392/files?w=1
> test, refactor: simplify pg.test.js

- .github/dependabot.yml
Reduce some noise with `@babel/*` and aws-sdk dependabot updates.
> chore: tweak dependabot config to reduce some noise

- docs/agent-api.asciidoc
- docs/span-api.asciidoc
- docs/transaction-api.asciidoc
Closes: https://github.com/elastic/apm-agent-nodejs/issues/1938
> docs: clarify suggested stringify=false for setLabel/addLabels APIs

- .ci/scripts/docker-test.sh
- .ci/scripts/prepare-benchmarks-env.sh
- .github/workflows/test.yml
- test/opentelemetry-metrics/fixtures.test.js
- test/script/docker/run_tests.sh
Closes: https://github.com/elastic/apm-agent-nodejs/issues/2682
> chore: use 'npm ci' in tests

- test/fixtures/json-specs/container_metadata_discovery.json
- test/fixtures/json-specs/service_resource_inference.json
- test/service-resource-inference.test.js
APM agent specs automatic sync
*Changeset*
* https://github.com/elastic/apm/commit/5791498e9569ef9111615ef439e1cbf0b7fd7c18
---
<Actions>
<action id="8f63bcbf3d6d0df77a5c87dccadc8462ff69d5855a2d54b10a5292c892903c49">
<h3>update-jsons-specs</h3>
<details id="c7c88fb7c67da63968962fabd8e10b3b89053dddd5fc0ea6e1da5f070ad04a65">
<summary>service_resource_inference.json</summary>
<p>Updated to content &#34;&#34; in file &#34;test/fixtures/json-specs/service_resource_inference.json&#34;&#xA;</p>
</details>
<details id="51b51c35f35d91535097fd9395976b0be51211da0a6db79e48824e45a55d3156">
<summary>container_metadata_discovery.json</summary>
<p>Updated to content &#34;&#34; in file &#34;test/fixtures/json-specs/container_metadata_discovery.json&#34;&#xA;</p>
</details>
</action>
</Actions>
---
<table> …
> [Automation] Update JSON specs

- .backportrc.json
- package-lock.json
- package.json
> chore(dev): drop backport tool

- test/instrumentation/modules/cassandra-driver/cassandra-driver.test.js
New `cassandra-driver`'s tests forgot to accomodate its assertions depending if the cassandra API supports Promises or not. Long story short
- `use-cassandra-driver.js` was aware of promises API support
- `cassandra-driver.tests.js` was not
This PR puts them in sync so the test does not perform extra assertions if promises are not supported (because the use file will send less spans).
> tests: fix assertions on cassandra-driver tests

- docs/supported-technologies.asciidoc
- examples/trace-mongoose.js
PR to update docs and add an example for mongoose package as requested in https://github.com/elastic/apm-agent-nodejs/pull/3408#issuecomment-1731762215
> docs: update supported technologies and add an example for mongoose

- package-lock.json
- package.json
- test/context-propagation-only.test.js
v1.4.0 of the ecs logging libs were just released. I'm bumping our dep to sanity test with it.
> chore(deps): bump @elastic/ecs-pino-format

- test/instrumentation/modules/mongodb/mongodb.test.js
mongodb TAV test are failing in main:
- test was not getting the host from env vars
- command's address is resolved to an IP so it's a bad idea to compare to a static value
- we went too far by doing assertions of `close` commands. Previous tests did do it
> chore: fix mongodb tests for TAV

- docs/supported-technologies.asciidoc
- test/opentelemetry-metrics/fixtures/package-lock.json
Run dev-utils/update-otel-deps.js to clean-up some bumps in otel deps
recently by dependabot and #3745
> chore: update otel deps

- CHANGELOG.asciidoc
- CONTRIBUTING.md
- docs/agent-api.asciidoc
- package-lock.json
- package.json
https://github.com/elastic/apm-agent-nodejs/blob/trentm/release-4.2.0/CHANGELOG.asciidoc#420---20231123
> release 4.2.0

- CHANGELOG.asciidoc
- lib/agent.js
> chore: reduce log level of 'Sending error to Elastic APM: ...' to "debug"

- package-lock.json
- package.json
> fix: agent usage depends on v1.5.0 of ecs-pino-format

- CHANGELOG.asciidoc
- package-lock.json
- package.json
Highlights:
- https://github.com/elastic/apm-agent-nodejs/pull/3857
> release 4.4.1

- docs/esm.asciidoc
> docs: bump supported knex version in ESM doc

- .github/workflows/labeler.yml
Closes: https://github.com/elastic/apm-agent-nodejs/issues/3884
Refs: https://github.com/elastic/apm-agent-nodejs/pull/3875
> chore(ci): allow 'labeler' workflow to add labels to issues/PR

- CHANGELOG.asciidoc
- package-lock.json
- package.json
- #3923 
- #3919 
- #3963 
- #3964
> release 4.5.1

- CHANGELOG.asciidoc
- package-lock.json
- package.json
> release 4.5.3

- .tav.yml
- CHANGELOG.asciidoc
- CONTRIBUTING.md
- dev-utils/update-4x-branch.sh
- lib/instrumentation/modules/kafkajs.js
- package-lock.json
- package.json
- test/_is_undici_incompat.js
- test/instrumentation/modules/kafkajs/fixtures/use-kafkajs-each-message.js
- test/instrumentation/modules/kafkajs/kafkajs.test.js
- fix(kafkajs): handle kafka tombstone messages (#3985)
- release 4.5.3 (#3986)
> update 4x branch 20240424

- .github/workflows/release.yml
- CHANGELOG.asciidoc
> feat: make published Docker images multi-platform, add linux/arm64 plat

- CHANGELOG.asciidoc
- package-lock.json
- package.json
- https://github.com/elastic/apm-agent-nodejs/pull/4058
- https://github.com/elastic/apm-agent-nodejs/pull/4036
- https://github.com/elastic/apm-agent-nodejs/issues/4033
> release 4.6.0

- .github/workflows/release.yml
- CHANGELOG.asciidoc
- docs/span-api.asciidoc
- docs/supported-technologies.asciidoc
- docs/transaction-api.asciidoc
- index.d.ts
- lib/instrumentation/generic-span.js
- lib/instrumentation/modules/@aws-sdk/client-sqs.js
- lib/instrumentation/modules/aws-sdk/sqs.js
- lib/instrumentation/modules/kafkajs.js
- lib/lambda.js
- lib/opentelemetry-bridge/OTelBridgeNonRecordingSpan.js
- lib/opentelemetry-bridge/OTelSpan.js
- package-lock.json
- package.json
- test/instrumentation/span.test.js
- test/instrumentation/transaction.test.js
- test/opentelemetry-bridge/.tav.yml
- test/opentelemetry-bridge/OTelBridgeNonRecordingSpan.test.js
- test/opentelemetry-bridge/fixtures.test.js
- test/opentelemetry-bridge/fixtures/interface-span.js
- test/opentelemetry-bridge/package-lock.json
- test/opentelemetry-bridge/package.json
- test/opentelemetry-metrics/fixtures/.tav.yml
- test/opentelemetry-metrics/fixtures/package-lock.json
- test/opentelemetry-metrics/fixtures/package.json
- test/types/index.ts
> docs: update 4.x branch for v4.7.0 release

- test/integration/api-schema/apm-server-schema/metadata.json
APM agent json server schema automatic sync
*Changeset*
* https://github.com/elastic/apm-data/pull/321
* https://github.com/elastic/apm-data/commit/dee00d147b18d27598afd585c42cde6838270746
---
<Actions>
<action id="e779bb0c8f30a963db858c559b963edd1fa99844e8a5213fbc4f54b247007f2d">
<h3>automation: update JSON server schema specs</h3>
<details id="fa450b1827de4f90bb214eaf9924527a95b821d8f72de0b38a8f5b75ac6dcdc2">
<summary>APM agent json server schema dee00d147b18d27598afd585c42cde6838270746</summary>
<p>ran shell command &#34;tar -xzf /home/runner/work/apm-agent-nodejs/apm-agent-nodejs/json-schema.tgz &amp;&amp; git --no-pager diff&#34;</p>
</details>
<a href="https://github.com/elastic/apm-agent-nodejs/actions/runs/9806099782">GitHub Action workflow link</a>
</action>
</Actions>
--- …
> [Automation] Update JSON server schema specs

- .ci/Makefile
- .ci/docker/docker-compose.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/updatecli.yml
- CHANGELOG.asciidoc
- examples/trace-tedious.js
- lib/config/schema.js
- lib/instrumentation/modules/@aws-sdk/client-sns.js
- package-lock.json
- package.json
- renovate.json
- test/docker-compose.yml
- test/instrumentation/modules/@aws-sdk/client-sns.test.js
- test/instrumentation/modules/@aws-sdk/fixtures/use-client-sns.js
- test/instrumentation/modules/tedious.test.js
- test/start/file/elastic-apm-node.js
- test/start/file/test.test.js
> docs: update 4.x branch for v4.7.2 release

- CHANGELOG.asciidoc
- lib/apm-client/http-apm-client/container-info.js
- test/apm-client/http-apm-client/container-info.test.js
Refs: https://github.com/elastic/apm/issues/888
Closes: #4215
> feat: improved container-id parsing for ECS Fargate

- package-lock.json
- test/opentelemetry-metrics/fixtures.test.js
- test/opentelemetry-metrics/fixtures/package-lock.json
There was a recent 1.26.0/0.53.0 OTel release.
> chore(deps): update otel deps to latest

- docs/supported-technologies.asciidoc
> chore: update `tedious` entry in supported technologies

- test/stacktraces/stacktraces.test.js
This cherry-picks commit b8daf0385 from the main branch (actually one of the squashed commits in PR 3827):
https://github.com/elastic/apm-agent-nodejs/pull/3827/commits/b8daf0385e5b40dd7df28ce9d8230225608bcac1
This fixes an error in stacktraces.test.js when running with Node.js 20. That change to node v21.6.0 also made it into v20.12.0, which means this test started breaking when that was released (2024-03-26).
---
@david-luna Note this is targetting 3.x. I need this to have clean tests for https://github.com/elastic/apm-agent-nodejs/pull/4291
> test: correct the 'Error.prepareStackTrace is not set' test assumptions, node v21.6.0 sets a default Error.prepareStackTrace

- CHANGELOG.asciidoc
- package-lock.json
- package.json
A release to get the fix for #4294 out.
> release 4.8.1

- CHANGELOG.asciidoc
- package-lock.json
- package.json
> release 3.52.0

- .github/workflows/release.yml
- .github/workflows/test-fips.yml
- .github/workflows/updatecli.yml
- .tool-versions
- CHANGELOG.asciidoc
- CONTRIBUTING.md
- Dockerfile.wolfi
- lib/instrumentation/azure-functions.js
- package-lock.json
- package.json
- test/instrumentation/modules/bluebird/_coroutine.js
- test/instrumentation/modules/bluebird/bluebird.test.js
> docs: update do-not-delete_legacy-docs branch for v4.11.2 release

- CONTRIBUTING.md
- docs/release-notes/index.md
- package-lock.json
- package.json
> release 4.12.0

- docs/release-notes/index.md
- package-lock.json
- package.json
https://github.com/elastic/apm-agent-nodejs/pull/4581
> release 4.13.0
